import type{ActorRuntimeState,InventoryEntry}from"./index.js";
export interface ItemDefinition{id:string;label:string;stackLimit?:number}
export interface ProgressionDefinition{id:string;label:string;min?:number;max?:number;default:number}
export interface RuntimeStateEvent{type:"ItemGranted"|"ItemTransferred"|"ProgressionChanged"|"ActorMoved";payload:Record<string,unknown>}
const quantity=(value:number)=>{if(!Number.isSafeInteger(value)||value<=0)throw Error("item quantity must be a positive integer");return value};
const update=(entries:InventoryEntry[]|undefined,itemId:string,delta:number,limit?:number)=>{const inventory=structuredClone(entries??[]),at=inventory.findIndex(value=>value.itemId===itemId),before=at<0?0:inventory[at]!.quantity,after=before+delta;if(after<0)throw Error("insufficient item quantity");if(limit!==undefined&&after>limit)throw Error("item stack limit exceeded");if(after===0&&at>=0)inventory.splice(at,1);else if(at>=0)inventory[at]={itemId,quantity:after};else inventory.push({itemId,quantity:after});return{inventory,before,after}};
export function grantItem(sessionId:string,actor:ActorRuntimeState,item:ItemDefinition,amount:number){const result=update(actor.inventory,item.id,quantity(amount),item.stackLimit),state={...actor,inventory:result.inventory};return{state,event:{type:"ItemGranted",payload:{sessionId,actorId:actor.actorId,itemId:item.id,quantity:amount,before:result.before,after:result.after}}as RuntimeStateEvent}}
export function transferItem(sessionId:string,from:ActorRuntimeState,to:ActorRuntimeState,item:ItemDefinition,amount:number){if(from.actorId===to.actorId)throw Error("item transfer requires different actors");quantity(amount);const removed=update(from.inventory,item.id,-amount,item.stackLimit),added=update(to.inventory,item.id,amount,item.stackLimit);return{states:[{...from,inventory:removed.inventory},{...to,inventory:added.inventory}],event:{type:"ItemTransferred",payload:{sessionId,fromActorId:from.actorId,toActorId:to.actorId,itemId:item.id,quantity:amount,fromAfter:removed.after,toAfter:added.after}}as RuntimeStateEvent}}
export function changeProgression(sessionId:string,actor:ActorRuntimeState,definition:ProgressionDefinition,amount:number){if(!Number.isFinite(amount))throw Error("progression amount must be finite");const before=actor.progression?.[definition.id]??definition.default,after=before+amount;if(definition.min!==undefined&&after<definition.min||definition.max!==undefined&&after>definition.max)throw Error("progression value outside bounds");return{state:{...actor,progression:{...(actor.progression??{}),[definition.id]:after}},event:{type:"ProgressionChanged",payload:{sessionId,actorId:actor.actorId,progressionId:definition.id,amount,before,after}}as RuntimeStateEvent}}
export function moveActor(sessionId:string,actor:ActorRuntimeState,locationId:string){if(!locationId)throw Error("location is required");return{state:{...actor,locationId},event:{type:"ActorMoved",payload:{sessionId,actorId:actor.actorId,fromLocationId:actor.locationId??null,toLocationId:locationId}}as RuntimeStateEvent}}
