import{describe,expect,it}from"vitest";
import{readFile}from"node:fs/promises";
import{resolve}from"node:path";
import{assessOfficialPack,buildCharacterState,loadWorldPack}from"@masterhost/worldpack-sdk";
import{compileSatisfying}from"@masterhost/world-compiler";
import{buildDescriptor}from"@masterhost/descriptor";
import{executeAction,initializeResources,startEncounter}from"@masterhost/game-runtime";
import type{ActorRuntimeState,ResourceDefinition}from"@masterhost/game-runtime";

const slugs=["classic-fantasy","dark-fantasy","space-opera","cyberpunk","post-apocalypse","gothic-horror"];
const load=(slug:string)=>loadWorldPack(resolve("worldpacks",slug));

describe.each(slugs)("official Pack %s",slug=>{
 it("meets the official content contract and declares reusable artwork",async()=>{const pack=await load(slug),assessment=assessOfficialPack(pack);expect(assessment,assessment.errors.join("; ")).toMatchObject({passed:true});expect(pack.manifest.license?.spdx).toBe("CC-BY-4.0");expect(new Set(pack.assets).size).toBeGreaterThanOrEqual(5);for(const path of pack.assets){const source=await readFile(resolve("worldpacks",slug,path),"utf8");expect(source).toMatch(/^<svg/)}const art=pack.artSets[pack.manifest.defaultArtSet]!;expect(art.defaults?.background).toMatch(/background\.svg$/);expect(art.types?.creature?.token).toMatch(/creature\.svg$/);expect(art.types?.location?.location).toMatch(/location\.svg$/)});
 it("compiles deterministic full content in multiple descriptor modes",async()=>{const pack=await load(slug),compile=(seed:string,threat:string)=>{const choices={"world.tone":threat==="high"?"tense":"heroic","world.threat":threat,"world.environment":pack.content.questions.find(value=>value.id==="world.environment")!.options.at(-1)!.value,"world.scarcity":pack.content.questions.find(value=>value.id==="world.scarcity")!.options.at(-1)!.value},descriptor=buildDescriptor({packId:pack.manifest.id,packVersion:pack.manifest.version,choices:Object.entries(choices).map(([path,value])=>({path,value:{mode:"explicit"as const,value}})),seed});return compileSatisfying({realmId:"00000000-0000-0000-0000-000000000008",pack,descriptor,seed})};const first=compile("official-seed","high"),again=compile("official-seed","high"),alternate=compile("alternate-seed","medium");expect(first.constraints.every(value=>value.passed)).toBe(true);expect(first.world.entities.map(value=>[value.materializationPath,value.values])).toEqual(again.world.entities.map(value=>[value.materializationPath,value.values]));expect(first.world.entities.map(value=>value.kind)).toEqual(expect.arrayContaining(["location","creature","npc","item","encounter","event"]));expect(first.world.entities.length).toBeGreaterThanOrEqual(20);expect(alternate.world.entities.length).toBeGreaterThanOrEqual(20)});
 it("supports its complete Character and runtime contract",async()=>{const pack=await load(slug),schema=pack.content.characterCreation!,role=schema.steps.find(value=>value.id==="calling")!.fields[0]!.options![0]!.value,values=Object.fromEntries(schema.steps.flatMap(value=>value.fields).map(field=>[field.id,field.id==="name"?"M8 Tester":field.id==="calling"?role:field.type==="number"?2:field.default??field.options?.[0]?.value])),character=buildCharacterState(schema,values);expect(character.inventory.length).toBeGreaterThanOrEqual(2);expect(Object.keys(character.resources)).toHaveLength(3);const resources=Object.fromEntries(Object.entries(pack.content.resources!).map(([id,value])=>[id,{id,...value}]))as Record<string,ResourceDefinition>,actor=(actorId:string):ActorRuntimeState=>({actorId,resources:initializeResources(resources),effects:[]}),result=executeAction({action:{id:"basic-attack",...pack.content.actions!["basic-attack"]!},request:{sessionId:"s",actionId:"basic-attack",actorId:"a",targetActorIds:["b"],inputs:{difficulty:5}},actors:{a:actor("a"),b:actor("b")},checks:Object.fromEntries(Object.entries(pack.content.checks!).map(([id,value])=>[id,{id,...value}])),resources,effects:Object.fromEntries(Object.entries(pack.content.effects!).map(([id,value])=>[id,{id,...value}])),characterValues:{a:character.values},roller:()=>3});expect(result.events.at(-1)?.type).toBe("ActionResolved");const policy=pack.content.encounter!.orderingPolicy,attribute=pack.content.encounter!.attributeField,encounter=startEncounter({sessionId:"s",participantIds:["a","b"],policy,attributes:{a:Number(attribute?character.values[attribute]??0:0),b:0},...(policy==="custom"?{customOrder:["b","a"]}:{})});expect(encounter.encounter.participants).toHaveLength(2)});
});

it("ships six distinct official settings",async()=>{const packs=await Promise.all(slugs.map(load));expect(new Set(packs.map(value=>value.manifest.id)).size).toBe(6);expect(new Set(packs.map(value=>value.content.templates[value.manifest.entryTemplate]!.values!.name!.value)).size).toBe(6);expect(new Set(packs.map(value=>value.artSets.standard!.defaults!.background)).size).toBe(1);const backgrounds=await Promise.all(slugs.map(slug=>readFile(resolve("worldpacks",slug,"assets/ui/background.svg"),"utf8")));expect(new Set(backgrounds).size).toBe(6)});
