import {describe,it,expect} from 'vitest';
import {createContentTranslator,authoredValue,authoredActorLabel,contentFieldLabel} from '../apps/web/src/i18n/content.js';
describe('authored display localization preserves canonical state',()=>{
 const dictionaries={'classic-fantasy':{ru:{'Border Kingdoms':'Пограничные королевства','Vigor':'Сила'}},_ui:{ru:{'Game name':'Название игры','ADD':'ДОБАВИТЬ'}}};
 it('prioritizes Pack localization keys and falls back only when text is untranslated',()=>{const c=createContentTranslator('ru',dictionaries,{manifest:{id:'masterhost.classic-fantasy'},universe:{localization:{sourceLocale:'en',strings:{en:{'pattern.border':'Border Kingdoms'},ru:{'pattern.border':'Собственные королевства'}}}}});expect(c('Border Kingdoms')).toBe('Собственные королевства');expect(c('Anything','classic-fantasy','pattern.border')).toBe('Собственные королевства');expect(c('Game name')).toBe('Название игры');expect(c('unknown extension')).toBe('unknown extension');});
 it('localizes UI even when selected locale is the custom Pack source locale',()=>{const c=createContentTranslator('ru',dictionaries,{universe:{localization:{sourceLocale:'ru',strings:{ru:{title:'Русский мир'}}}}});expect(c('ADD')).toBe('ДОБАВИТЬ');expect(c('Русский мир')).toBe('Русский мир');});
 it('renders detached composed World stock copy through unambiguous source lookup',()=>{const c=createContentTranslator('ru',dictionaries,{manifest:{id:'masterhost.game.project-42'}});expect(c('Border Kingdoms')).toBe('Пограничные королевства');expect(authoredValue({value:'Border Kingdoms',source:'custom'},c)).toBe('Border Kingdoms');});
 it('resolves attribute display labels from schema IDs and preserves canonical IDs',()=>{const schema={steps:[{fields:[{id:'reflex',label:'Agility'}]}]};expect(contentFieldLabel('reflex',schema)).toBe('Agility');expect(contentFieldLabel('interface')).toBe('Interface');expect(contentFieldLabel('pilot-skill')).toBe('Pilot Skill');expect(schema.steps[0]!.fields[0]!.id).toBe('reflex');});
 it('preserves custom names even if they match translated authored copy',()=>{const c=createContentTranslator('ru',dictionaries);const source={value:'Border Kingdoms',source:'pack'},custom={...source,source:'custom'},runtime={...source,source:'runtime'};expect(authoredValue(source,c)).toBe('Пограничные королевства');expect(authoredValue(custom,c)).toBe('Border Kingdoms');expect(authoredValue(runtime,c)).toBe('Border Kingdoms');expect(source).toEqual({value:'Border Kingdoms',source:'pack'});});
 it('preserves participant, custom NPC and action identities while translating authored NPC labels',()=>{const c=createContentTranslator('ru',dictionaries),actor={worldEntityId:'entity-42',label:'Border Kingdoms',worldEntityLabel:'Border Kingdoms'};expect(authoredActorLabel(actor,c)).toBe('Пограничные королевства');expect(authoredActorLabel({...actor,labelSource:'custom'},c)).toBe('Border Kingdoms');expect(authoredActorLabel({...actor,labelSource:'pack',worldEntityNameSource:'custom'},c)).toBe('Пограничные королевства');expect(authoredActorLabel({label:'Border Kingdoms'},c)).toBe('Border Kingdoms');expect(actor.worldEntityId).toBe('entity-42');expect(createContentTranslator('en',dictionaries)('Border Kingdoms')).toBe('Border Kingdoms');});
});
