import{describe,expect,it}from"vitest";import{reconcileWorldLink}from"@masterhost/game-runtime";import type{ActorRuntimeState}from"@masterhost/game-runtime";import type{MaterializedWorld,WorldEntity}from"@masterhost/domain";
const entity=(id="entity",kind="creature",name="Scout"):WorldEntity=>({id,worldId:"world",kind,materializationPath:"world.creature.0",values:{name:{value:name,source:"pack",locked:false}},traits:[],tags:[],revision:1});
const world=(entities:WorldEntity[],revision=2):MaterializedWorld=>({id:"world",realmId:"realm",name:"World",packId:"pack",packVersion:"1",descriptor:{schemaVersion:"1",worldPack:{id:"pack",version:"1"},decisions:{},locks:[],seedPolicy:"explicit",seed:"seed"},seed:"seed",status:"draft",revision,createdAt:"now",updatedAt:"now",entities});
const actor:ActorRuntimeState={actorId:"actor",kind:"npc",label:"Custom label",templateId:"goblin",worldEntityId:"old-id",worldEntityPath:"world.creature.0",worldEntityLabel:"Old Scout",worldEntityRevision:1,worldEntityStatus:"current",attributes:{perception:3},resources:{health:8},effects:[]};
describe("World actor reconciliation",()=>{
 it("updates provenance by stable path without overwriting runtime mechanics or label",()=>{const next=reconcileWorldLink(actor,{worldEntityKinds:["creature"]},world([entity("new-id","creature","Scarlet Scout")],3));expect(next).toMatchObject({worldEntityId:"new-id",worldEntityLabel:"Scarlet Scout",worldEntityRevision:3,worldEntityStatus:"current",label:"Custom label",resources:{health:8},attributes:{perception:3}})});
 it("marks a disappeared entity and reconnects it when the path returns",()=>{const missing=reconcileWorldLink(actor,{worldEntityKinds:["creature"]},world([],4));expect(missing.worldEntityStatus).toBe("missing");expect(missing.worldEntityId).toBe("old-id");expect(reconcileWorldLink(missing,{worldEntityKinds:["creature"]},world([entity("restored")],5)).worldEntityStatus).toBe("current")});
 it("marks a path that now resolves to an incompatible kind",()=>{expect(reconcileWorldLink(actor,{worldEntityKinds:["creature"]},world([entity("replacement","region")],6)).worldEntityStatus).toBe("incompatible")});
});
