import{describe,it,expect}from"vitest";import{resolve}from"node:path";import{loadWorldPack}from"@masterhost/worldpack-sdk";import{compileWorld,generationReport,explainValue,compareWorlds,evaluateConstraints}from"@masterhost/world-compiler";import{exportMhWorld,verifyMhWorld}from"@masterhost/persistence";import{resolveAsset}from"@masterhost/domain";
const d=(id:string,v:string,x:Record<string,unknown>)=>({schemaVersion:"0.1",worldPack:{id,version:v},decisions:Object.fromEntries(Object.entries(x).map(([k,value])=>[k,{mode:"explicit",value}])),locks:[],seedPolicy:"explicit",seed:"S"} as any);
describe("world engine v0.1 supporting services",()=>{
 it("produces generation report and explainability",async()=>{const p=await loadWorldPack(resolve("worldpacks/classic-fantasy-test"));const w=compileWorld({realmId:"00000000-0000-0000-0000-000000000001",pack:p,seed:"S",descriptor:d(p.manifest.id,p.manifest.version,{"world.magic":"high"})});const r=generationReport(w);expect(r.entities).toBe(w.entities.length);const e=w.entities.find(x=>x.values.name)!;expect(explainValue(w,e.id,"name").source).toBeTruthy()});
 it("evaluates constraints",async()=>{const p=await loadWorldPack(resolve("worldpacks/cyberpunk-test"));const w=compileWorld({realmId:"00000000-0000-0000-0000-000000000001",pack:p,seed:"S",descriptor:d(p.manifest.id,p.manifest.version,{"world.streetViolence":"high"})});const c=evaluateConstraints(w,[],[{id:"districts",type:"entity-count",query:{kind:"district"},min:3}]);expect(c[0]?.passed).toBe(true)});
 it("previews regeneration differences",async()=>{const p=await loadWorldPack(resolve("worldpacks/classic-fantasy-test"));const x=d(p.manifest.id,p.manifest.version,{});const a=compileWorld({realmId:"00000000-0000-0000-0000-000000000001",pack:p,seed:"A",descriptor:x}),b=compileWorld({realmId:a.realmId,worldId:a.id,pack:p,seed:"B",descriptor:x});expect(compareWorlds(a,b)).toBeTruthy()});
 it("verifies mhworld checksums",async()=>{const p=await loadWorldPack(resolve("worldpacks/classic-fantasy-test"));const w=compileWorld({realmId:"00000000-0000-0000-0000-000000000001",pack:p,seed:"S",descriptor:d(p.manifest.id,p.manifest.version,{})});const b=exportMhWorld(w);expect(verifyMhWorld(b)).toBe(true);b.metadata+="x";expect(verifyMhWorld(b)).toBe(false)});
 it("resolves asset fallback",()=>{const x=resolveAsset("portrait",[{level:"entity"},{level:"family",assets:{roles:{portrait:{id:"goblin",path:"goblin.webp"}}}}]);expect(x?.source).toBe("family")});
});
