import type { FastifyInstance } from "fastify";
import type { LoadedWorldPack } from "@masterhost/worldpack-sdk";
import { assessOfficialPack, toLoadedWorldPack, WorldPackDocumentSchema } from "@masterhost/worldpack-sdk";
import { buildDescriptor } from "@masterhost/descriptor";
import { compileSatisfying, assertUniqueMaterializationPaths } from "@masterhost/world-compiler";
import { HostedPlatformRepository, RuntimeRepository, AdvancedEcosystemRepository, validateWorldImage } from "@masterhost/persistence";
import type { HostedRealm, PackProjectRepository, PublicationPolicy, WorldRepository } from "@masterhost/persistence";
import { randomUUID } from "node:crypto";
import { AsyncLocalStorage } from "node:async_hooks";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
declare module "fastify" { interface FastifyInstance { masterhostResolveRealm?:(req:any)=>Promise<HostedRealm>; masterhostActivePack?:(realm:HostedRealm)=>Promise<LoadedWorldPack|null>; masterhostContext?:()=>{realm:HostedRealm;pack:LoadedWorldPack|null}|undefined; masterhostRole?:(req:any,realm:HostedRealm)=>Promise<string|null>; masterhostCanRead?:(req:any,realm:HostedRealm,kind:"world"|"pack",id:string)=>Promise<boolean>; masterhostCanList?:(req:any,realm:HostedRealm,kind:"world"|"pack",id:string)=>Promise<boolean> } }

const bearer=(req:any)=>String(req.headers.authorization??"").replace(/^Bearer\s+/i,"");
const selector=(req:any)=>String(req.headers["x-realm-slug"]??req.query?.realm??req.hostname??"default").split(":")[0]!.toLowerCase();
const policies=(input:any):PublicationPolicy=>({allowCampaigns:Boolean(input?.allowCampaigns),allowFork:Boolean(input?.allowFork),allowModify:Boolean(input?.allowModify),allowCharacters:Boolean(input?.allowCharacters)});
const officialIdentity=(value:{id:string;version:string})=>`${value.id}@${value.version}`;
const latestOfficial=(packs:Map<string,LoadedWorldPack>,id:string)=>[...packs.values()].filter(value=>value.manifest.id===id).sort((a,b)=>b.manifest.version.localeCompare(a.manifest.version,undefined,{numeric:true}))[0];
const visibility=(value:any)=>{if(!["private","unlisted","public"].includes(value))throw Object.assign(Error("invalid publication visibility"),{statusCode:400});return value as"private"|"unlisted"|"public"};

export async function registerHosted(app:FastifyInstance,x:{databaseUrl:string;defaultRealmId:string;bundledPack:LoadedWorldPack;officialPacks:Map<string,LoadedWorldPack>;worlds:WorldRepository;packs:PackProjectRepository}){
 const hosted=new HostedPlatformRepository(x.databaseUrl),runtime=new RuntimeRepository(x.databaseUrl),advanced=new AdvancedEcosystemRepository(x.databaseUrl);await hosted.migrate();await advanced.migrate();await hosted.ensureDefault(x.defaultRealmId);
 const pinAttempts=new Map<string,{window:number;count:number}>(),checkPinRate=(req:any)=>{const now=Date.now(),key=String(req.ip??"unknown"),current=pinAttempts.get(key);if(!current||now-current.window>=60_000){pinAttempts.set(key,{window:now,count:1});return}if(current.count>=20)throw Object.assign(Error("PIN resolver rate limit exceeded"),{statusCode:429});current.count++};
 const resolveRealm=async(req:any)=>{const requested=selector(req),found=await hosted.resolve(requested),realm=found??(["localhost","127.0.0.1"].includes(requested)?await hosted.resolve("default"):null);if(!realm)throw Object.assign(Error("Realm not found"),{statusCode:404});return realm};
 const requirePlatform=(req:any)=>{const expected=process.env.MASTERHOST_PLATFORM_KEY??"local-platform-admin";if(bearer(req)!==expected)throw Object.assign(Error("platform authorization required"),{statusCode:403})};
 const requireAdmin=async(req:any,id:string)=>{if(!await hosted.verifyAdmin(id,bearer(req)))throw Object.assign(Error("Realm admin authorization required"),{statusCode:403})};
 const roleFor=(req:any,realm:HostedRealm)=>hosted.role(realm.id,bearer(req));
 const requireRole=async(req:any,realm:HostedRealm,allowed:string[])=>{const role=await roleFor(req,realm);if(!role||!allowed.includes(role))throw Object.assign(Error("Realm role authorization required"),{statusCode:403});return role};
 const canRead=async(req:any,realm:HostedRealm,kind:"world"|"pack",id:string)=>{if(realm.slug==="default"||["owner","creator"].includes(await roleFor(req,realm)??""))return true;const publication=await hosted.publication(realm.id,kind,id);return Boolean(publication&&publication.visibility!=="private")};
 const canList=async(req:any,realm:HostedRealm,kind:"world"|"pack",id:string)=>{if(realm.slug==="default"||["owner","creator"].includes(await roleFor(req,realm)??""))return true;return(await hosted.publication(realm.id,kind,id))?.visibility==="public"};
 const authorizeStandard=async(req:any,realm:HostedRealm)=>{
  if(realm.slug==="default")return;
  const path=String(req.url).split("?")[0]!,role=await roleFor(req,realm),write=!["GET","HEAD","OPTIONS"].includes(req.method);
  if(path.startsWith("/api/pack-projects")&&!["owner","creator"].includes(role??""))throw Object.assign(Error("Creator role required"),{statusCode:403});
  if(write&&path.startsWith("/api/worlds")){
   if(["owner","creator"].includes(role??""))return;
   const worldId=path.match(/^\/api\/worlds\/([^/]+)/)?.[1],publication=worldId?await hosted.publication(realm.id,"world",worldId):null,permission=path.endsWith("/fork")?publication?.policies.allowFork:publication?.policies.allowModify;
   if(role==="gm"&&permission)return;
   throw Object.assign(Error("World modification is not permitted"),{statusCode:403});
  }
  if(req.method==="POST"&&path==="/api/campaigns"){
   if(!["owner","creator","gm"].includes(role??""))throw Object.assign(Error("Realm GM role required"),{statusCode:403});
   const publication=await hosted.publication(realm.id,"world",String(req.body?.worldId??""));
   if(!publication?.policies.allowCampaigns||req.body?.characterPortability==="pack"&&!publication.policies.allowCharacters)throw Object.assign(Error("Published World does not permit this Campaign"),{statusCode:403});
  }
 };
 const activePack=async(realm:HostedRealm)=>{if(realm.activePack){const project=(await x.packs.list(realm.id)).find(value=>value.status==="published"&&value.document.manifest.id===realm.activePack!.id&&value.document.manifest.version===realm.activePack!.version);if(project)return toLoadedWorldPack(project.document);return x.officialPacks.get(officialIdentity(realm.activePack))??null}return realm.slug==="default"?x.bundledPack:null};
 const contexts=new AsyncLocalStorage<{realm:HostedRealm;pack:LoadedWorldPack|null}>();app.decorate("masterhostResolveRealm",resolveRealm);app.decorate("masterhostActivePack",activePack);app.decorate("masterhostContext",()=>contexts.getStore());app.decorate("masterhostRole",roleFor);app.decorate("masterhostCanRead",canRead);app.decorate("masterhostCanList",canList);app.addHook("onRequest",(req,_reply,done)=>{resolveRealm(req).then(async realm=>{await authorizeStandard(req,realm);return{realm,pack:await activePack(realm)}}).then(context=>contexts.run(context,done)).catch(done)});

 app.get("/api/host/realm",async(req:any)=>{const realm=await resolveRealm(req);return{...realm,role:await roleFor(req,realm),assets:await hosted.assets(realm.id),catalog:await hosted.catalog(realm.id)}});
 app.post("/api/host/realms",async(req:any)=>{requirePlatform(req);return hosted.create(req.body??{})});
 app.post("/api/host/realms/:id/members",async(req:any)=>{await requireAdmin(req,req.params.id);return hosted.createMembership(req.params.id,String(req.body?.name??""),req.body?.role)});
 app.put("/api/host/realms/:id",async(req:any)=>{await requireAdmin(req,req.params.id);const active=req.body?.activePack;if(active){const project=(await x.packs.list(req.params.id)).some(value=>value.status==="published"&&value.document.manifest.id===active.id&&value.document.manifest.version===active.version),official=x.officialPacks.get(officialIdentity(active));if(!project&&!official)throw Object.assign(Error("active Pack version is neither published in this Realm nor installed official content"),{statusCode:409})}return hosted.update(req.params.id,req.body??{})});
 app.get("/api/official-packs",async()=>[...new Set([...x.officialPacks.values()].map(pack=>pack.manifest.id))].map(id=>latestOfficial(x.officialPacks,id)!).map(pack=>({manifest:pack.manifest,assessment:assessOfficialPack(pack),artSets:Object.values(pack.artSets),assets:pack.assets,content:{kinds:[...new Set(Object.values(pack.content.templates).map(value=>value.kind))],characters:pack.content.characterCreation?.steps.map(value=>value.title)??[],checks:Object.values(pack.content.checks??{}).map(value=>value.label),items:Object.values(pack.content.items??{}).map(value=>value.label),actors:Object.values(pack.content.actorTemplates??{}).map(value=>value.label)}})).sort((a,b)=>a.manifest.name.localeCompare(b.manifest.name)));
 app.get("/api/official-packs/:id",async(req:any)=>{const pack=latestOfficial(x.officialPacks,req.params.id);if(!pack)throw Object.assign(Error("official Pack not found"),{statusCode:404});return{manifest:pack.manifest,assessment:assessOfficialPack(pack),questions:pack.content.questions,artSets:pack.artSets,assets:pack.assets,content:pack.content}});
 app.get("/api/official-packs/:id/assets/*",async(req:any,reply)=>{const pack=latestOfficial(x.officialPacks,req.params.id),requested=`assets/${String(req.params["*"]??"")}`;if(!pack?.root||!pack.assets.includes(requested))throw Object.assign(Error("official Pack asset not found"),{statusCode:404});reply.header("content-type",requested.endsWith(".svg")?"image/svg+xml":"application/octet-stream");reply.header("cache-control","public, max-age=31536000, immutable");reply.header("x-content-type-options","nosniff");return reply.send(await readFile(join(pack.root,requested)))});
 app.post("/api/host/realms/:id/assets/:role",async(req:any)=>{await requireAdmin(req,req.params.id);const realm=await hosted.realm(req.params.id);if(!realm)throw Object.assign(Error("Realm not found"),{statusCode:404});if(!Buffer.isBuffer(req.body))throw Object.assign(Error("binary brand image required"),{statusCode:415});await hosted.assertQuota(realm,"assetBytes",req.body.length);const mediaType=String(req.headers["x-asset-media-type"]??"");validateWorldImage(`${req.params.role}.png`,mediaType,req.body);const result=await hosted.putObject(realm.id,req.params.role,mediaType,req.body);await hosted.record(realm.id,"brand.asset.uploaded",req.body.length);return result});
 app.get("/api/cdn/:checksum",async(req:any,reply)=>{const object=await hosted.object(req.params.checksum);if(!object)throw Object.assign(Error("object not found"),{statusCode:404});reply.header("content-type",object.mediaType);reply.header("cache-control","public, max-age=31536000, immutable");reply.header("etag",`\"sha256-${req.params.checksum}\"`);reply.header("x-content-type-options","nosniff");return reply.send(Buffer.from(object.data))});
 app.post("/api/host/realms/:id/publications",async(req:any)=>{await requireAdmin(req,req.params.id);const realm=await hosted.realm(req.params.id);if(!realm)throw Object.assign(Error("Realm not found"),{statusCode:404});const kind=req.body?.kind,resourceId=String(req.body?.resourceId??"");if(kind==="world"){const world=await x.worlds.get(resourceId);if(!world||world.realmId!==realm.id)throw Object.assign(Error("World not found in Realm"),{statusCode:404});await x.worlds.publish(world.id,realm.id)}else if(kind==="pack"){const project=await x.packs.get(resourceId);if(!project||project.realmId!==realm.id||project.status!=="published")throw Object.assign(Error("published Pack not found in Realm"),{statusCode:404})}else throw Object.assign(Error("publication kind must be world or pack"),{statusCode:400});const result=await hosted.publish({realmId:realm.id,kind,resourceId,visibility:visibility(req.body?.visibility),policies:policies(req.body?.policies)});await hosted.record(realm.id,`${kind}.published`);return result});
 app.get("/api/host/catalog",async(req:any)=>{const realm=await resolveRealm(req),admin=await hosted.verifyAdmin(realm.id,bearer(req));return hosted.catalog(realm.id,admin)});
 app.get("/api/community/packs",async(req:any)=>advanced.communityCatalog({query:req.query?.query,tag:req.query?.tag,license:req.query?.license}));
 app.get("/api/host/collaboration/:kind/:resourceId",async(req:any)=>{const realm=await resolveRealm(req);await requireRole(req,realm,["owner","creator"]);const project=await x.packs.get(req.params.resourceId);if(!project||project.realmId!==realm.id||project.status!=="draft")throw Object.assign(Error("draft Pack project not found in Realm"),{statusCode:404});const document=await advanced.collaboration(realm.id,req.params.kind,req.params.resourceId);return document?{...document,history:await advanced.collaborationHistory(document.id)}:{id:null,realmId:realm.id,resourceKind:"pack",resourceId:project.id,revision:0,content:project.document,history:[]}});
 app.put("/api/host/collaboration/:kind/:resourceId",async(req:any)=>{const realm=await resolveRealm(req);await requireRole(req,realm,["owner","creator"]);if(req.params.kind!=="pack")throw Object.assign(Error("collaboration kind must be pack"),{statusCode:400});const identity=await hosted.identity(realm.id,bearer(req)),project=await x.packs.get(req.params.resourceId);if(!identity||!project||project.realmId!==realm.id||project.status!=="draft")throw Object.assign(Error("draft Pack project not found in Realm"),{statusCode:404});const content=WorldPackDocumentSchema.parse(req.body?.content);return advanced.saveCollaboration({realmId:realm.id,resourceKind:"pack",resourceId:project.id,expectedRevision:Number(req.body?.expectedRevision),content,authorId:identity.id,summary:String(req.body?.summary??"Updated draft").slice(0,240),project})});
 app.get("/api/host/publications/:kind/:resourceId",async(req:any)=>{const realm=await resolveRealm(req),item=await hosted.publication(realm.id,req.params.kind,req.params.resourceId);if(!item||item.visibility==="private"&&!await hosted.verifyAdmin(realm.id,bearer(req)))throw Object.assign(Error("publication not found"),{statusCode:404});return item});
 app.post("/api/host/worlds/generate",async(req:any)=>{const realm=await resolveRealm(req);await requireRole(req,realm,["owner","creator"]);const pack=await activePack(realm);if(!pack)throw Object.assign(Error("Realm has no active published Pack"),{statusCode:409});await hosted.assertQuota(realm,"worlds");const seed=String(req.body?.seed??randomUUID()),choices=Object.entries(req.body?.choices??{}).map(([path,value])=>({path,value:{mode:"explicit"as const,value}})),descriptor=buildDescriptor({packId:pack.manifest.id,packVersion:pack.manifest.version,choices,seed}),compiled=compileSatisfying({realmId:realm.id,descriptor,pack,seed});if(compiled.constraints.some(value=>!value.passed))throw Object.assign(Error("Pack constraints could not be satisfied"),{statusCode:409});assertUniqueMaterializationPaths(compiled.world);const saved=await x.worlds.save(compiled.world,`realm:${realm.slug}`);await hosted.record(realm.id,"world.generated");return saved});
 app.post("/api/host/worlds/:id/fork",async(req:any)=>{const realm=await resolveRealm(req);await requireRole(req,realm,["owner","creator","gm"]);const source=await x.worlds.get(req.params.id),publication=await hosted.publication(realm.id,"world",req.params.id);if(!source||source.realmId!==realm.id||!publication?.policies.allowFork)throw Object.assign(Error("World is not forkable in this Realm"),{statusCode:403});await hosted.assertQuota(realm,"worlds");const fork=await x.worlds.fork(source,String(req.body?.name??`${source.name} Fork`).trim());await hosted.record(realm.id,"world.forked");return fork});
 app.post("/api/host/campaigns",async(req:any)=>{const realm=await resolveRealm(req);await requireRole(req,realm,["owner","creator","gm"]);const world=await x.worlds.get(req.body?.worldId),publication=world?await hosted.publication(realm.id,"world",world.id):null;if(!world||world.realmId!==realm.id||!publication?.policies.allowCampaigns)throw Object.assign(Error("World does not allow Campaign creation"),{statusCode:403});if(req.body?.characterPortability==="pack"&&!publication.policies.allowCharacters)throw Object.assign(Error("World does not allow portable Characters"),{statusCode:403});const pack=await activePack(realm);if(!pack||world.packId!==pack.manifest.id||world.packVersion!==pack.manifest.version)throw Object.assign(Error("World Pack is not active for this Realm"),{statusCode:409});await hosted.record(realm.id,"campaign.created");return runtime.createCampaign({realmId:realm.id,worldId:world.id,name:req.body?.name??"New Campaign",characterPortability:req.body?.characterPortability??"exact"})});
 app.post("/api/host/campaigns/:id/sessions",async(req:any)=>{const realm=await resolveRealm(req),campaign=await runtime.campaign(req.params.id);if(!campaign||campaign.realmId!==realm.id)throw Object.assign(Error("Campaign not found in Realm"),{statusCode:404});if(!await runtime.verifyCampaignGm(campaign.id,bearer(req)))throw Object.assign(Error("GM authorization required"),{statusCode:403});await hosted.assertQuota(realm,"activeSessions");const session=await runtime.startLobby({realmId:realm.id,campaignId:campaign.id});await hosted.record(realm.id,"session.started");return session});
 app.post("/api/join/resolve-global",async(req:any)=>{checkPinRate(req);const session=await runtime.resolveGlobalPin(String(req.body?.pin??""));if(!session)throw Object.assign(Error("PIN not found, expired, or ambiguous"),{statusCode:404});const realm=await hosted.realm(session.realmId);if(!realm)throw Object.assign(Error("Realm unavailable"),{statusCode:404});return{session,realm:{slug:realm.slug,name:realm.name,brand:realm.brand,assets:await hosted.assets(realm.id)},campaign:await runtime.campaign(session.campaignId)}});
 app.get("/api/host/realms/:id/usage",async(req:any)=>{await requireAdmin(req,req.params.id);const realm=await hosted.realm(req.params.id);if(!realm)throw Object.assign(Error("Realm not found"),{statusCode:404});return{usage:await hosted.usage(realm.id),quotas:realm.quotas}});
 app.get("/api/host/realms/:id/telemetry",async(req:any)=>{await requireAdmin(req,req.params.id);return hosted.telemetry(req.params.id)});
 app.post("/api/host/realms/:id/backups",async(req:any)=>{await requireAdmin(req,req.params.id);const result=await hosted.backup(req.params.id);await hosted.record(req.params.id,"backup.created");return result});
 app.post("/api/host/realms/:id/backups/:backupId/restore",async(req:any)=>{await requireAdmin(req,req.params.id);const result=await hosted.restore(req.params.id,req.params.backupId);await hosted.record(req.params.id,"backup.restored");return result});
 return{hosted,resolveRealm,activePack};
}
