import Fastify from"fastify";import cors from"@fastify/cors";import{randomUUID}from"node:crypto";import{resolve,join}from"node:path";import{fileURLToPath}from"node:url";import{readFile}from"node:fs/promises";
import{loadWorldPack,validateWorldPack,createStarterPack,validateWorldPackDocument,toLoadedWorldPack,packSource,WorldPackDocumentSchema}from"@masterhost/worldpack-sdk";import type{PackDiagnostic,WorldPackProject}from"@masterhost/worldpack-sdk";import{buildDescriptor}from"@masterhost/descriptor";
import{compileWorld,compileSatisfying,customizeValue,assignEntityImage,regenerateWorld,generationReport,explainValue,compareWorlds,scopeSummary,preserveCustomByPath,assertUniqueMaterializationPaths,createWorldEntity,updateWorldEntity,editWorldValue,worldDependencyGraph,entityRemovalImpact,removeWorldEntity,entityRegenerationImpact,regenerateWorldEntity}from"@masterhost/world-compiler";
import{assetRoles}from"@masterhost/domain";import type{WorldArtSet}from"@masterhost/domain";
import{WorldRepository,PackProjectRepository,exportMhWorldZip,importMhWorldZipWithAssets,exportMhPack,importMhPack,withMigrationLock,assetChecksum,validateWorldImage}from"@masterhost/persistence";import{registerRuntime}from"./runtime.js";
const app=Fastify({logger:true});await app.register(cors,{origin:true,methods:["GET","HEAD","POST","PUT","PATCH","DELETE"]});
app.addContentTypeParser("application/vnd.masterhost.world+zip",{parseAs:"buffer",bodyLimit:10_000_000},(_req,body,done)=>done(null,body));
app.addContentTypeParser("application/vnd.masterhost.pack+zip",{parseAs:"buffer",bodyLimit:10_000_000},(_req,body,done)=>done(null,body));
app.addContentTypeParser("application/octet-stream",{parseAs:"buffer",bodyLimit:2_000_000},(_req,body,done)=>done(null,body));
const repositoryRoot=fileURLToPath(new URL("../../../",import.meta.url));
const pack=await loadWorldPack(resolve(repositoryRoot,process.env.WORLD_PACK_PATH??"worldpacks/classic-fantasy-test"));
const databaseUrl=process.env.DATABASE_URL??"postgresql://masterhost:masterhost@localhost:5432/masterhost";
const repo=new WorldRepository(databaseUrl);
const packProjects=new PackProjectRepository(databaseUrl);
app.masterhostWorldRepository=repo;
const realmId="00000000-0000-0000-0000-000000000001";
const must=async(id:string)=>{const w=await repo.get(id);if(!w)throw Object.assign(Error("world not found"),{statusCode:404});return w};

app.get("/health",async()=>({status:"ok",pack:`${pack.manifest.id}@${pack.manifest.version}`}));
app.get("/api/pack",async()=>({manifest:pack.manifest,questions:pack.content.questions,artSets:pack.artSets,validation:validateWorldPack(pack)}));
app.get("/api/pack/assets/*",async(req:any,reply)=>{const requested=String(req.params["*"]??"").replace(/^assets\//,"");if(!pack.assets.includes(`assets/${requested}`))throw Object.assign(Error("Pack asset not found"),{statusCode:404});reply.header("content-type",requested.endsWith(".svg")?"image/svg+xml":"application/octet-stream");reply.header("x-content-type-options","nosniff");return reply.send(await readFile(join(pack.root,"assets",requested)))});

const mustProject=async(id:string)=>{const project=await packProjects.get(id);if(!project||project.realmId!==realmId)throw Object.assign(Error("Pack project not found"),{statusCode:404});return project};
const conformance=async(project:WorldPackProject)=>{const result=validateWorldPackDocument(project.document,project.assetData),diagnostics=[...result.diagnostics];if(!result.valid||!result.document)return{valid:false,diagnostics,fixtures:[]};const loaded=toLoadedWorldPack(result.document),fixtures=[] as any[];for(const fixture of result.document.fixtures)try{const choices=Object.entries(fixture.choices).map(([path,value])=>({path,value:{mode:"explicit"as const,value}})),descriptor=buildDescriptor({packId:loaded.manifest.id,packVersion:loaded.manifest.version,choices,seed:fixture.seed}),first=compileSatisfying({realmId,descriptor,pack:loaded,seed:fixture.seed}),second=compileSatisfying({realmId,descriptor,pack:loaded,seed:fixture.seed,worldId:first.world.id}),kinds=[...new Set(first.world.entities.map(value=>value.kind))];if(JSON.stringify(first.world.entities.map(value=>[value.materializationPath,value.values]))!==JSON.stringify(second.world.entities.map(value=>[value.materializationPath,value.values])))throw Error("fixture is not deterministic");if(fixture.expect?.minimumEntities&&first.world.entities.length<fixture.expect.minimumEntities)throw Error(`expected at least ${fixture.expect.minimumEntities} entities`);for(const kind of fixture.expect?.kinds??[])if(!kinds.includes(kind))throw Error(`expected kind ${kind}`);if(first.constraints.some(value=>!value.passed))throw Error("fixture constraints failed");fixtures.push({id:fixture.id,passed:true,entities:first.world.entities.length,kinds})}catch(error){diagnostics.push({severity:"error",code:"fixture",path:`fixtures.${fixture.id}`,message:error instanceof Error?error.message:"fixture failed"})}const published=await packProjects.list(realmId);for(const dependency of result.document.dependencies)if(!published.some(value=>value.status==="published"&&value.document.manifest.id===dependency.id&&value.document.manifest.version===dependency.version))diagnostics.push({severity:"error",code:"dependency",path:"dependencies",message:`Missing published dependency ${dependency.id}@${dependency.version}`});return{valid:diagnostics.every(value=>value.severity!=="error"),diagnostics,fixtures}};
app.get("/api/pack-projects",async()=>packProjects.list(realmId));
app.post("/api/pack-projects",async(req:any)=>{const project=createStarterPack({realmId,id:req.body?.id,name:req.body?.name,version:req.body?.version,worldKind:req.body?.worldKind,worldName:req.body?.worldName,childKind:req.body?.childKind,childName:req.body?.childName}),validation=validateWorldPackDocument(project.document,project.assetData);if(!validation.valid)throw Object.assign(Error(validation.diagnostics.map(value=>value.message).join("; ")),{statusCode:400});return packProjects.create(project)});
app.post("/api/pack-projects/import",async(req:any)=>{if(!Buffer.isBuffer(req.body))throw Object.assign(Error("mhpack ZIP body required"),{statusCode:415});let project;try{project=importMhPack(req.body,realmId);for(const[name,data]of Object.entries(project.assetData)){const meta=project.document.assets[name]!;validateWorldImage(name,meta.mediaType,Buffer.from(data,"base64"))}}catch(error){throw Object.assign(Error(error instanceof Error?error.message:"Invalid mhpack archive"),{statusCode:400})}return packProjects.create(project)});
app.get("/api/pack-projects/:id",async(req:any)=>mustProject(req.params.id));
app.post("/api/pack-projects/:id/clone",async(req:any)=>{const source=await mustProject(req.params.id),version=String(req.body?.version??"").trim();if(!version)throw Error("new version is required");const now=new Date().toISOString(),next:WorldPackProject={...structuredClone(source),id:randomUUID(),status:"draft",revision:1,createdAt:now,updatedAt:now,publishedAt:undefined};next.document.manifest.version=version;return packProjects.create(next)});
app.put("/api/pack-projects/:id",async(req:any)=>{const current=await mustProject(req.params.id);if(current.status!=="draft")throw Object.assign(Error("published Pack versions are immutable"),{statusCode:409});const document=WorldPackDocumentSchema.parse(req.body?.document),next=structuredClone(current);next.document=document;next.revision++;next.updatedAt=new Date().toISOString();return packProjects.save(next)});
app.post("/api/pack-projects/:id/assets",async(req:any)=>{const current=await mustProject(req.params.id);if(current.status!=="draft")throw Object.assign(Error("published Pack versions are immutable"),{statusCode:409});if(!Buffer.isBuffer(req.body))throw Object.assign(Error("binary image required"),{statusCode:415});const name=String(req.query?.name??""),mediaType=String(req.headers["x-asset-media-type"]??"");validateWorldImage(name,mediaType,req.body);const next=structuredClone(current),checksum=assetChecksum(req.body);next.assetData[name]=Buffer.from(req.body).toString("base64");next.document.assets[name]={mediaType,checksum,size:req.body.length};next.revision++;next.updatedAt=new Date().toISOString();return packProjects.save(next)});
app.get("/api/pack-projects/:id/assets/:name",async(req:any,reply)=>{const project=await mustProject(req.params.id),meta=project.document.assets[req.params.name],data=project.assetData[req.params.name];if(!meta||!data)throw Object.assign(Error("Pack asset not found"),{statusCode:404});reply.header("content-type",meta.mediaType);reply.header("x-content-type-options","nosniff");return reply.send(Buffer.from(data,"base64"))});
app.get("/api/pack-projects/:id/source/:format",async(req:any,reply)=>{const project=await mustProject(req.params.id),source=packSource(project.document),format=req.params.format;if(format!=="json"&&format!=="yaml")throw Object.assign(Error("source format must be json or yaml"),{statusCode:400});reply.header("content-type",format==="json"?"application/json":"application/yaml");reply.header("content-disposition",`attachment; filename="${project.document.manifest.id}.${format}"`);return reply.send(source[format as"json"|"yaml"])});
app.get("/api/pack-projects/:id/export",async(req:any,reply)=>{const project=await mustProject(req.params.id);reply.header("content-type","application/vnd.masterhost.pack+zip");reply.header("content-disposition",`attachment; filename="${project.document.manifest.id}-${project.document.manifest.version}.mhpack"`);return reply.send(Buffer.from(exportMhPack(project)))});
app.post("/api/pack-projects/:id/validate",async(req:any)=>conformance(await mustProject(req.params.id)));
app.post("/api/pack-projects/:id/publish",async(req:any)=>{const project=await mustProject(req.params.id),result=await conformance(project);if(!result.valid)throw Object.assign(Error(result.diagnostics.map((value:PackDiagnostic)=>value.message).join("; ")),{statusCode:409});return{project:await packProjects.publish(project.id),conformance:result}});
app.post("/api/pack-projects/:id/generate-world",async(req:any)=>{const project=await mustProject(req.params.id);if(project.status!=="published")throw Object.assign(Error("Pack version must be published"),{statusCode:409});const loaded=toLoadedWorldPack(project.document),seed=req.body?.seed??randomUUID(),choices=Object.entries(req.body?.choices??{}).map(([path,value])=>({path,value:{mode:"explicit"as const,value}})),descriptor=buildDescriptor({packId:loaded.manifest.id,packVersion:loaded.manifest.version,choices,seed}),compiled=compileSatisfying({realmId,descriptor,pack:loaded,seed});if(compiled.constraints.some(value=>!value.passed))throw Object.assign(Error("Pack constraints could not be satisfied"),{statusCode:409});assertUniqueMaterializationPaths(compiled.world);return repo.save(compiled.world,`pack:${loaded.manifest.id}@${loaded.manifest.version}`)});
app.get("/api/worlds",async()=>repo.list());
app.post("/api/worlds/import",async(req:any)=>{if(!Buffer.isBuffer(req.body))throw Object.assign(Error("mhworld ZIP body required"),{statusCode:415});let result;try{result=importMhWorldZipWithAssets(req.body,realmId)}catch(error){throw Object.assign(Error(error instanceof Error?error.message:"Invalid mhworld archive"),{statusCode:400})}const{world,assets}=result;if(world.packId!==pack.manifest.id||world.packVersion!==pack.manifest.version)throw Object.assign(Error("required World Pack version is not active"),{statusCode:409});assertUniqueMaterializationPaths(world);return repo.saveImported(world,assets)});
app.post("/api/worlds",async(req:any)=>{const seed=req.body?.seed??randomUUID(),choices=Object.entries(req.body?.choices??{}).map(([path,value])=>({path,value:{mode:"explicit"as const,value},locked:Boolean(req.body?.locks?.includes(path))})),descriptor=buildDescriptor({packId:pack.manifest.id,packVersion:pack.manifest.version,choices,seed}),world=compileWorld({realmId,descriptor,pack,seed});assertUniqueMaterializationPaths(world);return repo.save(world,"compile")});
app.get("/api/worlds/:id",async(req:any)=>must(req.params.id));
app.post("/api/worlds/:id/assets",async(req:any)=>{await must(req.params.id);if(!Buffer.isBuffer(req.body))throw Object.assign(Error("binary image required"),{statusCode:415});try{return await repo.putAsset(req.params.id,String(req.query?.name??""),String(req.headers["x-asset-media-type"]??""),req.body,req.query?.replace==="1")}catch(error){throw Object.assign(Error(error instanceof Error?error.message:"Invalid asset"),{statusCode:(error as any)?.statusCode??400})}});
app.get("/api/worlds/:id/assets/:name",async(req:any,reply)=>{await must(req.params.id);const asset=await repo.asset(req.params.id,req.params.name);if(!asset)throw Object.assign(Error("asset not found"),{statusCode:404});reply.header("content-type",asset.mediaType);reply.header("x-content-type-options","nosniff");reply.header("content-disposition",`${req.query?.inline==="1"?"inline":"attachment"}; filename="${req.params.name}"`);return reply.send(Buffer.from(asset.data))});
app.patch("/api/worlds/:id/entities/:entityId/assets/:role",async(req:any)=>{const world=await must(req.params.id);try{return await repo.save(assignEntityImage(world,req.params.entityId,req.params.role,req.body?.name),`image:${req.params.entityId}.${req.params.role}`)}catch(error){if(error&&typeof error==="object"&&"statusCode" in error)throw error;throw Object.assign(Error(error instanceof Error?error.message:"Invalid image assignment"),{statusCode:400})}});
app.patch("/api/worlds/:id/assets/:name/metadata",async(req:any)=>repo.updateAssetMetadata(req.params.id,req.params.name,{title:req.body?.title,tags:req.body?.tags,variants:req.body?.variants}));
app.delete("/api/worlds/:id/assets/:name",async(req:any)=>repo.deleteAsset(req.params.id,req.params.name));

app.patch("/api/worlds/:id/values",async(req:any)=>{const w=await must(req.params.id);return repo.save(customizeValue(w,req.body.entityId,req.body.key,req.body.value,req.body.locked??true),`customize:${req.body.entityId}.${req.body.key}`)});

const baseline=(world:any,seed=world.seed)=>compileWorld({realmId:world.realmId,descriptor:world.descriptor,pack,seed,worldId:world.id});
const editor=(world:any)=>{const graph=worldDependencyGraph(world),customArtSets=world.authoring?.artSets??{},activeArtSetId=world.authoring?.activeArtSetId??pack.manifest.defaultArtSet,active:any=customArtSets[activeArtSetId]??pack.artSets[activeArtSetId],resolveArt=(item:any)=>Object.fromEntries(assetRoles.map(role=>{const direct=item.assets?.roles?.[role]?.path,family=item.tags.find((tag:string)=>active?.families?.[tag]?.[role]),fallback=direct??active?.types?.[item.kind]?.[role]??(family?active.families[family][role]:undefined)??active?.defaults?.[role];return[role,fallback?{path:fallback,source:direct?"entity":active?.types?.[item.kind]?.[role]?"type":family?"family":"art-set",kind:direct||customArtSets[activeArtSetId]?"world":"pack"}:null]}));return{kinds:[...new Set(Object.values(pack.content.templates).map(value=>value.kind))].sort(),graph,media:Object.entries(world.assets??{}).map(([name,ref]:any)=>({name,...ref,...world.authoring?.assetMetadata?.[name]})),artSets:{builtIn:pack.artSets,custom:customArtSets,activeArtSetId},resolvedArt:Object.fromEntries(world.entities.map((item:any)=>[item.id,resolveArt(item)])),revision:world.revision}};
app.get("/api/worlds/:id/editor",async(req:any)=>editor(await must(req.params.id)));
app.post("/api/worlds/:id/entities",async(req:any)=>{const world=await must(req.params.id),result=createWorldEntity(world,{kind:req.body?.kind,name:req.body?.name,parentId:req.body?.parentId,values:req.body?.values,tags:req.body?.tags});return repo.save(result.world,`entity-create:${result.entity.id}`)});
app.patch("/api/worlds/:id/entities/:entityId",async(req:any)=>{const world=await must(req.params.id);return repo.save(updateWorldEntity(world,req.params.entityId,{kind:req.body?.kind,parentId:req.body?.parentId,tags:req.body?.tags,traits:req.body?.traits}),`entity-update:${req.params.entityId}`)});
app.get("/api/worlds/:id/entities/:entityId/remove-impact",async(req:any)=>entityRemovalImpact(await must(req.params.id),req.params.entityId));
app.delete("/api/worlds/:id/entities/:entityId",async(req:any)=>{const world=await must(req.params.id),result=removeWorldEntity(world,req.params.entityId);return repo.save(result.world,`entity-remove:${req.params.entityId}`)});
app.patch("/api/worlds/:id/entities/:entityId/values/:key",async(req:any)=>{const world=await must(req.params.id),next=editWorldValue(world,baseline(world),req.params.entityId,req.params.key,{mode:req.body?.mode,value:req.body?.value});return repo.save(next,`value-${req.body?.mode}:${req.params.entityId}.${req.params.key}`)});
app.get("/api/worlds/:id/entities/:entityId/regenerate-impact",async(req:any)=>{const world=await must(req.params.id);return entityRegenerationImpact(world,baseline(world,`${world.seed}:regen:${world.revision+1}`),req.params.entityId)});
app.post("/api/worlds/:id/entities/:entityId/regenerate",async(req:any)=>{const world=await must(req.params.id);await repo.snapshot(world,req.body?.snapshotName??`Before entity regeneration r${world.revision}`);const result=regenerateWorldEntity(world,baseline(world,`${world.seed}:regen:${world.revision+1}`),req.params.entityId);return repo.save(result.world,`entity-regenerate:${req.params.entityId}`)});

const validateArtSet=(world:any,input:any):WorldArtSet=>{if(!input||!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/.test(input.id)||typeof input.name!=="string"||!input.name.trim())throw Error("invalid Art Set");const check=(mapping:any)=>{for(const[role,name]of Object.entries(mapping??{})){if(!assetRoles.includes(role as any)||typeof name!=="string"||!world.assets?.[name])throw Error(`invalid Art Set asset ${role}`)}};check(input.defaults);for(const value of Object.values(input.families??{}))check(value);for(const value of Object.values(input.types??{}))check(value);return{id:input.id,name:input.name.trim(),description:typeof input.description==="string"?input.description.trim():undefined,defaults:input.defaults??{},families:input.families??{},types:input.types??{}}};
app.put("/api/worlds/:id/artsets/:artSetId",async(req:any)=>{const world=await must(req.params.id),artSet=validateArtSet(world,{...req.body,id:req.params.artSetId}),next=structuredClone(world);next.authoring={...next.authoring,artSets:{...next.authoring?.artSets,[artSet.id]:artSet}};next.revision++;next.updatedAt=new Date().toISOString();return repo.save(next,`artset-save:${artSet.id}`)});
app.post("/api/worlds/:id/artsets/:artSetId/activate",async(req:any)=>{const world=await must(req.params.id);if(!pack.artSets[req.params.artSetId]&&!world.authoring?.artSets?.[req.params.artSetId])throw Error("Art Set not found");const next=structuredClone(world);next.authoring={...next.authoring,activeArtSetId:req.params.artSetId};next.revision++;next.updatedAt=new Date().toISOString();return repo.save(next,`artset-activate:${req.params.artSetId}`)});
app.delete("/api/worlds/:id/artsets/:artSetId",async(req:any)=>{const world=await must(req.params.id);if(!world.authoring?.artSets?.[req.params.artSetId])throw Error("custom Art Set not found");const next=structuredClone(world),authoring=next.authoring!;delete authoring.artSets![req.params.artSetId];if(authoring.activeArtSetId===req.params.artSetId)authoring.activeArtSetId=pack.manifest.defaultArtSet;next.revision++;next.updatedAt=new Date().toISOString();return repo.save(next,`artset-delete:${req.params.artSetId}`)});

app.get("/api/worlds/:id/report",async(req:any)=>generationReport(await must(req.params.id)));
app.get("/api/worlds/:id/entities/:entityId/explain/:key",async(req:any)=>explainValue(await must(req.params.id),req.params.entityId,req.params.key));
app.get("/api/worlds/:id/scope/:entityId",async(req:any)=>scopeSummary(await must(req.params.id),req.params.entityId));

app.post("/api/worlds/:id/regenerate/preview",async(req:any)=>{const w=await must(req.params.id),fresh=compileWorld({realmId:w.realmId,descriptor:w.descriptor,pack,seed:`${w.seed}:regen:${w.revision+1}`,worldId:w.id});preserveCustomByPath(w,fresh);return compareWorlds(w,fresh)});
app.post("/api/worlds/:id/regenerate",async(req:any)=>{const w=await must(req.params.id);await repo.snapshot(w,req.body?.snapshotName??`Before regeneration r${w.revision}`);const fresh=compileWorld({realmId:w.realmId,descriptor:w.descriptor,pack,seed:`${w.seed}:regen:${w.revision+1}`,worldId:w.id});preserveCustomByPath(w,fresh);fresh.createdAt=w.createdAt;fresh.assets=w.assets;fresh.revision=w.revision+1;return repo.save(fresh,"regenerate")});

app.get("/api/worlds/:id/revisions",async(req:any)=>repo.revisions(req.params.id));
app.get("/api/worlds/:id/snapshots",async(req:any)=>repo.snapshots(req.params.id));
app.post("/api/worlds/:id/snapshots",async(req:any)=>{const w=await must(req.params.id);return repo.snapshot(w,req.body?.name??`Snapshot r${w.revision}`)});
app.post("/api/snapshots/:id/restore",async(req:any)=>repo.restore(req.params.id));
app.post("/api/worlds/:id/fork",async(req:any)=>{const w=await must(req.params.id);return repo.fork(w,req.body?.name??`${w.name} Fork`)});

app.get("/api/worlds/:id/export",async(req:any,reply)=>{const w=await must(req.params.id),bytes=exportMhWorldZip(w,await repo.assets(w.id));reply.header("content-type","application/vnd.masterhost.world+zip");reply.header("content-disposition",`attachment; filename="${w.name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.mhworld"`);return reply.send(Buffer.from(bytes))});

app.masterhostPack=pack;
await withMigrationLock(databaseUrl,async()=>{await repo.migrate();await packProjects.migrate();await registerRuntime(app,{db:databaseUrl,realmId})});

app.setErrorHandler((err,req,reply)=>{req.log.error(err);const error=err instanceof Error?err:new Error(String(err));reply.code((error as Error&{statusCode?:number}).statusCode??400).send({error:"masterhost_error",message:error.message})});
await app.listen({host:"0.0.0.0",port:Number(process.env.PORT??8080)});
