import type{FastifyInstance}from"fastify";import websocket from"@fastify/websocket";import{RuntimeRepository,GameRepository,ActorStateRepository,EncounterRepository,RuntimeMutationRepository,RuntimeReplayRepository,CheckRecoveryRepository,PostgresRealtimeBus,AdvancedEcosystemRepository}from"@masterhost/persistence";import type{WorldRepository,RealtimeBusMessage}from"@masterhost/persistence";import{newCheckRequest,resolveCheck,initializeResources,effectiveModifier,executeAction,startEncounter,advanceEncounter,endEncounter,reconcileWorldLink,grantItem,transferItem,changeProgression,moveActor,visibleExplorationBoard,buildCampaignRecap,redactSpectatorTimeline,createTableState,visibleTableState,isTablePhase,buildRehearsalReport,assertActorControl}from"@masterhost/game-runtime";import type{CheckDefinition,CheckRequest,CheckResolution,ResourceDefinition,EffectDefinition,ActorRuntimeState,ItemDefinition,ProgressionDefinition,FogRegion,TablePhase}from"@masterhost/game-runtime";import{buildCharacterState,evaluateCharacterPortability}from"@masterhost/worldpack-sdk";import type{LoadedWorldPack}from"@masterhost/worldpack-sdk";
import{createHash,randomUUID}from"node:crypto";
import { changeEncounterParticipants } from "@masterhost/game-runtime";
import { AsyncLocalStorage } from "node:async_hooks";
import type { MaterializedWorld } from "@masterhost/domain";
declare module "fastify" { interface FastifyInstance { masterhostPack?: LoadedWorldPack; masterhostWorldRepository?: WorldRepository } }
export async function resolveRuntimeWorldPack(world:MaterializedWorld, fallback:LoadedWorldPack, resolver?:(world:MaterializedWorld)=>Promise<LoadedWorldPack>){
 const candidate=world.packId===fallback.manifest.id&&world.packVersion===fallback.manifest.version?fallback:resolver?await resolver(world):null;
 if(!candidate||candidate.manifest.id!==world.packId||candidate.manifest.version!==world.packVersion)throw Object.assign(Error("Game rules and content are unavailable"),{statusCode:409});
 return candidate;
}
export async function registerRuntime(app:FastifyInstance,x:{db:string;realmId:string;packForWorld?:(world:MaterializedWorld)=>Promise<LoadedWorldPack>}){
 const fallbackPack=app.masterhostPack,worldRepository=app.masterhostWorldRepository;if(!fallbackPack||!worldRepository)throw Error("MasterHost dependencies unavailable");
 const packContext=new AsyncLocalStorage<LoadedWorldPack>(),pack=new Proxy(fallbackPack,{get(target,key,receiver){return Reflect.get(packContext.getStore()??target,key,receiver)}});
 const repo=new RuntimeRepository(x.db),game=new GameRepository(x.db),actors=new ActorStateRepository(x.db),encounters=new EncounterRepository(x.db),mutations=new RuntimeMutationRepository(x.db),replay=new RuntimeReplayRepository(x.db),checkRecovery=new CheckRecoveryRepository(x.db),advanced=new AdvancedEcosystemRepository(x.db),bus=new PostgresRealtimeBus(x.db);await game.migrate();await actors.migrate();await encounters.migrate();await mutations.migrate();await replay.migrate();await checkRecovery.migrate();await advanced.migrate();await bus.migrate();await bus.cleanup();await repo.migrate();await repo.ensureRealm(x.realmId);await app.register(websocket);
 const sockets=new Map<string,Set<{socket:any;participantId?:string;gm:boolean}>>();
 const snapshot=async(id:string)=>{const[session,participants,actorStates,sessionEncounters,lastSequence]=await Promise.all([repo.session(id),repo.participants(id),actors.all(id),encounters.forSession(id),game.latestSequence(id)]);return{session,participants,actors:actorStates,encounters:sessionEncounters,lastSequence}};
 const deliver=async(message:RealtimeBusMessage)=>{const wire=JSON.stringify(message);for(const client of sockets.get(message.sessionId)??[])if(client.socket.readyState===1&&(!message.participantId||client.gm||client.participantId===message.participantId))client.socket.send(wire)};await bus.subscribe(deliver);
 const broadcast=async(id:string,type:string,payload:any,participantId?:string)=>bus.publish({type,sessionId:id,payload,participantId,sequence:await game.latestSequence(id)});
 const token=(req:any)=>String(req.headers.authorization??"").replace(/^Bearer\s+/i,"");
 const realmFor=(req:any)=>app.masterhostContext?.()?.realm.id??x.realmId;
 const requireCampaignGm=async(req:any,id:string)=>{if(!await repo.verifyCampaignGm(id,token(req)))throw Object.assign(Error("GM authorization required"),{statusCode:403})};
 const requireSessionGm=async(req:any,id:string)=>{if(!await repo.verifySessionGm(id,token(req)))throw Object.assign(Error("GM authorization required"),{statusCode:403})};
 const requireParticipant=async(req:any,id:string)=>{if(!await repo.verifyParticipant(id,token(req)))throw Object.assign(Error("participant authorization required"),{statusCode:403})};
 const requireSessionMember=async(req:any,id:string)=>{if(!await repo.verifySessionGm(id,token(req))&&!await repo.sessionMember(id,token(req)))throw Object.assign(Error("session authorization required"),{statusCode:403})};
 const viewerRole=async(req:any,id:string)=>await repo.verifySessionGm(id,token(req))?"gm":await repo.sessionMember(id,token(req))?"player":await advanced.verifySpectator(id,token(req))?"spectator":null;
 const requireViewer=async(req:any,id:string)=>{const role=await viewerRole(req,id);if(!role)throw Object.assign(Error("session viewer authorization required"),{statusCode:403});return role};
 const idempotency=async(req:any,sessionId:string)=>{const raw=req.headers["idempotency-key"];if(raw===undefined)return undefined;if(typeof raw!=="string"||!(/^[A-Za-z0-9._:-]{1,128}$/).test(raw))throw Object.assign(Error("invalid Idempotency-Key"),{statusCode:400});const fingerprint=createHash("sha256").update(`${req.method}\0${req.url}\0${JSON.stringify(req.body??{})}`).digest("hex");const prior=await mutations.receipt(sessionId,raw,fingerprint);return{key:raw,fingerprint,prior}};
 const visibleRequest=(request:CheckRequest)=>request.visibility==="full"?request:(({difficulty,...rest})=>rest)(request);
 const visibleResolution=(request:CheckRequest,resolution:CheckResolution)=>request.visibility==="full"?resolution:request.visibility==="result-only"?{requestId:resolution.requestId,total:resolution.total,outcome:resolution.outcome,resolvedAt:resolution.resolvedAt}:request.visibility==="roll-only"?{requestId:resolution.requestId,roll:resolution.roll,modifier:resolution.modifier,total:resolution.total,resolvedAt:resolution.resolvedAt}:{requestId:resolution.requestId,resolvedAt:resolution.resolvedAt};
	 const sessionWorld=async(session:{campaignId:string;realmId:string})=>{const campaign=await repo.campaign(session.campaignId),world=campaign?await worldRepository.get(campaign.worldId):null;if(!campaign||!world||world.realmId!==session.realmId)throw Object.assign(Error("session game is unavailable"),{statusCode:409});await resolveRuntimeWorldPack(world,fallbackPack,x.packForWorld);return world};
	 const initializeParticipant=async(sessionId:string,participantId:string,characterId:string,idem?:{key:string;fingerprint:string})=>{const existing=await actors.get(sessionId,participantId);if(existing)return existing;const c=await repo.character(characterId),defs=Object.fromEntries(Object.entries(pack.content.resources??{}).map(([id,value])=>[id,{id,...value}])) as Record<string,ResourceDefinition>,state={actorId:participantId,resources:initializeResources(defs,c?.resources??c?.values??{}),effects:[],inventory:(c?.inventory??[]).map((entry:any)=>({itemId:entry.id,quantity:entry.quantity??1})),progression:Object.fromEntries(Object.entries(c?.progression??{}).filter((entry):entry is[string,number]=>typeof entry[1]==="number"))};await mutations.commit(sessionId,[{type:"ActorInitialized",payload:{...state}}],[state],undefined,{},idem?{...idem,result:state}:undefined);await broadcast(sessionId,"actor.state",state);return state};
 const worldForSession=async(id:string)=>{const session=await repo.session(id),campaign=session?await repo.campaign(session.campaignId):null;return campaign?await worldRepository.get(campaign.worldId):null};
 const requestWorld=async(req:any):Promise<MaterializedWorld|null>=>{
  const url=String(req.url??"");let world:MaterializedWorld|null=null;
  const sessionId=url.match(/^\/api\/sessions\/([^/?]+)/)?.[1]??req.query?.sessionId??req.body?.sessionId;
  if(sessionId)world=await worldForSession(String(sessionId));
  else if(/^\/api\/campaigns$/.test(url.split("?")[0]??"")&&req.body?.worldId)world=await worldRepository.get(String(req.body.worldId));
  else if(url.match(/^\/api\/campaigns\/([^/?]+)\/sessions/)){const campaign=await repo.campaign(String(req.params?.id));world=campaign?await worldRepository.get(campaign.worldId):null}
  else if(url.match(/^\/api\/participants\/([^/?]+)/)){const participant=await repo.participant(String(req.params?.id));world=participant?await worldForSession(participant.sessionId):null}
  else if(url.match(/^\/api\/checks\/([^/?]+)\/roll/)){const found=await game.check(String(req.params?.id));world=found?await worldForSession(found.request.sessionId):null}
  else if(url.match(/^\/api\/encounters\/([^/?]+)/)){const found=await encounters.get(String(req.params?.id));world=found?await worldForSession(found.sessionId):null}
  return world;
 };
 app.addHook("preHandler",(req:any,_reply,done)=>{requestWorld(req).then(world=>world?resolveRuntimeWorldPack(world,fallbackPack,x.packForWorld):fallbackPack).then(selected=>packContext.run(selected,done)).catch(done)});
 app.post("/api/campaigns",async(req:any)=>{const realmId=realmFor(req),world=await worldRepository.get(req.body?.worldId);if(!world||world.realmId!==realmId)throw Object.assign(Error("game not found"),{statusCode:404});await resolveRuntimeWorldPack(world,fallbackPack,x.packForWorld);const characterPortability=req.body?.characterPortability??"exact";if(!["exact","pack"].includes(characterPortability))throw Object.assign(Error("invalid character portability policy"),{statusCode:400});return repo.createCampaign({realmId,worldId:world.id,name:req.body.name??"New Campaign",characterPortability})});
 app.get("/api/campaigns/:id",async(req:any)=>repo.campaign(req.params.id));
 app.post("/api/campaigns/:id/sessions",async(req:any)=>{const realmId=realmFor(req),c=await repo.campaign(req.params.id);if(!c||c.realmId!==realmId)throw Object.assign(Error("campaign not found"),{statusCode:404});await requireCampaignGm(req,c.id);return repo.startLobby({realmId,campaignId:c.id,gmId:req.body?.gmId})});
 app.post("/api/join/resolve",async(req:any)=>{const s=await repo.resolvePin(realmFor(req),String(req.body?.pin??""));if(!s)throw Object.assign(Error("PIN not found or expired"),{statusCode:404});return{session:s,campaign:await repo.campaign(s.campaignId)}});

 app.get("/api/character-creation",async()=>({pack:{id:pack.manifest.id,version:pack.manifest.version},schema:pack.content.characterCreation??{steps:[]}}));
 app.get("/api/characters",async(req:any)=>{const ownerKey=String(req.headers["x-owner-key"]??"");if(ownerKey.length<20)throw Object.assign(Error("owner key required"),{statusCode:403});const schema=pack.content.characterCreation??{schemaVersion:"1",steps:[]};return(await repo.characters(realmFor(req),ownerKey)).map(character=>({...character,compatibility:evaluateCharacterPortability(pack.manifest.id,pack.manifest.version,schema,character)}))});
 app.post("/api/characters",async(req:any)=>{if(!pack)throw Error("pack unavailable");const ownerKey=String(req.body?.ownerKey??"");if(ownerKey.length<20)throw Object.assign(Error("owner key required"),{statusCode:400});const schema=pack.content.characterCreation??{schemaVersion:"1",steps:[]},state=buildCharacterState(schema,req.body?.values),name=String(state.values.name??state.values.handle??req.body?.displayName??"Unnamed");return repo.createCharacter({realmId:realmFor(req),packId:pack.manifest.id,packVersion:pack.manifest.version,schemaVersion:schema.schemaVersion??"1",ownerKey,displayName:name,...state})});
	 app.post("/api/participants/:id/character",async(req:any)=>{await requireParticipant(req,req.params.id);const realmId=realmFor(req),ownerKey=String(req.body.ownerKey??""),participant=await repo.participant(req.params.id),source=await repo.character(req.body.characterId);if(!participant||!source)throw Object.assign(Error("participant or character not found"),{statusCode:404});const session=await repo.session(participant.sessionId),campaign=session?await repo.campaign(session.campaignId):null;if(!session||!campaign||session.realmId!==realmId||source.realmId!==realmId||!await repo.characterOwnedBy(source.id,ownerKey))throw Object.assign(Error("character is not owned by this guest"),{statusCode:403});const schema=pack.content.characterCreation??{schemaVersion:"1",steps:[]},compatibility=evaluateCharacterPortability(pack.manifest.id,pack.manifest.version,schema,source);if(!compatibility.compatible||compatibility.mode!=="exact"&&campaign.characterPortability!=="pack")throw Object.assign(Error(`character rejected: ${compatibility.reason}`),{statusCode:409});let character=source;if(compatibility.mode!=="exact"){const state=buildCharacterState(schema,compatibility.values);character=await repo.createCharacter({realmId,packId:pack.manifest.id,packVersion:pack.manifest.version,schemaVersion:schema.schemaVersion??"1",ownerKey,displayName:String(state.values.name??state.values.handle??source.displayName),...state})}await repo.selectCharacter(req.params.id,character.id);if(session.state==="live")await initializeParticipant(session.id,participant.id,character.id);const updated=await repo.participant(req.params.id);if(updated)await broadcast(participant.sessionId,"participant.character",updated);return{ok:true,character,compatibility}});
 app.get("/api/participants/:id/character",async(req:any)=>{await requireParticipant(req,req.params.id);const participant=await repo.participant(req.params.id);if(!participant?.characterId)throw Object.assign(Error("participant has no character"),{statusCode:404});return repo.character(participant.characterId)});

 app.post("/api/sessions/:id/join",async(req:any)=>{const p=await repo.joinGuest({sessionId:req.params.id,pin:String(req.body?.pin??""),displayName:String(req.body?.displayName??"Guest").trim().slice(0,80)||"Guest"});const{accessToken,...publicParticipant}=p;await broadcast(req.params.id,"participant.joined",publicParticipant);return p});
 app.get("/api/sessions/:id",async(req:any)=>{await requireSessionMember(req,req.params.id);return snapshot(req.params.id)});
 app.get("/api/sessions/:id/context",async(req:any)=>{await requireSessionMember(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const campaign=await repo.campaign(session.campaignId),world=await sessionWorld(session),artSet=pack.artSets[pack.manifest.defaultArtSet],mappings=[artSet?.defaults,...Object.values(artSet?.types??{}),...Object.values(artSet?.families??{})],map=mappings.find(value=>value?.map)?.map;return{session,campaign:{id:campaign!.id,name:campaign!.name},world:{id:world.id,name:world.name,revision:world.revision},pack:{id:pack.manifest.id,name:pack.manifest.name,version:pack.manifest.version},media:{map}}});
 app.post("/api/sessions/:id/state",async(req:any)=>{await requireSessionGm(req,req.params.id);const s=await repo.transition(req.params.id,req.body.state);await broadcast(req.params.id,"session.state",s);return s});
 app.post("/api/participants/:id/ready",async(req:any)=>{await requireParticipant(req,req.params.id);const p=await repo.setReady(req.params.id,Boolean(req.body.ready));if(p)await broadcast(p.sessionId,"participant.ready",p);return p});
 app.post("/api/participants/:id/leave",async(req:any)=>{await requireParticipant(req,req.params.id);const sid=await repo.leave(req.params.id);if(sid){await broadcast(sid,"participant.left",{id:req.params.id});for(const client of sockets.get(sid)??[])if(client.participantId===req.params.id)client.socket.close(1008,"participant left")}return{ok:true}});
 app.post("/api/sessions/:id/participants/:participantId/remove",async(req:any)=>{await requireSessionGm(req,req.params.id);const participant=await repo.participant(req.params.participantId);if(!participant||participant.sessionId!==req.params.id)throw Object.assign(Error("participant not found in session"),{statusCode:404});const sid=await repo.leave(participant.id);if(sid){await broadcast(sid,"participant.left",{id:participant.id});for(const client of sockets.get(sid)??[])if(client.participantId===participant.id)client.socket.close(1008,"participant removed by GM")}return{ok:true}});


 app.get("/api/game/definitions",async()=>{const c=pack.content;return{checks:c.checks??{},resources:c.resources??{},effects:c.effects??{},actions:c.actions??{},items:c.items??{},progression:c.progression??{},locations:c.locations??{worldEntityKinds:[]},actorTemplates:c.actorTemplates??{},encounter:c.encounter??{orderingPolicy:"none"}}});
 app.get("/api/sessions/:id/actors",async(req:any)=>{await requireSessionMember(req,req.params.id);return actors.all(req.params.id)});
 app.get("/api/sessions/:id/world-actors",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const world=await sessionWorld(session),kinds=new Set(Object.values(pack.content.actorTemplates??{}).flatMap(template=>template.worldEntityKinds??[]));return world.entities.filter(entity=>kinds.has(entity.kind)).map(entity=>({id:entity.id,kind:entity.kind,name:String(entity.values.name?.value??entity.kind),materializationPath:entity.materializationPath}))});
 app.post("/api/sessions/:id/actors",async(req:any)=>{
  await requireSessionGm(req,req.params.id);
  const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const templateId=String(req.body?.templateId??""),template=pack.content.actorTemplates?.[templateId];if(!template)throw Object.assign(Error("unknown actor template"),{statusCode:400});
  const worldEntityId=req.body?.worldEntityId;let worldLink:{}|Pick<ActorRuntimeState,"worldEntityId"|"worldEntityPath"|"worldEntityLabel"|"worldEntityRevision"|"worldEntityStatus">={};
  if(worldEntityId!==undefined){
   if(typeof worldEntityId!=="string")throw Object.assign(Error("invalid World entity ID"),{statusCode:400});
   const world=await sessionWorld(session),entity=world.entities.find(item=>item.id===worldEntityId);
   if(!entity||!template.worldEntityKinds?.includes(entity.kind))throw Object.assign(Error("World entity is not compatible with actor template"),{statusCode:400});
   worldLink={worldEntityId,worldEntityPath:entity.materializationPath,worldEntityLabel:String(entity.values.name?.value??entity.kind),worldEntityRevision:world.revision,worldEntityStatus:"current"};
  }
  const definitions=Object.fromEntries(Object.entries(pack.content.resources??{}).map(([id,value])=>[id,{id,...value}])) as Record<string,ResourceDefinition>;
  const state={actorId:randomUUID(),kind:"npc" as const,label:template.label,templateId,...worldLink,attributes:template.attributes??{},resources:initializeResources(definitions,template.resources??{}),effects:[],inventory:template.inventory??[],progression:template.progression??{}};
  let receipt;
  try{receipt=await mutations.commit(session.id,[{type:"ActorInitialized",payload:{...state}}],[state],undefined,{},idem?{key:idem.key,fingerprint:idem.fingerprint,result:state}:undefined)}
  catch(error){if(error&&typeof error==="object"&&"constraint_name" in error&&error.constraint_name==="actor_one_world_entity_per_session")throw Object.assign(Error("World entity already has a session actor"),{statusCode:409});throw error}
  if(receipt.replayed)return receipt.result;
  await broadcast(session.id,"actor.state",state);return state;
 });
 app.post("/api/sessions/:id/actors/reconcile-world",async(req:any)=>{
  await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const world=await sessionWorld(session),versioned=await actors.allVersioned(session.id),states:ActorRuntimeState[]=[],events:{type:string;payload:Record<string,unknown>}[]=[],result:{actorId:string;status:string;worldRevision:number;changed:boolean}[]=[];
  for(const row of versioned){const actor=row.state;if(actor.kind!=="npc"||!actor.worldEntityId)continue;const template=actor.templateId?pack.content.actorTemplates?.[actor.templateId]:undefined;if(!template)throw Object.assign(Error(`NPC template unavailable for ${actor.actorId}`),{statusCode:409});const next=reconcileWorldLink(actor,template,world),changed=JSON.stringify(next)!==JSON.stringify(actor);result.push({actorId:actor.actorId,status:next.worldEntityStatus!,worldRevision:world.revision,changed});if(changed){states.push(next);events.push({type:"ActorWorldLinkReconciled",payload:{actor:next}})}}
  const actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),receipt=await mutations.commit(session.id,events,states,undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);if(receipt.replayed)return receipt.result;for(const state of states)await broadcast(session.id,"actor.state",state);return result;
 });
 app.post("/api/sessions/:id/actors/:actorId/edit",async(req:any)=>{
  await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const versioned=await actors.allVersioned(session.id),row=versioned.find(value=>value.state.actorId===req.params.actorId),current=row?.state;if(!current)throw Object.assign(Error("actor not found"),{statusCode:404});if(current.kind!=="npc"||!current.templateId)throw Object.assign(Error("only NPC actors can be edited"),{statusCode:400});
  const template=pack.content.actorTemplates?.[current.templateId];if(!template)throw Object.assign(Error("NPC template is unavailable"),{statusCode:409});
  const label=req.body?.label===undefined?current.label:String(req.body.label).trim();if(!label||label.length>80)throw Object.assign(Error("NPC label must contain 1 to 80 characters"),{statusCode:400});
  const patch=req.body?.attributes??{};if(!patch||typeof patch!=="object"||Array.isArray(patch))throw Object.assign(Error("NPC attributes must be an object"),{statusCode:400});
  const allowed=new Set(Object.keys(template.attributes??{})),attributes={...(current.attributes??{})};for(const[key,value]of Object.entries(patch)){if(!allowed.has(key)||typeof value!=="number"||!Number.isFinite(value)||Math.abs(value)>1000)throw Object.assign(Error(`invalid NPC attribute ${key}`),{statusCode:400});attributes[key]=value}
  const next={...current,label,attributes},actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),receipt=await mutations.commit(session.id,[{type:"ActorUpdated",payload:{actor:next}}],[next],undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:next}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"actor.state",next);return next;
 });
 app.post("/api/sessions/:id/actors/:actorId/remove",async(req:any)=>{
  await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const versioned=await actors.allVersioned(session.id),row=versioned.find(value=>value.state.actorId===req.params.actorId);if(!row)throw Object.assign(Error("actor not found"),{statusCode:404});if(row.state.kind!=="npc")throw Object.assign(Error("only NPC actors can be removed"),{statusCode:400});
  if((await encounters.forSession(session.id)).some(encounter=>encounter.state==="live"&&encounter.participants.includes(row.state.actorId)))throw Object.assign(Error("remove NPC from the active Encounter first"),{statusCode:409});
  const result={removedActorId:row.state.actorId},actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),receipt=await mutations.commit(session.id,[{type:"ActorRemoved",payload:{actorId:row.state.actorId}}],[],undefined,{actorVersions,removeActorIds:[row.state.actorId]},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"actor.removed",result);return result;
 });
	 app.post("/api/sessions/:id/participants/:participantId/initialize",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const p=await repo.participant(req.params.participantId);if(!p?.characterId||p.sessionId!==req.params.id)throw Object.assign(Error("participant has no character in session"),{statusCode:409});return initializeParticipant(req.params.id,p.id,p.characterId,idem)});
 app.post("/api/sessions/:id/actions",async(req:any)=>{
  const actionGm=await repo.verifySessionGm(req.params.id,token(req)),actionMember=actionGm?null:await repo.sessionMember(req.params.id,token(req));if(!actionGm&&!actionMember)throw Object.assign(Error("session authorization required"),{statusCode:403});
  const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const defs=pack.content,action=defs.actions?.[req.body?.actionId];if(!action)throw Object.assign(Error("unknown action"),{statusCode:400});
  const actorId=String(req.body?.actorId??""),targetActorIds=Array.isArray(req.body?.targetActorIds)?req.body.targetActorIds:req.body?.targetActorId?[req.body.targetActorId]:[];assertActorControl({gm:actionGm,participantId:actionMember?.id,actorId});
  const versioned=await actors.allVersioned(session.id),all=versioned.map(row=>row.state),actorVersions=Object.fromEntries(versioned.map(row=>[row.state.actorId,row.version])),actorMap=Object.fromEntries(all.map(state=>[state.actorId,state]));
  const characterValues:Record<string,Record<string,unknown>>={};for(const state of all){if(state.kind==="npc"){characterValues[state.actorId]=state.attributes??{};continue}const participant=await repo.participant(state.actorId);if(participant?.sessionId===session.id&&participant.characterId){const character=await repo.character(participant.characterId);if(character)characterValues[state.actorId]=character.values}}
  const checks=Object.fromEntries(Object.entries(defs.checks??{}).map(([id,value])=>[id,{id,...value as object}])) as Record<string,CheckDefinition>;
  const resources=Object.fromEntries(Object.entries(defs.resources??{}).map(([id,value])=>[id,{id,...value as object}])) as Record<string,ResourceDefinition>;
  const effects=Object.fromEntries(Object.entries(defs.effects??{}).map(([id,value])=>[id,{id,...value as object}])) as Record<string,EffectDefinition>;
  const result=executeAction({action:{id:req.body.actionId,...action},request:{sessionId:session.id,actionId:req.body.actionId,actorId,targetActorIds,inputs:req.body?.inputs},actors:actorMap,checks,resources,effects,characterValues});
  const receipt=await mutations.commit(session.id,result.events,result.states,undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);
  if(receipt.replayed)return receipt.result;
  for(const state of result.states)await broadcast(session.id,"actor.state",state);
  await broadcast(session.id,"action.resolved",result.events.at(-1)?.payload);return result;
 });

 app.get("/api/sessions/:id/locations",async(req:any)=>{await requireSessionMember(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const world=await sessionWorld(session),kinds=new Set(pack.content.locations?.worldEntityKinds??[]);return world.entities.filter(entity=>kinds.has(entity.kind)).map(entity=>({id:entity.id,kind:entity.kind,name:String(entity.values.name?.value??entity.kind),materializationPath:entity.materializationPath}))});
 app.post("/api/sessions/:id/items/grant",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const definition=pack.content.items?.[String(req.body?.itemId??"")];if(!definition)throw Object.assign(Error("unknown item"),{statusCode:400});const versioned=await actors.allVersioned(session.id),row=versioned.find(value=>value.state.actorId===req.body?.actorId);if(!row)throw Object.assign(Error("actor not found"),{statusCode:404});const result=grantItem(session.id,row.state,{id:String(req.body.itemId),...definition}as ItemDefinition,Number(req.body?.quantity)),actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),response={actor:result.state,event:result.event};const receipt=await mutations.commit(session.id,[result.event],[result.state],undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"actor.state",result.state);return response});
 app.post("/api/sessions/:id/items/transfer",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const definition=pack.content.items?.[String(req.body?.itemId??"")];if(!definition)throw Object.assign(Error("unknown item"),{statusCode:400});const versioned=await actors.allVersioned(session.id),from=versioned.find(value=>value.state.actorId===req.body?.fromActorId),to=versioned.find(value=>value.state.actorId===req.body?.toActorId);if(!from||!to)throw Object.assign(Error("transfer actor not found"),{statusCode:404});const result=transferItem(session.id,from.state,to.state,{id:String(req.body.itemId),...definition}as ItemDefinition,Number(req.body?.quantity)),actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),response={actors:result.states,event:result.event};const receipt=await mutations.commit(session.id,[result.event],result.states,undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;for(const state of result.states)await broadcast(session.id,"actor.state",state);return response});
 app.post("/api/sessions/:id/progression",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const definition=pack.content.progression?.[String(req.body?.progressionId??"")];if(!definition)throw Object.assign(Error("unknown progression"),{statusCode:400});const versioned=await actors.allVersioned(session.id),row=versioned.find(value=>value.state.actorId===req.body?.actorId);if(!row)throw Object.assign(Error("actor not found"),{statusCode:404});const result=changeProgression(session.id,row.state,{id:String(req.body.progressionId),...definition}as ProgressionDefinition,Number(req.body?.amount)),actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),response={actor:result.state,event:result.event};const receipt=await mutations.commit(session.id,[result.event],[result.state],undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"actor.state",result.state);return response});
 app.post("/api/sessions/:id/location",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const world=await sessionWorld(session),location=world.entities.find(entity=>entity.id===req.body?.locationId),kinds=new Set(pack.content.locations?.worldEntityKinds??[]);if(!location||!kinds.has(location.kind))throw Object.assign(Error("location is not compatible with this Pack"),{statusCode:400});const versioned=await actors.allVersioned(session.id),row=versioned.find(value=>value.state.actorId===req.body?.actorId);if(!row)throw Object.assign(Error("actor not found"),{statusCode:404});const result=moveActor(session.id,row.state,location.id),actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),response={actor:result.state,location:{id:location.id,kind:location.kind,name:String(location.values.name?.value??location.kind)},event:result.event};const receipt=await mutations.commit(session.id,[result.event],[result.state],undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"actor.state",result.state);return response});
 app.post("/api/sessions/:id/travel",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const world=await sessionWorld(session),location=world.entities.find(entity=>entity.id===req.body?.locationId),kinds=new Set(pack.content.locations?.worldEntityKinds??[]),actorIds=req.body?.actorIds;if(!location||!kinds.has(location.kind)||!Array.isArray(actorIds)||!actorIds.length||new Set(actorIds).size!==actorIds.length)throw Object.assign(Error("travel requires a compatible location and unique actors"),{statusCode:400});const versioned=await actors.allVersioned(session.id),selected=actorIds.map((id:string)=>versioned.find(value=>value.state.actorId===id));if(selected.some(value=>!value))throw Object.assign(Error("travel actor not found"),{statusCode:404});const moved=selected.map(value=>moveActor(session.id,value!.state,location.id)),states=moved.map(value=>value.state),events=moved.map(value=>value.event),actorVersions=Object.fromEntries(versioned.map(value=>[value.state.actorId,value.version])),response={actors:states,location:{id:location.id,kind:location.kind,name:String(location.values.name?.value??location.kind)}};const receipt=await mutations.commit(session.id,events,states,undefined,{actorVersions},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;for(const state of states)await broadcast(session.id,"actor.state",state);return response});
 app.post("/api/sessions/:id/events/narrative",async(req:any)=>{await requireSessionGm(req,req.params.id);const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const text=String(req.body?.text??"").trim();if(!text||text.length>1000)throw Object.assign(Error("session event must contain 1 to 1000 characters"),{statusCode:400});const event={type:"NarrativeEventRecorded",payload:{text}},response={event};const receipt=await mutations.commit(session.id,[event],[],undefined,{},idem?{key:idem.key,fingerprint:idem.fingerprint,result:response}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"session.event",event.payload);return response});

 app.get("/api/game/checks",async()=>({checks:pack.content.checks??{}}));
 app.post("/api/sessions/:id/checks",async(req:any)=>{
  await requireSessionGm(req,req.params.id);
  const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const checks=pack.content.checks??{},def=checks[req.body.checkId];if(!def)throw Object.assign(Error("unknown check"),{statusCode:400});const difficulty=Number(req.body?.difficulty),visibility=String(req.body?.visibility??"full");if(!Number.isSafeInteger(difficulty)||![-1000000,1000000].every((bound,index)=>index?difficulty<=bound:difficulty>=bound)||!["full","result-only","roll-only","hidden"].includes(visibility))throw Object.assign(Error("invalid check difficulty or visibility"),{statusCode:400});
  const participant=await repo.participant(req.body.participantId);if(!participant||participant.sessionId!==session.id)throw Object.assign(Error("participant not in session"),{statusCode:400});
  const c=newCheckRequest({sessionId:session.id,participantId:participant.id,checkId:req.body.checkId,difficulty,visibility:visibility as CheckRequest["visibility"]});
  const created=await game.createCheck(c,idem?{key:idem.key,fingerprint:idem.fingerprint,result:c}:undefined);
  if(!created.replayed)await broadcast(session.id,"check.requested",visibleRequest(created.request),participant.id);
  return created.request;
 });
 app.post("/api/checks/:id/roll",async(req:any)=>{const found=await game.check(req.params.id);if(!found)throw Object.assign(Error("check not found"),{statusCode:404});await requireParticipant(req,found.request.participantId);if(found.resolution)return visibleResolution(found.request,found.resolution);const participant=await repo.participant(found.request.participantId);if(!participant?.characterId)throw Object.assign(Error("participant has no character"),{statusCode:409});const character=await repo.character(participant.characterId);if(!character)throw Error("character not found");const def=pack.content.checks?.[found.request.checkId];if(!def)throw Error("check definition unavailable");const state=await actors.get(found.request.sessionId,participant.id),effects=state?.effects??[],effectDefs=Object.fromEntries(Object.entries(pack.content.effects??{}).map(([id,value])=>[id,{id,...value}])) as Record<string,EffectDefinition>,field=def.modifierField,base=field?Number(character.values[field]??0):0,modified={...character.values,...(field?{[field]:effectiveModifier(base,field,effects,effectDefs)}:{})};const proposed=resolveCheck(found.request,{id:found.request.checkId,...def},modified);const{resolution,created}=await game.resolveCheck(found.request.id,proposed);const visible={request:visibleRequest(found.request),resolution:visibleResolution(found.request,resolution)};if(created)await broadcast(found.request.sessionId,"check.resolved",visible,found.request.participantId);return visible.resolution});
 app.get("/api/sessions/:id/events",async(req:any)=>{await requireSessionGm(req,req.params.id);return game.events(req.params.id)});
 app.get("/api/sessions/:id/playtest-report",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const events=await game.events(session.id),started=session.startedAt?Date.parse(session.startedAt):NaN,ended=session.finishedAt?Date.parse(session.finishedAt):Date.now(),durationMinutes=Number.isFinite(started)?Math.max(0,Math.floor((ended-started)/60000)):0,count=(type:string)=>events.filter(event=>event.type===type).length,evidence={checks:count("CheckResolved"),actions:count("ActionResolved"),encounters:count("EncounterStarted"),travelMoves:count("ActorMoved"),reconnects:count("SessionReconnected"),narrativeEvents:count("NarrativeEventRecorded")};return{sessionId:session.id,state:session.state,startedAt:session.startedAt,finishedAt:session.finishedAt,durationMinutes,eventCount:events.length,evidence,gatePassed:durationMinutes>=120&&evidence.checks>0&&evidence.actions>0&&evidence.encounters>0&&evidence.travelMoves>0&&evidence.reconnects>0}});
 app.post("/api/sessions/:id/table",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const world=await sessionWorld(session),locationKinds=new Set(pack.content.locations?.worldEntityKinds??[]),candidates=world.entities.filter(entity=>locationKinds.has(entity.kind)||/(scene|encounter|event)/i.test(entity.kind)),selected=(candidates.length?candidates:world.entities.slice(0,12)).slice(0,40),scenes:Array<{id:string;title:string;summary?:string;sourceEntityId?:string}>=selected.map(entity=>({id:entity.id,title:String(entity.values.name?.value??entity.kind),summary:typeof entity.values.description?.value==="string"?entity.values.description.value:undefined,sourceEntityId:entity.id}));if(!scenes.length)scenes.push({id:`${session.id}:opening`,title:"Opening scene"});const result=await advanced.createTable(createTableState({sessionId:session.id,scenes}));if(result.created)await broadcast(session.id,"table.state",visibleTableState(result.table,false));return result.table});
 app.get("/api/sessions/:id/table",async(req:any)=>{const role=await requireViewer(req,req.params.id),table=await advanced.table(req.params.id);if(!table)throw Object.assign(Error("table state not found"),{statusCode:404});return visibleTableState(table,role==="gm")});
 app.patch("/api/sessions/:id/table",async(req:any)=>{await requireSessionGm(req,req.params.id);const tableSession=await repo.session(req.params.id);if(!tableSession||!["lobby","live"].includes(tableSession.state))throw Object.assign(Error("table state is immutable after Session completion"),{statusCode:409});const expectedRevision=Number(req.body?.expectedRevision);if(!Number.isSafeInteger(expectedRevision)||expectedRevision<1)throw Object.assign(Error("valid table revision required"),{statusCode:400});const phase=req.body?.phase,activeSceneId=req.body?.activeSceneId,completeSceneId=req.body?.completeSceneId,sharedNote=req.body?.sharedNote,privateNote=req.body?.privateNote;if(phase!==undefined&&!isTablePhase(phase))throw Object.assign(Error("invalid table phase"),{statusCode:400});for(const[name,value]of [["shared",sharedNote],["private",privateNote]] as const)if(value!==undefined&&(typeof value!=="string"||!value.trim()||value.trim().length>2000))throw Object.assign(Error(`invalid ${name} note`),{statusCode:400});if(activeSceneId!==undefined&&typeof activeSceneId!=="string"||completeSceneId!==undefined&&typeof completeSceneId!=="string")throw Object.assign(Error("invalid scene ID"),{statusCode:400});if(phase===undefined&&activeSceneId===undefined&&completeSceneId===undefined&&sharedNote===undefined&&privateNote===undefined)throw Object.assign(Error("table update is empty"),{statusCode:400});const event=privateNote!==undefined?{type:"TablePrivateNoteRecorded",payload:{}}:sharedNote!==undefined?{type:"TableSharedNoteRecorded",payload:{text:sharedNote.trim()}}:activeSceneId!==undefined||completeSceneId!==undefined?{type:"TableSceneChanged",payload:{activeSceneId,completeSceneId}}:{type:"TablePhaseChanged",payload:{phase}};const table=await advanced.updateTable(req.params.id,expectedRevision,value=>{if(phase!==undefined)value.phase=phase as TablePhase;if(activeSceneId!==undefined){if(!value.scenes.some(scene=>scene.id===activeSceneId))throw Object.assign(Error("table scene not found"),{statusCode:400});for(const scene of value.scenes)if(scene.status==="active")scene.status="complete";value.scenes.find(scene=>scene.id===activeSceneId)!.status="active";value.activeSceneId=activeSceneId}if(completeSceneId!==undefined){const scene=value.scenes.find(scene=>scene.id===completeSceneId);if(!scene)throw Object.assign(Error("table scene not found"),{statusCode:400});scene.status="complete";if(value.activeSceneId===completeSceneId)value.activeSceneId=undefined}if(sharedNote!==undefined)value.sharedNotes.push(sharedNote.trim());if(privateNote!==undefined)value.privateNotes.push(privateNote.trim());if(value.sharedNotes.length>100)value.sharedNotes=value.sharedNotes.slice(-100);if(value.privateNotes.length>100)value.privateNotes=value.privateNotes.slice(-100)},event);await broadcast(req.params.id,"table.state",visibleTableState(table,false));return table});
 app.post("/api/sessions/:id/table/beats",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});const phase=String(req.body?.phase??"") as TablePhase,title=String(req.body?.title??"").trim(),summary=String(req.body?.summary??"").trim();if(!isTablePhase(phase)||phase==="setup"||!title||title.length>120||summary.length>1000)throw Object.assign(Error("invalid table beat"),{statusCode:400});const event=await game.event(session.id,"TableBeatRecorded",{phase,title,...(summary?{summary}:{})});await broadcast(session.id,"table.beat",event.payload);return event});
 app.get("/api/sessions/:id/rehearsal-report",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const[participants,actorStates,events]=await Promise.all([repo.participants(session.id),actors.all(session.id),game.events(session.id)]);return buildRehearsalReport({sessionId:session.id,sessionState:session.state,participants,actors:actorStates,events})});
 app.get("/api/sessions/:id/runtime/verify",async(req:any)=>{await requireSessionGm(req,req.params.id);return replay.verify(req.params.id)});
 app.get("/api/sessions/:id/runtime/verify-checks",async(req:any)=>{await requireSessionGm(req,req.params.id);return checkRecovery.verify(req.params.id)});
 app.post("/api/sessions/:id/runtime/snapshots",async(req:any)=>{await requireSessionGm(req,req.params.id);return replay.createSnapshot(req.params.id)});
 app.get("/api/sessions/:id/runtime/verify-snapshot",async(req:any)=>{await requireSessionGm(req,req.params.id);return replay.verifyFromSnapshot(req.params.id)});
 app.get("/api/sessions/:id/participants/:participantId/checks",async(req:any)=>{await requireParticipant(req,req.params.participantId);const p=await repo.participant(req.params.participantId);if(p?.sessionId!==req.params.id)throw Object.assign(Error("participant not in session"),{statusCode:403});return(await game.pendingForParticipant(req.params.id,req.params.participantId)).map(value=>({request:visibleRequest(value.request as CheckRequest),resolution:value.resolution?visibleResolution(value.request as CheckRequest,value.resolution as CheckResolution):null}))});

 app.get("/api/sessions/:id/encounters",async(req:any)=>{await requireSessionMember(req,req.params.id);return encounters.forSession(req.params.id)});
 app.post("/api/sessions/:id/encounters",async(req:any)=>{
  await requireSessionGm(req,req.params.id);
  const idem=await idempotency(req,req.params.id);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(req.params.id);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const states=await actors.all(session.id),available=new Set(states.map(state=>state.actorId)),ids=req.body?.participantIds;
  if(!Array.isArray(ids)||ids.some(id=>typeof id!=="string"||!available.has(id)))throw Object.assign(Error("encounter participants must be initialized session actors"),{statusCode:400});
  const config=pack.content.encounter??{orderingPolicy:"none"};
  const attributes:Record<string,number>={};if(config.orderingPolicy==="attribute"){if(!config.attributeField)throw Error("encounter attribute field missing in Pack");for(const id of ids){const actor=states.find(state=>state.actorId===id);if(actor?.kind==="npc"){attributes[id]=Number(actor.attributes?.[config.attributeField]??NaN);continue}const participant=await repo.participant(id),character=participant?.characterId?await repo.character(participant.characterId):null;attributes[id]=Number(character?.values?.[config.attributeField]??NaN)}}
  const result=startEncounter({sessionId:session.id,participantIds:ids,policy:config.orderingPolicy,attributes,customOrder:req.body?.customOrder});
  const receipt=await mutations.commit(session.id,result.events,[],result.encounter,{},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);if(receipt.replayed)return receipt.result;await broadcast(session.id,"encounter.state",result.encounter);return result;
 });
 app.post("/api/encounters/:id/participants",async(req:any)=>{
  const current=await encounters.getVersioned(req.params.id);if(!current)throw Object.assign(Error("encounter not found"),{statusCode:404});
  const encounter=current.encounter;await requireSessionGm(req,encounter.sessionId);
  const idem=await idempotency(req,encounter.sessionId);if(idem?.prior!==undefined)return idem.prior;
  const session=await repo.session(encounter.sessionId);if(!session||session.state!=="live")throw Object.assign(Error("session is not live"),{statusCode:409});
  const added=req.body?.addActorIds??[],removed=req.body?.removeActorIds??[];
  if(!Array.isArray(added)||!Array.isArray(removed)||[...added,...removed].some(id=>typeof id!=="string"))throw Object.assign(Error("actor ID lists are required"),{statusCode:400});
  const available=new Set((await actors.all(encounter.sessionId)).map(state=>state.actorId));
  if(added.some(id=>!available.has(id)))throw Object.assign(Error("added actors must be initialized in this Session"),{statusCode:400});
  const result=changeEncounterParticipants(encounter,{addActorIds:added,removeActorIds:removed});
  const receipt=await mutations.commit(encounter.sessionId,result.events,[],result.encounter,{encounterVersion:current.version},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);
  if(receipt.replayed)return receipt.result;
  await broadcast(encounter.sessionId,"encounter.state",result.encounter);return result;
 });
 app.post("/api/encounters/:id/advance",async(req:any)=>{
  const current=await encounters.getVersioned(req.params.id);if(!current)throw Object.assign(Error("encounter not found"),{statusCode:404});
  const encounter=current.encounter;await requireSessionGm(req,encounter.sessionId);const idem=await idempotency(req,encounter.sessionId);if(idem?.prior!==undefined)return idem.prior;
  const versioned=await actors.allVersioned(encounter.sessionId),states=versioned.map(row=>row.state),actorVersions=Object.fromEntries(versioned.map(row=>[row.state.actorId,row.version])),defs=pack.content.effects??{};
  const effects=Object.fromEntries(Object.entries(defs).map(([id,value])=>[id,{id,...value as object}])) as Record<string,EffectDefinition>;
  const result=advanceEncounter(encounter,Object.fromEntries(states.map(state=>[state.actorId,state])),effects);
  const receipt=await mutations.commit(encounter.sessionId,result.events,result.states,result.encounter,{actorVersions,encounterVersion:current.version},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);if(receipt.replayed)return receipt.result;await broadcast(encounter.sessionId,"encounter.state",result.encounter);return result;
 });
 app.post("/api/encounters/:id/end",async(req:any)=>{const current=await encounters.getVersioned(req.params.id);if(!current)throw Object.assign(Error("encounter not found"),{statusCode:404});const encounter=current.encounter;await requireSessionGm(req,encounter.sessionId);const idem=await idempotency(req,encounter.sessionId);if(idem?.prior!==undefined)return idem.prior;const result=endEncounter(encounter);const receipt=await mutations.commit(encounter.sessionId,result.events,[],result.encounter,{encounterVersion:current.version},idem?{key:idem.key,fingerprint:idem.fingerprint,result}:undefined);if(receipt.replayed)return receipt.result;await broadcast(encounter.sessionId,"encounter.state",result.encounter);return result});

 app.post("/api/sessions/:id/exploration",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const world=await sessionWorld(session),allowedKinds=new Set(pack.content.locations?.worldEntityKinds??["location"]),locations=world.entities.filter(value=>allowedKinds.has(value.kind)),nodes=locations.map((value,index)=>({id:value.id,locationId:value.id,label:String(value.values.name?.value??value.kind),x:Number(value.values.x?.value??(index%4)*180+80),y:Number(value.values.y?.value??Math.floor(index/4)*130+80)})),fog=Array.isArray(req.body?.fog)?req.body.fog.map((value:any)=>validateFog(value)):[],result=await advanced.createBoard({sessionId:session.id,worldId:world.id,nodes,fog});if(result.created)await broadcast(session.id,"exploration.state",visibleExplorationBoard(result.board,false));return result.board});
 const validateFog=(value:any):FogRegion=>{if(!value||typeof value.id!=="string"||!value.id.trim()||typeof value.label!=="string"||!Array.isArray(value.polygon)||value.polygon.length<3||value.polygon.some((point:any)=>!Array.isArray(point)||point.length!==2||point.some((n:any)=>!Number.isFinite(n))))throw Object.assign(Error("invalid fog region"),{statusCode:400});return{id:value.id.slice(0,80),label:value.label.trim().slice(0,120),revealed:Boolean(value.revealed),polygon:value.polygon.map((point:any)=>[Number(point[0]),Number(point[1])])}};
 app.get("/api/sessions/:id/exploration",async(req:any)=>{const role=await requireViewer(req,req.params.id),board=await advanced.board(req.params.id);if(!board)throw Object.assign(Error("exploration board not found"),{statusCode:404});return visibleExplorationBoard(board,role==="gm")});
 app.patch("/api/sessions/:id/exploration/fog",async(req:any)=>{await requireSessionGm(req,req.params.id);const fog=validateFog(req.body?.fog),board=await advanced.updateBoard(req.params.id,Number(req.body?.expectedRevision),value=>{const index=value.fog.findIndex(item=>item.id===fog.id);if(index<0)value.fog.push(fog);else value.fog[index]=fog},{type:"FogRegionChanged",payload:{fogId:fog.id,revealed:fog.revealed}});await broadcast(req.params.id,"exploration.state",visibleExplorationBoard(board,false));return board});
 app.patch("/api/sessions/:id/exploration/token",async(req:any)=>{await requireSessionGm(req,req.params.id);const actorId=String(req.body?.actorId??""),nodeId=String(req.body?.nodeId??"");if(!(await actors.all(req.params.id)).some(value=>value.actorId===actorId))throw Object.assign(Error("actor is not initialized in this Session"),{statusCode:400});const board=await advanced.updateBoard(req.params.id,Number(req.body?.expectedRevision),value=>{if(!value.nodes.some(item=>item.id===nodeId))throw Object.assign(Error("exploration node not found"),{statusCode:400});const item=value.tokens.find(token=>token.actorId===actorId);if(item)item.nodeId=nodeId;else value.tokens.push({actorId,nodeId})},{type:"ExplorationTokenMoved",payload:{actorId,nodeId}});await broadcast(req.params.id,"exploration.state",visibleExplorationBoard(board,false));return board});
 app.post("/api/sessions/:id/spectators",async(req:any)=>{await requireSessionGm(req,req.params.id);return advanced.createSpectator(req.params.id,String(req.body?.label??"Spectator"))});
 app.delete("/api/sessions/:id/spectators/:grantId",async(req:any)=>{await requireSessionGm(req,req.params.id);return advanced.revokeSpectator(req.params.grantId,req.params.id)});
 app.get("/api/sessions/:id/replay",async(req:any)=>{const role=await requireViewer(req,req.params.id),after=Math.max(0,Number(req.query?.afterSequence??0)),all=await game.events(req.params.id),visible=role==="gm"?all:redactSpectatorTimeline(all),events=visible.filter(value=>value.sequence>after),board=await advanced.board(req.params.id);return{role,events,board:board?visibleExplorationBoard(board,role==="gm"):null,lastSequence:all.at(-1)?.sequence??after}});
 app.get("/api/sessions/:id/recap",async(req:any)=>{const role=await requireViewer(req,req.params.id),session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const events=await game.events(req.params.id);return buildCampaignRecap(session.campaignId,role==="gm"?events:redactSpectatorTimeline(events))});
 app.get("/api/sessions/:id/canon",async(req:any)=>{await requireSessionMember(req,req.params.id);const session=await repo.session(req.params.id);return session?advanced.canon(session.realmId):[]});
 app.post("/api/sessions/:id/canon",async(req:any)=>{await requireSessionGm(req,req.params.id);const session=await repo.session(req.params.id);if(!session)throw Object.assign(Error("session not found"),{statusCode:404});const key=String(req.body?.key??"").trim(),title=String(req.body?.title??"").trim();if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/.test(key)||!title)throw Object.assign(Error("valid canon key and title required"),{statusCode:400});const fact=await advanced.promoteFact({realmId:session.realmId,key,title:title.slice(0,160),value:req.body?.value??null,campaignId:session.campaignId,sessionId:session.id});await broadcast(session.id,"canon.changed",fact);return fact});
 app.get("/api/advanced/ai",async()=>({enabled:false,provider:null,coreDependency:false,capabilities:["recap-decoration"],deterministicFallback:true}));

 app.get("/ws/sessions/:id",{websocket:true},(socket:any,req:any)=>{const id=req.params.id;let client:{socket:any;participantId?:string;gm:boolean}|undefined;const timer=setTimeout(()=>socket.close(1008,"authentication timeout"),5000);socket.on("message",async(raw:Buffer)=>{if(client)return;try{const message=JSON.parse(raw.toString()),credential=String(message?.token??""),afterSequence=Number(message?.afterSequence??0);if(message?.type!=="authenticate"||!credential||!Number.isSafeInteger(afterSequence)||afterSequence<0){socket.close(1008,"authorization required");return}const gm=await repo.verifySessionGm(id,credential),member=gm?null:await repo.sessionMember(id,credential);if(!gm&&!member){socket.close(1008,"authorization required");return}clearTimeout(timer);client={socket,gm,participantId:member?.id};let set=sockets.get(id);if(!set)sockets.set(id,set=new Set());set.add(client);if(afterSequence)await game.event(id,"SessionReconnected",{role:gm?"gm":"player",participantId:member?.id??null,afterSequence});const state=await snapshot(id),missed=(await game.events(id,afterSequence)).map(event=>({id:event.id,sequence:event.sequence,type:event.type,createdAt:event.createdAt,...(event.type==="NarrativeEventRecorded"?{text:String((event.payload as any)?.text??"")}:{})})),windowed=missed.slice(-200);socket.send(JSON.stringify({type:afterSequence?"session.catchup":"session.snapshot",sessionId:id,payload:{...state,missedEvents:windowed,missedEventCount:missed.length,truncated:missed.length>windowed.length},sequence:state.lastSequence,at:new Date().toISOString()}))}catch{socket.close(1008,"invalid authentication")}});socket.on("close",()=>{clearTimeout(timer);const set=sockets.get(id);if(client)set?.delete(client);if(set&&!set.size)sockets.delete(id)})});
}
