import React,{useEffect,useState}from"react";
import{realmHeaders}from"./realm.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
type Board={revision:number;nodes:{id:string;label:string}[];tokens:{actorId:string;nodeId:string}[];fog:{id:string;label:string;revealed:boolean;polygon?:[number,number][]}[]};
async function api(path:string,token:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:realmHeaders({...init.headers,authorization:`Bearer ${token}`})}),body=await response.json();if(!response.ok)throw Error(body.message??`HTTP ${response.status}`);return body}
export function AdvancedSessionPanel({sessionId,token,gm,actors}:{sessionId:string;token:string;gm:boolean;actors:{actorId:string;label?:string}[]}){
 const[board,setBoard]=useState<Board>(),[replay,setReplay]=useState<any>(),[recap,setRecap]=useState<any>(),[canon,setCanon]=useState<any[]>([]),[message,setMessage]=useState(""),[spectator,setSpectator]=useState(""),[canonKey,setCanonKey]=useState("first-contact"),[canonTitle,setCanonTitle]=useState("First contact established");
 const load=async()=>{const results=await Promise.allSettled([api(`/sessions/${sessionId}/exploration`,token),api(`/sessions/${sessionId}/replay`,token),api(`/sessions/${sessionId}/recap`,token),api(`/sessions/${sessionId}/canon`,token)]);if(results[0].status==="fulfilled")setBoard(results[0].value);else if(!String(results[0].reason).includes("not found"))setMessage(`Exploration: ${String(results[0].reason)}`);if(results[1].status==="fulfilled")setReplay(results[1].value);else setMessage(`Replay: ${String(results[1].reason)}`);if(results[2].status==="fulfilled")setRecap(results[2].value);else setMessage(`Recap: ${String(results[2].reason)}`);if(results[3].status==="fulfilled")setCanon(results[3].value);else if(gm)setMessage(`Canon: ${String(results[3].reason)}`)};
 useEffect(()=>{void load()},[sessionId,token]);
 const send=async(path:string,method:string,body:any)=>{try{const value=await api(path,token,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage("Saved");await load();return value}catch(error:any){setMessage(error.message)}};
 return <article><div className="titleRow"><h3>Exploration, replay and canon</h3><button className="secondary" onClick={()=>void load()}>Refresh</button></div>{message&&<p className={message==="Saved"?"notice":"error"}>{message}</p>}
  {!board&&gm&&<button onClick={()=>void send(`/sessions/${sessionId}/exploration`,"POST",{fog:[{id:"unexplored",label:"Unexplored region",revealed:false,polygon:[[0,0],[100,0],[100,100],[0,100]]}]})}>START EXPLORATION MAP</button>}
  {board&&<><p>{board.nodes.length} visible locations · revision {board.revision}</p>{board.nodes.map(node=><div className="compactRow" key={node.id}><b>{node.label}</b><small>{board.tokens.filter(token=>token.nodeId===node.id).map(token=>actors.find(actor=>actor.actorId===token.actorId)?.label??token.actorId).join(", ")||"No tokens"}</small>{gm&&actors[0]&&<button className="secondary" onClick={()=>void send(`/sessions/${sessionId}/exploration/token`,"PATCH",{expectedRevision:board.revision,actorId:actors[0].actorId,nodeId:node.id})}>Move {actors[0].label??"actor"}</button>}</div>)}{board.fog.map(fog=><div className="compactRow" key={fog.id}><span>{fog.label}</span><b>{fog.revealed?"Revealed":"Hidden"}</b>{gm&&<button className="secondary" onClick={()=>void send(`/sessions/${sessionId}/exploration/fog`,"PATCH",{expectedRevision:board.revision,fog:{...fog,revealed:!fog.revealed,polygon:fog.polygon}})}>{fog.revealed?"Hide":"Reveal"}</button>}</div>)}</>}
  {gm&&<><button className="secondary" onClick={async()=>{const value=await send(`/sessions/${sessionId}/spectators`,"POST",{label:"Shared spectator"});if(value)setSpectator(value.accessToken)}}>CREATE SPECTATOR ACCESS</button>{spectator&&<p><small>Read-only spectator token</small><code>{spectator}</code></p>}<div className="actions"><input value={canonKey} onChange={e=>setCanonKey(e.target.value)} aria-label="Canon key"/><input value={canonTitle} onChange={e=>setCanonTitle(e.target.value)} aria-label="Canon title"/><button onClick={()=>void send(`/sessions/${sessionId}/canon`,"POST",{key:canonKey,title:canonTitle,value:{established:true}})}>PROMOTE TO REALM CANON</button></div></>}
  <h4>Realm canon</h4>{canon.length?canon.map(fact=><div className="compactRow" key={fact.key}><b>{fact.title}</b><small>v{fact.revision}</small></div>):<p className="muted">No shared facts yet.</p>}
  <h4>Campaign recap</h4>{recap?.entries?.length?recap.entries.slice(-8).map((entry:any)=><div className="compactRow" key={entry.sequence}><span>#{entry.sequence}</span><small>{entry.text}</small></div>):<p className="muted">No recap entries yet.</p>}
  <h4>Replay timeline</h4><p className="muted">{replay?.events?.length??0} authoritative events · deterministic recap · AI disabled by default</p>{replay?.events?.slice(-12).map((event:any)=><div className="compactRow" key={event.id??event.sequence}><b>#{event.sequence}</b><span>{event.type}</span><small>{event.createdAt?new Date(event.createdAt).toLocaleTimeString():""}</small></div>)}
 </article>
}
