import {recapEntryText} from './i18n/recap.js';
import {authoredActorLabel,authoredValue} from './i18n/content.js';
import {useContentI18n} from './i18n/content-react.js';
import React,{useEffect,useMemo,useState}from"react";
import{currentRealm,realmHeaders}from"./realm.js";
import type{ConnectionStatus}from"./session-client.js";
import{sessionSocket}from"./session-client.js";
import{useI18n}from"./i18n/react.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
type Board={revision:number;nodes:{id:string;label:string;labelSource?:string;x:number;y:number}[];tokens:{actorId:string;nodeId:string}[];fog:{id:string;label:string;revealed:boolean;polygon?:[number,number][]}[]};
type Table={revision:number;phase:string;activeSceneId?:string;scenes:{id:string;title:string;titleSource?:string;summary?:string;summarySource?:string;status:string}[];sharedNotes:string[];privateNotes?:string[]};
type Rehearsal={gatePassed:boolean;missing:string[];stages:Record<string,{passed:boolean;count:number}>};
async function api(path:string,token:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:realmHeaders({...init.headers,authorization:`Bearer ${token}`})}),body=await response.json();if(!response.ok)throw Error(body.message??`HTTP ${response.status}`);return body}
export function AdvancedSessionPanel({sessionId,token,gm,actors,worldId,onOpenChecks,onOpenEncounter,variant,journalEntries}:{sessionId:string;token:string;gm:boolean;actors:{actorId:string;kind?:string;label?:string;labelSource?:string;worldEntityId?:string;worldEntityLabel?:string;worldEntityNameSource?:string}[];worldId?:string;onOpenChecks?:()=>void;onOpenEncounter?:()=>void;variant?:"player-map";journalEntries?:{id:string;text:string}[]}){
 const{t}=useI18n();
 const[connection,setConnection]=useState<ConnectionStatus>("connecting");
 const[board,setBoard]=useState<Board>(),[table,setTable]=useState<Table>(),[replay,setReplay]=useState<any>(),[recap,setRecap]=useState<any>(),[canon,setCanon]=useState<any[]>([]),[rehearsal,setRehearsal]=useState<Rehearsal>(),[context,setContext]=useState<{world:{id:string};pack?:{id:string;universe?:import("./i18n/content.js").ContentPack["universe"]};media?:{map?:string;background?:string};sceneMedia?:Record<string,string>}>(),[message,setMessage]=useState(""),[spectator,setSpectator]=useState(""),[canonKey,setCanonKey]=useState("first-contact"),[canonTitle,setCanonTitle]=useState("First contact established"),[mapActor,setMapActor]=useState(""),[note,setNote]=useState(""),[privateNote,setPrivateNote]=useState(""),[beatTitle,setBeatTitle]=useState("The crew gains an ally"),[beatSummary,setBeatSummary]=useState("The negotiation changes the situation."),[beatPhase,setBeatPhase]=useState("social"),[gmRoll,setGmRoll]=useState(17),[rolling,setRolling]=useState(false);
 const {c}=useContentI18n(context?.pack?{manifest:{id:context.pack.id},universe:context.pack.universe}:undefined);
 const [editedSuggestions,setEditedSuggestions]=useState<Record<string,boolean>>({});
 const suggested=(key:string,value:string)=>editedSuggestions[key]?value:c(value);
 const sceneTitle=(scene:Table["scenes"][number]|undefined)=>authoredValue({value:scene?.title,source:scene?.titleSource},c);
 const sceneSummary=(scene:Table["scenes"][number]|undefined)=>authoredValue({value:scene?.summary,source:scene?.summarySource},c);
 const loadTablePart=async(path:string)=>{try{return await api(path,token)}catch(error){if(!gm||!String(error).includes("not found"))throw error;return api(path,token,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({})})}};
 const load=async()=>{const results=await Promise.allSettled([loadTablePart(`/sessions/${sessionId}/exploration`),loadTablePart(`/sessions/${sessionId}/table`),api(`/sessions/${sessionId}/replay`,token),api(`/sessions/${sessionId}/recap`,token),api(`/sessions/${sessionId}/canon`,token),gm?api(`/sessions/${sessionId}/rehearsal-report`,token):Promise.resolve(undefined),api(`/sessions/${sessionId}/context`,token)]);if(results[0].status==="fulfilled")setBoard(results[0].value);else if(!String(results[0].reason).includes("not found"))setMessage(`Exploration: ${String(results[0].reason)}`);if(results[1].status==="fulfilled")setTable(results[1].value);else if(!String(results[1].reason).includes("not found"))setMessage(`Table: ${String(results[1].reason)}`);if(results[2].status==="fulfilled")setReplay(results[2].value);if(results[3].status==="fulfilled")setRecap(results[3].value);if(results[4].status==="fulfilled")setCanon(results[4].value);if(results[5].status==="fulfilled"&&results[5].value)setRehearsal(results[5].value as Rehearsal);if(results[6].status==="fulfilled")setContext(results[6].value as {world:{id:string};pack?:{id:string;universe?:import("./i18n/content.js").ContentPack["universe"]};media?:{map?:string;background?:string};sceneMedia?:Record<string,string>})};
 useEffect(()=>{void load()},[sessionId,token]);useEffect(()=>{if(!actors.some(actor=>actor.actorId===mapActor))setMapActor(actors[0]?.actorId??"")},[actors,mapActor]);
 useEffect(()=>{const socket=sessionSocket(sessionId,token,event=>{if(["table.state","table.beat","exploration.state","actor.state","session.catchup"].includes(event.type))void load()},setConnection);return()=>socket.close()},[sessionId,token]);
 const send=async(path:string,method:string,body:any)=>{if(connection!=="live"){setMessage(t("common.reconnecting"));return undefined}try{const value=await api(path,token,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage("Saved");await load();return value}catch(error:any){setMessage(error.message);await load()}};
 const extent=useMemo(()=>({width:Math.max(420,...(board?.nodes.map(node=>node.x+90)??[])),height:Math.max(260,...(board?.nodes.map(node=>node.y+70)??[]))}),[board]);
 const actorName=(id:string)=>{const actor=actors.find(actor=>actor.actorId===id);return actor?(actor.kind==="npc"?authoredActorLabel(actor,c):actor.label??t("table.token")):(id===mapActor?t("table.selectedActor"):t("table.token"))};
 const phaseLabel=(phase:string)=>t(`table.phase.${phase}` as "table.phase.setup");
 const rollGmDie=()=>{setRolling(true);window.setTimeout(()=>{setGmRoll(Math.floor(Math.random()*20)+1);setRolling(false)},420)};
	 if(gm){
	  const activeScene=table?.scenes.find(scene=>scene.id===table.activeSceneId)??table?.scenes[0],visibleScenes=table?[activeScene,...table.scenes.filter(scene=>scene.id!==activeScene?.id)].filter(Boolean).slice(0,4) as Table["scenes"]:[],mapAssetUrl=context?.media?.map?`${API}/worlds/${encodeURIComponent(context.world.id)}/pack-assets/${context.media.map.replace(/^assets\//,"")}?realm=${encodeURIComponent(currentRealm())}`:undefined;
  return <article className="gmTableCockpit"><fieldset className="gmTableControls" disabled={connection!=="live"}>
   {message&&<p className={message==="Saved"?"notice cockpitMessage":"error cockpitMessage"}>{message==="Saved"?t("table.saved"):message}</p>}
   <aside className="cockpitScenes">
    <div className="cockpitSectionTitle"><h3>{t("table.scenes")}</h3>{!table&&<button className="iconButton" title={t("table.prepare")} onClick={()=>void send(`/sessions/${sessionId}/table`,"POST",{})}>+</button>}</div>
	    <div className="cockpitSceneList">{visibleScenes.map((scene,index)=><button key={scene.id} className={scene.id===activeScene?.id?"cockpitScene active":"cockpitScene"} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table?.revision??0,activeSceneId:scene.id})}><span className={`sceneThumb sceneThumb${(index%4)+1}`} style={context?.sceneMedia?.[scene.id]?{backgroundImage:`linear-gradient(#07101822,#07101866),url(${API}/worlds/${encodeURIComponent(context.world.id)}/pack-assets/${context.sceneMedia[scene.id].replace(/^assets\//,"")}?realm=${encodeURIComponent(currentRealm())})`,backgroundPosition:"center"}:mapAssetUrl?{backgroundImage:`linear-gradient(#07101822,#07101866),url(${mapAssetUrl})`,backgroundPosition:`${20+index*22}% ${25+index*13}%`}:undefined}/><span><b>{sceneTitle(scene)}</b><small>{scene.summary?sceneSummary(scene):phaseLabel(table?.phase??"setup")}</small></span></button>)}</div>{table&&table.scenes.length>4&&<details className="allScenes"><summary>{t("table.scenes")} · {table.scenes.length}</summary><div>{table.scenes.filter(scene=>!visibleScenes.some(visible=>visible.id===scene.id)).map(scene=><button key={scene.id} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table?.revision??0,activeSceneId:scene.id})}>{sceneTitle(scene)}</button>)}</div></details>}
    <div className="cockpitNotes"><div className="mobileSessionEvents"><h3>{t("player.journal")}</h3>{journalEntries?.length?journalEntries.map(entry=><p key={entry.id}>{entry.text}</p>):<p className="muted">{t("player.noActivity")}</p>}</div><div className="cockpitSectionTitle"><h3>{t("table.notebook")}</h3></div>{table?.privateNotes?.slice(-2).map((value,index)=><p className="paperNote" key={index}>{value}</p>)}{!table?.privateNotes?.length&&<p className="muted">{t("table.noNotes")}</p>}<label className="quickNote"><span>{t("table.privateNote")}</span><textarea rows={3} value={privateNote} onChange={event=>setPrivateNote(event.target.value)}/></label><button className="secondary" disabled={!privateNote.trim()||!table} onClick={()=>table&&void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,privateNote:privateNote.trim()}).then(result=>{if(result!==undefined)setPrivateNote("")})}>{t("table.savePrivate")}</button></div>
   </aside>
   <section className="cockpitStage">
    <div className="stageHeading"><div><p className="eyebrow">{phaseLabel(table?.phase??"setup")}</p><h2>{activeScene?sceneTitle(activeScene):t("gm.firstTitle")}</h2></div>{board&&<label className="mapActorPicker"><span>{t("table.moveToken")}</span><select value={mapActor} onChange={event=>setMapActor(event.target.value)}>{actors.map(actor=><option key={actor.actorId} value={actor.actorId}>{actorName(actor.actorId)}</option>)}</select></label>}</div>
	    {!board?<div className="emptyMap"><span>⌖</span><h3>{t("table.map")}</h3><p>{t("gm.tableHelp")}</p><button onClick={()=>void send(`/sessions/${sessionId}/exploration`,"POST",{fog:[{id:"opening-fog",label:"Unexplored area",revealed:false,polygon:[[0,0],[220,0],[220,170],[0,170]]}]})}>{t("table.startMap")}</button></div>:<div className="cockpitMap" aria-label={t("table.map")}>{mapAssetUrl&&<img className="packMapBackdrop" src={mapAssetUrl} alt="" onError={event=>{event.currentTarget.hidden=true}}/>}<svg viewBox={`0 0 ${extent.width} ${extent.height}`} role="img"><defs><pattern id="map-grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="currentColor" strokeOpacity=".12"/></pattern><radialGradient id="map-glow"><stop offset="0" stopColor="#35523f" stopOpacity=".18"/><stop offset="1" stopColor="#101a18" stopOpacity=".48"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#map-glow)"/><rect width="100%" height="100%" fill="url(#map-grid)"/>{board.nodes.map(node=><path key={`road-${node.id}`} d={`M ${extent.width/2} ${extent.height/2} Q ${node.x} ${extent.height/2} ${node.x} ${node.y}`} className="mapRoad"/>)}{board.fog.filter(fog=>fog.polygon?.length).map(fog=><polygon key={fog.id} points={fog.polygon!.map(point=>point.join(",")).join(" ")} className={fog.revealed?"fog revealed":"fog hidden"}/>)}{board.nodes.map(node=><g key={node.id} className="mapNode" onClick={()=>mapActor&&void send(`/sessions/${sessionId}/exploration/token`,"PATCH",{expectedRevision:board.revision,actorId:mapActor,nodeId:node.id})}><circle cx={node.x} cy={node.y} r="27"/><text x={node.x} y={node.y+46} textAnchor="middle">{authoredValue({value:node.label,source:node.labelSource},c)}</text></g>)}{board.tokens.map(token=>{const node=board.nodes.find(value=>value.id===token.nodeId);return node?<g key={token.actorId} className="mapToken"><circle cx={node.x} cy={node.y} r="16"/><text x={node.x} y={node.y+4} textAnchor="middle">{actorName(token.actorId).slice(0,2).toUpperCase()}</text></g>:null})}</svg>{board.fog.length>0&&<div className="fogControls">{board.fog.map(fog=><button key={fog.id} className="secondary compactButton" onClick={()=>void send(`/sessions/${sessionId}/exploration/fog`,"PATCH",{expectedRevision:board.revision,fog:{...fog,revealed:!fog.revealed,polygon:fog.polygon}})}>{fog.revealed?t("table.hide"):t("table.reveal")} · {fog.id==="opening-fog"&&fog.label==="Unexplored area"?c(fog.label):fog.label}</button>)}</div>}</div>}
    {table?.sharedNotes.length?<div className="activityRibbon">✦ {table.sharedNotes.at(-1)}</div>:null}
   </section>
   <footer className="cockpitTray">
    <button className={`gmDie d20${rolling?" rolling":""}`} aria-label={t("player.roll")} onClick={rollGmDie}><span>{gmRoll}</span><small>{c("d20")}</small></button><button className="gmDie d6" aria-label="d6" onClick={()=>setGmRoll(Math.floor(Math.random()*6)+1)}><span>{Math.min(gmRoll,6)}</span><small>{c("d6")}</small></button><div className="lastRoll"><small>{t("player.dice")}</small><strong>{gmRoll}</strong></div>
    <div className="cockpitQuickActions"><button className="secondary" onClick={()=>activeScene&&table&&void send(`/sessions/${sessionId}/table/beats`,"POST",{phase:table.phase,title:activeScene.title,summary:activeScene.summary??"Scene opened"})}>▣ {t("game.opening")}</button><button className="secondary" onClick={onOpenChecks}>◇ {t("gm.openChecks")}</button><button className="secondary" onClick={()=>document.querySelector<HTMLTextAreaElement>(".quickNote textarea")?.focus()}>⌕ {t("table.privateNote")}</button><button onClick={onOpenEncounter}>▶ {t("gm.encounter")}</button></div>
   </footer>
  </fieldset></article>
	 }
	 if(variant==="player-map"){
	  const activeScene=table?.scenes.find(scene=>scene.id===table.activeSceneId)??table?.scenes[0];
	  return <article className="playerMapConsole">
	   <div className="playerSceneHeading"><div><p className="eyebrow">{phaseLabel(table?.phase??"setup")}</p><h1>{activeScene?sceneTitle(activeScene):t("table.map")}</h1><p>{activeScene?.summary?sceneSummary(activeScene):t("table.noNotes")}</p></div><span className="sceneLive">{c("● LIVE")}</span></div>
	   {!board?<div className="emptyMap playerEmptyMap"><span>⌖</span><h3>{t("table.map")}</h3><p>{t("table.noNotes")}</p></div>:<div className="playerMapCanvas" aria-label={t("table.map")}>{context?.media?.map&&<img className="packMapBackdrop" src={`${API}/worlds/${encodeURIComponent(context.world.id)}/pack-assets/${context.media.map.replace(/^assets\//,"")}?realm=${encodeURIComponent(currentRealm())}`} alt="" onError={event=>{event.currentTarget.hidden=true}}/>}<svg viewBox={`0 0 ${extent.width} ${extent.height}`} role="img"><defs><pattern id="player-map-grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="currentColor" strokeOpacity=".08"/></pattern><radialGradient id="player-map-glow"><stop offset="0" stopColor="#4b674d" stopOpacity=".08"/><stop offset="1" stopColor="#0b1116" stopOpacity=".35"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#player-map-glow)"/><rect width="100%" height="100%" fill="url(#player-map-grid)"/>{board.nodes.map(node=><path key={`player-road-${node.id}`} d={`M ${extent.width/2} ${extent.height/2} Q ${node.x} ${extent.height/2} ${node.x} ${node.y}`} className="mapRoad"/>)}{board.fog.filter(fog=>fog.polygon?.length).map(fog=><polygon key={fog.id} points={fog.polygon!.map(point=>point.join(",")).join(" ")} className={fog.revealed?"fog revealed":"fog hidden"}/>)}{board.nodes.map(node=><g key={node.id} className="mapNode"><circle cx={node.x} cy={node.y} r="27"/><text x={node.x} y={node.y+46} textAnchor="middle">{authoredValue({value:node.label,source:node.labelSource},c)}</text></g>)}{board.tokens.map(token=>{const node=board.nodes.find(value=>value.id===token.nodeId);return node?<g key={token.actorId} className="mapToken"><circle cx={node.x} cy={node.y} r="17"/><text x={node.x} y={node.y+4} textAnchor="middle">{actorName(token.actorId).slice(0,2).toUpperCase()}</text></g>:null})}</svg></div>}
	   {table?.sharedNotes.length?<div className="playerActivityRibbon"><span>✦</span><p>{table.sharedNotes.at(-1)}</p></div>:null}
	  </article>
	 }
	 return <article className="tableConsole"><div className="titleRow"><h3>{t("table.console")}</h3><button className="secondary" onClick={()=>void load()}>{t("table.refresh")}</button></div>{message&&<p className={message==="Saved"?"notice":"error"}>{message==="Saved"?t("table.saved"):message}</p>}
  {!table&&gm&&<button onClick={()=>void send(`/sessions/${sessionId}/table`,"POST",{})}>{t("table.prepare")}</button>}
  {table&&<section className="tableState"><div className="titleRow"><div><small>{t("table.pace")}</small><h3>{phaseLabel(table.phase)}</h3></div></div>{gm&&<div className="phaseRail">{["setup","exploration","social","encounter","reward","epilogue"].map(phase=><button key={phase} className={table.phase===phase?"selected secondary":"secondary"} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,phase})}>{phaseLabel(phase)}</button>)}</div>}
   <h4>{t("table.scenes")}</h4><div className="sceneRail">{table.scenes.map(scene=><button key={scene.id} className={`${scene.status} secondary`} disabled={!gm} onClick={()=>gm&&void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table?.revision??0,activeSceneId:scene.id})}><b>{sceneTitle(scene)}</b><small>{c(scene.status)}</small></button>)}</div>
   {table.activeSceneId&&<p>{t("table.activeScene")}: <b>{sceneTitle(table.scenes.find(scene=>scene.id===table.activeSceneId))}</b></p>}
   <h4>{t("table.sharedNotes")}</h4>{table.sharedNotes.length?table.sharedNotes.slice(-8).map((value,index)=><p className="tableNote" key={index}>{value}</p>):<p className="muted">{t("table.noNotes")}</p>}
   {gm&&<><div className="noteGrid"><label>{t("table.sharedNote")}<textarea rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label><button disabled={!note.trim()} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,sharedNote:note.trim()}).then(result=>{if(result!==undefined)setNote("")})}>{t("table.shareNote")}</button><label>{t("table.privateNote")}<textarea rows={2} value={privateNote} onChange={event=>setPrivateNote(event.target.value)}/></label><button className="secondary" disabled={!privateNote.trim()} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,privateNote:privateNote.trim()}).then(result=>{if(result!==undefined)setPrivateNote("")})}>{t("table.savePrivate")}</button></div>{table.privateNotes?.length?<details><summary>{t("table.notebook")} · {table.privateNotes.length}</summary>{table.privateNotes.map((value,index)=><p className="tableNote private" key={index}>{value}</p>)}</details>:null}
    <h4>{t("table.recordBeat")}</h4><div className="beatGrid"><select aria-label={t("table.beatPhase")} value={beatPhase} onChange={event=>setBeatPhase(event.target.value)}>{["exploration","social","encounter","reward","epilogue"].map(value=><option key={value} value={value}>{phaseLabel(value)}</option>)}</select><input aria-label={t("table.beatTitle")} value={suggested("beatTitle",beatTitle)} onChange={event=>{setEditedSuggestions(value=>({...value,beatTitle:true}));setBeatTitle(event.target.value)}}/><input aria-label={t("table.beatSummary")} value={suggested("beatSummary",beatSummary)} onChange={event=>{setEditedSuggestions(value=>({...value,beatSummary:true}));setBeatSummary(event.target.value)}}/><button disabled={!beatTitle.trim()} onClick={()=>void send(`/sessions/${sessionId}/table/beats`,"POST",{phase:beatPhase,title:suggested("beatTitle",beatTitle),summary:suggested("beatSummary",beatSummary)})}>{t("table.record")}</button></div></>}
  </section>}
  <h4>{t("table.map")}</h4>{!board&&gm&&<button onClick={()=>void send(`/sessions/${sessionId}/exploration`,"POST",{fog:[{id:"opening-fog",label:"Unexplored area",revealed:false,polygon:[[0,0],[220,0],[220,170],[0,170]]}]})}>{t("table.startMap")}</button>}
  {board&&<><div className="mapToolbar"><span>{t("table.visibleLocations",{count:board.nodes.length})}</span>{gm&&<label>{t("table.moveToken")}<select value={mapActor} onChange={event=>setMapActor(event.target.value)}>{actors.map(actor=><option key={actor.actorId} value={actor.actorId}>{actorName(actor.actorId)}</option>)}</select></label>}</div><div className="tableMap" aria-label={t("table.map")}><svg viewBox={`0 0 ${extent.width} ${extent.height}`} role="img">{board.fog.filter(fog=>fog.polygon?.length).map(fog=><polygon key={fog.id} points={fog.polygon!.map(point=>point.join(",")).join(" ")} className={fog.revealed?"fog revealed":"fog hidden"}/>)}{board.nodes.map(node=><g key={node.id} className="mapNode" onClick={()=>gm&&mapActor&&void send(`/sessions/${sessionId}/exploration/token`,"PATCH",{expectedRevision:board.revision,actorId:mapActor,nodeId:node.id})}><circle cx={node.x} cy={node.y} r="25"/><text x={node.x} y={node.y+43} textAnchor="middle">{authoredValue({value:node.label,source:node.labelSource},c)}</text></g>)}{board.tokens.map(token=>{const node=board.nodes.find(value=>value.id===token.nodeId);return node?<g key={token.actorId} className="mapToken"><circle cx={node.x} cy={node.y} r="14"/><text x={node.x} y={node.y+4} textAnchor="middle">{actorName(token.actorId).slice(0,2).toUpperCase()}</text></g>:null})}</svg></div>{gm&&board.fog.map(fog=><div className="compactRow" key={fog.id}><span>{fog.id==="opening-fog"&&fog.label==="Unexplored area"?c(fog.label):fog.label}</span><b>{fog.revealed?t("table.revealed"):t("table.hidden")}</b><button className="secondary" onClick={()=>void send(`/sessions/${sessionId}/exploration/fog`,"PATCH",{expectedRevision:board.revision,fog:{...fog,revealed:!fog.revealed,polygon:fog.polygon}})}>{fog.revealed?t("table.hide"):t("table.reveal")}</button></div>)}</>}
  <details className="sessionHistory"><summary>{t("table.history")}</summary><h4>{t("table.canon")}</h4>{canon.length?canon.map(fact=><div className="compactRow" key={fact.key}><b>{fact.title}</b><small>{c("v")}{fact.revision}</small></div>):<p className="muted">{t("table.noFacts")}</p>}<h4>{t("table.recap")}</h4>{recap?.entries?.length?recap.entries.slice(-8).map((entry:any)=><div className="compactRow" key={entry.sequence}><span>#{entry.sequence}</span><small>{recapEntryText(entry,c)}</small></div>):<p className="muted">{t("table.noRecap")}</p>}<h4>{t("table.replay")}</h4><p className="muted">{t("table.eventCount",{count:replay?.events?.length??0})}</p>{replay?.events?.slice(-12).map((event:any)=><div className="compactRow" key={event.id??event.sequence}><b>#{event.sequence}</b><span>{c(event.type)}</span><small>{event.createdAt?new Date(event.createdAt).toLocaleTimeString():""}</small></div>)}</details>
  {gm&&<details className="technicalEvidence"><summary>{t("gm.devTools")}</summary>{rehearsal&&<section className={rehearsal.gatePassed?"rehearsal passed":"rehearsal"}><div className="titleRow"><h4>{c("M15 rehearsal")}</h4><b>{rehearsal.gatePassed?"COMPLETE":"IN PROGRESS"}</b></div><div className="stageGrid">{Object.entries(rehearsal.stages).map(([name,stage])=><span className={stage.passed?"done":""} key={name}>{stage.passed?"✓":"○"} {name} · {stage.count}</span>)}</div></section>}<button className="secondary" onClick={async()=>{const value=await send(`/sessions/${sessionId}/spectators`,"POST",{label:"Shared spectator"});if(value)setSpectator(value.accessToken)}}>{c("CREATE SPECTATOR ACCESS")}</button>{spectator&&<p><small>{c("Read-only spectator token")}</small><code>{spectator}</code></p>}<div className="actions"><input value={canonKey} onChange={e=>setCanonKey(e.target.value)} aria-label={c("Canon key")}/><input value={suggested("canonTitle",canonTitle)} onChange={e=>{setEditedSuggestions(value=>({...value,canonTitle:true}));setCanonTitle(e.target.value)}} aria-label={c("Canon title")}/><button onClick={()=>void send(`/sessions/${sessionId}/canon`,"POST",{key:canonKey,title:suggested("canonTitle",canonTitle),value:{established:true}})}>{c("PROMOTE TO REALM CANON")}</button></div><h4>{c("Realm canon")}</h4>{canon.map(fact=><div className="compactRow" key={fact.key}><b>{fact.title}</b><small>{c("v")}{fact.revision}</small></div>)}<h4>{c("Replay timeline")}</h4><p className="muted">{replay?.events?.length??0} {c("authoritative events")}</p></details>}
 </article>
}
