import React,{useEffect,useMemo,useState}from"react";
import{realmHeaders}from"./realm.js";
import{sessionSocket}from"./session-client.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
type Board={revision:number;nodes:{id:string;label:string;x:number;y:number}[];tokens:{actorId:string;nodeId:string}[];fog:{id:string;label:string;revealed:boolean;polygon?:[number,number][]}[]};
type Table={revision:number;phase:string;activeSceneId?:string;scenes:{id:string;title:string;summary?:string;status:string}[];sharedNotes:string[];privateNotes?:string[]};
type Rehearsal={gatePassed:boolean;missing:string[];stages:Record<string,{passed:boolean;count:number}>};
async function api(path:string,token:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:realmHeaders({...init.headers,authorization:`Bearer ${token}`})}),body=await response.json();if(!response.ok)throw Error(body.message??`HTTP ${response.status}`);return body}
export function AdvancedSessionPanel({sessionId,token,gm,actors}:{sessionId:string;token:string;gm:boolean;actors:{actorId:string;label?:string}[]}){
 const[board,setBoard]=useState<Board>(),[table,setTable]=useState<Table>(),[replay,setReplay]=useState<any>(),[recap,setRecap]=useState<any>(),[canon,setCanon]=useState<any[]>([]),[rehearsal,setRehearsal]=useState<Rehearsal>(),[message,setMessage]=useState(""),[spectator,setSpectator]=useState(""),[canonKey,setCanonKey]=useState("first-contact"),[canonTitle,setCanonTitle]=useState("First contact established"),[mapActor,setMapActor]=useState(""),[note,setNote]=useState(""),[privateNote,setPrivateNote]=useState(""),[beatTitle,setBeatTitle]=useState("The crew gains an ally"),[beatSummary,setBeatSummary]=useState("The negotiation changes the situation."),[beatPhase,setBeatPhase]=useState("social");
 const load=async()=>{const results=await Promise.allSettled([api(`/sessions/${sessionId}/exploration`,token),api(`/sessions/${sessionId}/table`,token),api(`/sessions/${sessionId}/replay`,token),api(`/sessions/${sessionId}/recap`,token),api(`/sessions/${sessionId}/canon`,token),gm?api(`/sessions/${sessionId}/rehearsal-report`,token):Promise.resolve(undefined)]);if(results[0].status==="fulfilled")setBoard(results[0].value);else if(!String(results[0].reason).includes("not found"))setMessage(`Exploration: ${String(results[0].reason)}`);if(results[1].status==="fulfilled")setTable(results[1].value);else if(!String(results[1].reason).includes("not found"))setMessage(`Table: ${String(results[1].reason)}`);if(results[2].status==="fulfilled")setReplay(results[2].value);if(results[3].status==="fulfilled")setRecap(results[3].value);if(results[4].status==="fulfilled")setCanon(results[4].value);if(results[5].status==="fulfilled"&&results[5].value)setRehearsal(results[5].value as Rehearsal)};
 useEffect(()=>{void load()},[sessionId,token]);useEffect(()=>{if(!actors.some(actor=>actor.actorId===mapActor))setMapActor(actors[0]?.actorId??"")},[actors,mapActor]);
 useEffect(()=>{const socket=sessionSocket(sessionId,token,event=>{if(["table.state","table.beat","exploration.state","actor.state","session.catchup"].includes(event.type))void load()});return()=>socket.close()},[sessionId,token]);
 const send=async(path:string,method:string,body:any)=>{try{const value=await api(path,token,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage("Saved");await load();return value}catch(error:any){setMessage(error.message)}};
 const extent=useMemo(()=>({width:Math.max(420,...(board?.nodes.map(node=>node.x+90)??[])),height:Math.max(260,...(board?.nodes.map(node=>node.y+70)??[]))}),[board]);
 const actorName=(id:string)=>actors.find(actor=>actor.actorId===id)?.label??(id===mapActor?"Selected actor":"Token");
 return <article className="tableConsole"><div className="titleRow"><h3>Table console</h3><button className="secondary" onClick={()=>void load()}>Refresh</button></div>{message&&<p className={message==="Saved"?"notice":"error"}>{message}</p>}
  {!table&&gm&&<button onClick={()=>void send(`/sessions/${sessionId}/table`,"POST",{})}>PREPARE TABLE</button>}
  {table&&<section className="tableState"><div className="titleRow"><div><small>Current pace</small><h3>{table.phase.toUpperCase()}</h3></div><b>revision {table.revision}</b></div>{gm&&<div className="phaseRail">{["setup","exploration","social","encounter","reward","epilogue"].map(phase=><button key={phase} className={table.phase===phase?"selected secondary":"secondary"} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,phase})}>{phase}</button>)}</div>}
   <h4>Scenes</h4><div className="sceneRail">{table.scenes.map(scene=><button key={scene.id} className={`${scene.status} secondary`} disabled={!gm} onClick={()=>gm&&void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,activeSceneId:scene.id})}><b>{scene.title}</b><small>{scene.status}</small></button>)}</div>
   {table.activeSceneId&&<p>Active scene: <b>{table.scenes.find(scene=>scene.id===table.activeSceneId)?.title}</b></p>}
   <h4>Shared table notes</h4>{table.sharedNotes.length?table.sharedNotes.slice(-8).map((value,index)=><p className="tableNote" key={index}>{value}</p>):<p className="muted">No shared notes yet.</p>}
   {gm&&<><div className="noteGrid"><label>Shared note<textarea rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label><button disabled={!note.trim()} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,sharedNote:note.trim()}).then(()=>setNote(""))}>SHARE NOTE</button><label>GM-only note<textarea rows={2} value={privateNote} onChange={event=>setPrivateNote(event.target.value)}/></label><button className="secondary" disabled={!privateNote.trim()} onClick={()=>void send(`/sessions/${sessionId}/table`,"PATCH",{expectedRevision:table.revision,privateNote:privateNote.trim()}).then(()=>setPrivateNote(""))}>SAVE PRIVATELY</button></div>{table.privateNotes?.length?<details><summary>GM notebook · {table.privateNotes.length}</summary>{table.privateNotes.map((value,index)=><p className="tableNote private" key={index}>{value}</p>)}</details>:null}
    <h4>Record table beat</h4><div className="beatGrid"><select aria-label="Beat phase" value={beatPhase} onChange={event=>setBeatPhase(event.target.value)}>{["exploration","social","encounter","reward","epilogue"].map(value=><option key={value}>{value}</option>)}</select><input aria-label="Beat title" value={beatTitle} onChange={event=>setBeatTitle(event.target.value)}/><input aria-label="Beat summary" value={beatSummary} onChange={event=>setBeatSummary(event.target.value)}/><button disabled={!beatTitle.trim()} onClick={()=>void send(`/sessions/${sessionId}/table/beats`,"POST",{phase:beatPhase,title:beatTitle,summary:beatSummary})}>RECORD BEAT</button></div></>}
  </section>}
  <h4>Exploration map</h4>{!board&&gm&&<button onClick={()=>void send(`/sessions/${sessionId}/exploration`,"POST",{fog:[{id:"opening-fog",label:"Unexplored area",revealed:false,polygon:[[0,0],[220,0],[220,170],[0,170]]}]})}>START EXPLORATION MAP</button>}
  {board&&<><div className="mapToolbar"><span>{board.nodes.length} visible locations · revision {board.revision}</span>{gm&&<label>Move token<select value={mapActor} onChange={event=>setMapActor(event.target.value)}>{actors.map(actor=><option key={actor.actorId} value={actor.actorId}>{actor.label??actor.actorId}</option>)}</select></label>}</div><div className="tableMap" aria-label="Exploration map"><svg viewBox={`0 0 ${extent.width} ${extent.height}`} role="img">{board.fog.filter(fog=>fog.polygon?.length).map(fog=><polygon key={fog.id} points={fog.polygon!.map(point=>point.join(",")).join(" ")} className={fog.revealed?"fog revealed":"fog hidden"}/>)}{board.nodes.map(node=><g key={node.id} className="mapNode" onClick={()=>gm&&mapActor&&void send(`/sessions/${sessionId}/exploration/token`,"PATCH",{expectedRevision:board.revision,actorId:mapActor,nodeId:node.id})}><circle cx={node.x} cy={node.y} r="25"/><text x={node.x} y={node.y+43} textAnchor="middle">{node.label}</text></g>)}{board.tokens.map(token=>{const node=board.nodes.find(value=>value.id===token.nodeId);return node?<g key={token.actorId} className="mapToken"><circle cx={node.x} cy={node.y} r="14"/><text x={node.x} y={node.y+4} textAnchor="middle">{actorName(token.actorId).slice(0,2).toUpperCase()}</text></g>:null})}</svg></div>{gm&&board.fog.map(fog=><div className="compactRow" key={fog.id}><span>{fog.label}</span><b>{fog.revealed?"Revealed":"Hidden"}</b><button className="secondary" onClick={()=>void send(`/sessions/${sessionId}/exploration/fog`,"PATCH",{expectedRevision:board.revision,fog:{...fog,revealed:!fog.revealed,polygon:fog.polygon}})}>{fog.revealed?"Hide":"Reveal"}</button></div>)}</>}
  {gm&&rehearsal&&<section className={rehearsal.gatePassed?"rehearsal passed":"rehearsal"}><div className="titleRow"><h4>M15 rehearsal</h4><b>{rehearsal.gatePassed?"COMPLETE":"IN PROGRESS"}</b></div><div className="stageGrid">{Object.entries(rehearsal.stages).map(([name,stage])=><span className={stage.passed?"done":""} key={name}>{stage.passed?"✓":"○"} {name} · {stage.count}</span>)}</div>{rehearsal.missing.length>0&&<small>Still needed: {rehearsal.missing.join(", ")}</small>}</section>}
  {gm&&<><button className="secondary" onClick={async()=>{const value=await send(`/sessions/${sessionId}/spectators`,"POST",{label:"Shared spectator"});if(value)setSpectator(value.accessToken)}}>CREATE SPECTATOR ACCESS</button>{spectator&&<p><small>Read-only spectator token</small><code>{spectator}</code></p>}<div className="actions"><input value={canonKey} onChange={e=>setCanonKey(e.target.value)} aria-label="Canon key"/><input value={canonTitle} onChange={e=>setCanonTitle(e.target.value)} aria-label="Canon title"/><button onClick={()=>void send(`/sessions/${sessionId}/canon`,"POST",{key:canonKey,title:canonTitle,value:{established:true}})}>PROMOTE TO REALM CANON</button></div></>}
  <details><summary>History, recap and canon</summary><h4>Realm canon</h4>{canon.length?canon.map(fact=><div className="compactRow" key={fact.key}><b>{fact.title}</b><small>v{fact.revision}</small></div>):<p className="muted">No shared facts yet.</p>}<h4>Campaign recap</h4>{recap?.entries?.length?recap.entries.slice(-8).map((entry:any)=><div className="compactRow" key={entry.sequence}><span>#{entry.sequence}</span><small>{entry.text}</small></div>):<p className="muted">No recap entries yet.</p>}<h4>Replay timeline</h4><p className="muted">{replay?.events?.length??0} authoritative events</p>{replay?.events?.slice(-12).map((event:any)=><div className="compactRow" key={event.id??event.sequence}><b>#{event.sequence}</b><span>{event.type}</span><small>{event.createdAt?new Date(event.createdAt).toLocaleTimeString():""}</small></div>)}</details>
 </article>
}
