import {useContentI18n} from './i18n/content-react.js';
import React, { useMemo, useState } from "react";

type Entry = { id: string; name: string; description: string; patternIds: string[]; relations: Array<{ type: string; targetId: string }>; localeKey: string };
type Profile = { id?:string; patterns: Array<{ id: string; name: string }>; campaignKits: Array<{ id: string; name: string; summary: string; durationMinutes: { min: number; max: number }; playerCount: { min: number; max: number }; patternIds: string[]; openingSceneId: string; sceneIds: string[]; npcIds: string[]; locationIds: string[]; rewardIds: string[]; gmGuidance: string[]; readyCharacterIds: string[] }>; content: Record<string, Entry[]>; localization: { sourceLocale: string; supportedLocales: string[]; strings: Record<string, Record<string, string>> } };
type Assessment = { passed: boolean; counts: Record<string, { actual: number; required: number }>; diagnostics: Array<{ severity: "error" | "warning"; code: string; path: string; message: string }> };

export function filterDeepUniverseContent(profile: Profile, patternId: string, kind: string) {
  return Object.entries(profile.content).flatMap(([entryKind, entries]) => (!kind || entryKind === kind ? entries.map(entry => ({ ...entry, kind: entryKind })) : [])).filter(entry => !patternId || entry.patternIds.includes(patternId));
}

export function deepUniverseGraphSummary(profile: Profile) {
  const entries = Object.values(profile.content).flat(), core = ["factions", "npcs", "locations"].flatMap(kind => profile.content[kind] ?? []);
  return { nodes: entries.length, relations: entries.reduce((sum, entry) => sum + entry.relations.length, 0), disconnectedCore: core.filter(entry => entry.relations.length === 0).length };
}

export function localeCoverage(profile: Profile) {
  const keys = [...new Set(Object.values(profile.content).flat().map(entry => entry.localeKey))];
  return profile.localization.supportedLocales.map(locale => { const translated = keys.filter(key => profile.localization.strings[locale]?.[key]?.trim()).length; return { locale, translated, total: keys.length, missing: keys.length - translated }; });
}

export function DeepUniverseDashboard({ document, assessment, draft, canPublish, onAssess, onDiagnostic, initialPattern = "", initialKind = "", initialKitId = "" }: { document: { universe?: Profile }; assessment?: Assessment; draft: boolean; canPublish: boolean; onAssess?: () => void; onDiagnostic?: (path: string) => void; initialPattern?: string; initialKind?: string; initialKitId?: string }) {
  const profile = document.universe, [pattern, setPattern] = useState(initialPattern), [kind, setKind] = useState(initialKind), [kitId, setKitId] = useState(initialKitId);
  const {c}=useContentI18n({universe:profile});
  const entries = useMemo(() => profile ? filterDeepUniverseContent(profile, pattern, kind) : [], [profile, pattern, kind]), graph = profile ? deepUniverseGraphSummary(profile) : undefined, locales = profile ? localeCoverage(profile) : [], kit = profile?.campaignKits.find(value => value.id === kitId);
  if (!profile) return <section className="deepUniverseDashboard"><h2>{c("Deep Universe completeness")}</h2><p>{c("This Pack does not participate in the optional Deep Universe standard. It can still be validated and published normally.")}</p>{draft && <p>{c("Use the Source tab to add a declarative")}<code>universe</code>{c("profile.")}</p>}</section>;
  return <section className="deepUniverseDashboard">
    <div className="titleRow"><div><h2>{c("Deep Universe completeness")}</h2><p className="muted">{c("Standard v1 checks content depth, references, game rules, media, relationships and locales.")}</p></div>{onAssess && <button className="secondary" onClick={onAssess}>{c("Refresh quality report")}</button>}</div>
    <p className={assessment?.passed && canPublish ? "notice" : "error"}>{assessment?.passed && canPublish ? c("Preview and publication ready") : c("Preview and publication blocked")}</p>{draft && <p className="notice">{c("Draft editing remains available.")}</p>}
    <div className="deepCountGrid">{Object.entries(assessment?.counts ?? {}).map(([name, count]) => <article id={`deep-${name}`} key={name}><small>{c(name)}</small><strong>{count.actual} / {count.required}</strong><progress max={count.required} value={Math.min(count.actual, count.required)}/></article>)}</div>
    <div className="deepColumns"><article><h3>{c("Blocking diagnostics")}</h3>{assessment?.diagnostics.length ? assessment.diagnostics.map((diagnostic, index) => <button type="button" className={`deepDiagnostic ${diagnostic.severity}`} onClick={() => onDiagnostic?.(diagnostic.path)} key={`${diagnostic.code}-${diagnostic.path}-${index}`}><b>{diagnostic.code}</b><span>{diagnostic.message}</span><code>{diagnostic.path}</code></button>) :<p>{c("No quality diagnostics.")}</p>}</article><article><h3>{c("Relationship graph")}</h3><dl><div><dt>{c("Nodes")}</dt><dd>{graph?.nodes}</dd></div><div><dt>{c("Relations")}</dt><dd>{graph?.relations}</dd></div><div><dt>{c("Disconnected core")}</dt><dd>{graph?.disconnectedCore}</dd></div></dl></article></div>
    <article><h3>{c("Pack name translations")}</h3><div className="localeCoverage">{locales.map(locale => <div key={locale.locale}><b>{locale.locale}</b><span>{locale.translated} / {locale.total}</span><small>{locale.missing} {c("missing")}</small></div>)}</div></article>
    <article><h3>{c("Content inspector")}</h3><div className="deepFilters"><label>{c("Pattern")}<select value={pattern} onChange={event => setPattern(event.target.value)}><option value="">{c("All patterns")}</option>{profile.patterns.map(value => <option value={value.id} key={value.id}>{c(value.name)}</option>)}</select></label><label>{c("Type")}<select value={kind} onChange={event => setKind(event.target.value)}><option value="">{c("All types")}</option>{Object.keys(profile.content).map(value => <option key={value} value={value}>{c(value)}</option>)}</select></label></div><p>{entries.length} {c("matching entries")}</p><div className="deepEntryList">{entries.map(entry => <details key={`${entry.kind}-${entry.id}`}><summary><b>{c(entry.name,undefined,entry.localeKey)}</b> <small>{c(entry.kind)} · {entry.id}</small></summary><p>{c(entry.description)}</p><code>{entry.relations.map(relation => `${relation.type} → ${relation.targetId}`).join(" · ") || c("no relationships")}</code></details>)}</div></article>
    <article><h3>{c("Campaign Kit preview")}</h3><label>{c("Campaign Kit")}<select value={kitId} onChange={event => setKitId(event.target.value)}><option value="">{c("Choose a kit")}</option>{profile.campaignKits.filter(value => !pattern || value.patternIds.includes(pattern)).map(value => <option value={value.id} key={value.id}>{c(value.name)}</option>)}</select></label>{kit && <div className="campaignKitPreview"><h4>{c(kit.name)}</h4><p>{c(kit.summary)}</p><p><span className="tag">{kit.durationMinutes.min}–{kit.durationMinutes.max} {c("minutes")}</span><span className="tag">{kit.playerCount.min}–{kit.playerCount.max} {c("players")}</span></p><dl><div><dt>{c("Opening")}</dt><dd><code>{kit.openingSceneId}</code></dd></div><div><dt>{c("Scenes")}</dt><dd>{kit.sceneIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>{c("Cast")}</dt><dd>{kit.npcIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>{c("Locations")}</dt><dd>{kit.locationIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>{c("Rewards")}</dt><dd>{kit.rewardIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>{c("Ready characters")}</dt><dd>{kit.readyCharacterIds.map(id => <code key={id}>{id} </code>)}</dd></div></dl><h4>{c("GM guidance")}</h4><ol>{kit.gmGuidance.map(value => <li key={value}>{c(value)}</li>)}</ol></div>}</article>
  </section>;
}
