import React, { useMemo, useState } from "react";

type Entry = { id: string; name: string; description: string; patternIds: string[]; relations: Array<{ type: string; targetId: string }>; localeKey: string };
type Profile = { patterns: Array<{ id: string; name: string }>; campaignKits: Array<{ id: string; name: string; summary: string; durationMinutes: { min: number; max: number }; playerCount: { min: number; max: number }; patternIds: string[]; openingSceneId: string; sceneIds: string[]; npcIds: string[]; locationIds: string[]; rewardIds: string[]; gmGuidance: string[]; readyCharacterIds: string[] }>; content: Record<string, Entry[]>; localization: { sourceLocale: string; supportedLocales: string[]; strings: Record<string, Record<string, string>> } };
type Assessment = { passed: boolean; counts: Record<string, { actual: number; required: number }>; diagnostics: Array<{ severity: "error" | "warning"; code: string; path: string; message: string }> };

export function filterDeepUniverseContent(profile: Profile, patternId: string, kind: string) {
  return Object.entries(profile.content).flatMap(([entryKind, entries]) => (!kind || entryKind === kind ? entries.map(entry => ({ ...entry, kind: entryKind })) : [])).filter(entry => !patternId || entry.patternIds.includes(patternId));
}

export function deepUniverseGraphSummary(profile: Profile) {
  const entries = Object.values(profile.content).flat(), core = ["factions", "npcs", "locations"].flatMap(kind => profile.content[kind] ?? []);
  return { nodes: entries.length, relations: entries.reduce((sum, entry) => sum + entry.relations.length, 0), disconnectedCore: core.filter(entry => entry.relations.length === 0).length };
}

export function localeCoverage(profile: Profile) {
  const keys = [...new Set(Object.values(profile.content).flat().map(entry => entry.localeKey))];
  return profile.localization.supportedLocales.map(locale => { const translated = keys.filter(key => profile.localization.strings[locale]?.[key]?.trim()).length; return { locale, translated, total: keys.length, missing: keys.length - translated }; });
}

export function DeepUniverseDashboard({ document, assessment, draft, canPublish, onAssess, initialPattern = "", initialKind = "", initialKitId = "" }: { document: { universe?: Profile }; assessment?: Assessment; draft: boolean; canPublish: boolean; onAssess?: () => void; initialPattern?: string; initialKind?: string; initialKitId?: string }) {
  const profile = document.universe, [pattern, setPattern] = useState(initialPattern), [kind, setKind] = useState(initialKind), [kitId, setKitId] = useState(initialKitId);
  const entries = useMemo(() => profile ? filterDeepUniverseContent(profile, pattern, kind) : [], [profile, pattern, kind]), graph = profile ? deepUniverseGraphSummary(profile) : undefined, locales = profile ? localeCoverage(profile) : [], kit = profile?.campaignKits.find(value => value.id === kitId);
  if (!profile) return <section className="deepUniverseDashboard"><h2>Deep Universe completeness</h2><p className="error">This Pack has no Deep Universe profile. Add the declarative <code>universe</code> document before preview or publication.</p>{draft && <p>Draft editing remains available.</p>}</section>;
  return <section className="deepUniverseDashboard">
    <div className="titleRow"><div><h2>Deep Universe completeness</h2><p className="muted">Standard v1 checks content depth, references, game rules, media, relationships and locales.</p></div>{onAssess && <button className="secondary" onClick={onAssess}>Refresh quality report</button>}</div>
    <p className={assessment?.passed && canPublish ? "notice" : "error"}>{assessment?.passed && canPublish ? "Preview and publication ready" : "Preview and publication blocked"}</p>{draft && <p className="notice">Draft editing remains available.</p>}
    <div className="deepCountGrid">{Object.entries(assessment?.counts ?? {}).map(([name, count]) => <article id={`deep-${name}`} key={name}><small>{name}</small><strong>{count.actual} / {count.required}</strong><progress max={count.required} value={Math.min(count.actual, count.required)}/></article>)}</div>
    <div className="deepColumns"><article><h3>Blocking diagnostics</h3>{assessment?.diagnostics.length ? assessment.diagnostics.map((diagnostic, index) => <a className={`deepDiagnostic ${diagnostic.severity}`} href={`#deep-${diagnostic.path.split(".").at(-1)}`} key={`${diagnostic.code}-${diagnostic.path}-${index}`}><b>{diagnostic.code}</b><span>{diagnostic.message}</span><code>{diagnostic.path}</code></a>) : <p>No quality diagnostics.</p>}</article><article><h3>Relationship graph</h3><dl><div><dt>Nodes</dt><dd>{graph?.nodes}</dd></div><div><dt>Relations</dt><dd>{graph?.relations}</dd></div><div><dt>Disconnected core</dt><dd>{graph?.disconnectedCore}</dd></div></dl></article></div>
    <article><h3>Locale coverage</h3><div className="localeCoverage">{locales.map(locale => <div key={locale.locale}><b>{locale.locale}</b><span>{locale.translated} / {locale.total}</span><small>{locale.missing} missing</small></div>)}</div></article>
    <article><h3>Content inspector</h3><div className="deepFilters"><label>Pattern<select value={pattern} onChange={event => setPattern(event.target.value)}><option value="">All patterns</option>{profile.patterns.map(value => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label><label>Type<select value={kind} onChange={event => setKind(event.target.value)}><option value="">All types</option>{Object.keys(profile.content).map(value => <option key={value}>{value}</option>)}</select></label></div><p>{entries.length} matching entries</p><div className="deepEntryList">{entries.map(entry => <details key={`${entry.kind}-${entry.id}`}><summary><b>{entry.name}</b> <small>{entry.kind} · {entry.id}</small></summary><p>{entry.description}</p><code>{entry.relations.map(relation => `${relation.type} → ${relation.targetId}`).join(" · ") || "no relationships"}</code></details>)}</div></article>
    <article><h3>Campaign Kit preview</h3><label>Campaign Kit<select value={kitId} onChange={event => setKitId(event.target.value)}><option value="">Choose a kit</option>{profile.campaignKits.filter(value => !pattern || value.patternIds.includes(pattern)).map(value => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label>{kit && <div className="campaignKitPreview"><h4>{kit.name}</h4><p>{kit.summary}</p><p><span className="tag">{kit.durationMinutes.min}–{kit.durationMinutes.max} minutes</span><span className="tag">{kit.playerCount.min}–{kit.playerCount.max} players</span></p><dl><div><dt>Opening</dt><dd><code>{kit.openingSceneId}</code></dd></div><div><dt>Scenes</dt><dd>{kit.sceneIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>Cast</dt><dd>{kit.npcIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>Locations</dt><dd>{kit.locationIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>Rewards</dt><dd>{kit.rewardIds.map(id => <code key={id}>{id} </code>)}</dd></div><div><dt>Ready characters</dt><dd>{kit.readyCharacterIds.map(id => <code key={id}>{id} </code>)}</dd></div></dl><h4>GM guidance</h4><ol>{kit.gmGuidance.map(value => <li key={value}>{value}</li>)}</ol></div>}</article>
  </section>;
}
