import React,{useEffect,useState}from"react";
import{sessionSocket}from"./session-client.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
async function call(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,init),x=await r.json();if(!r.ok)throw Error(x.message??`HTTP ${r.status}`);return x}
const post=(p:string,b:any={},token:string)=>call(p,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(b)});
const gmPost=(p:string,b:any,gmToken:string)=>call(p,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${gmToken}`},body:JSON.stringify(b)});
export function GmGame({session,participants,gmToken}:{session:any;participants:any[];gmToken:string}){
 const[defs,setDefs]=useState<any>({checks:{},actions:{}}),[participantId,setParticipant]=useState(""),[targetId,setTarget]=useState(""),[checkId,setCheck]=useState(""),[difficulty,setDifficulty]=useState(14),[events,setEvents]=useState<any[]>([]),[actors,setActors]=useState<any[]>([]),[actionId,setAction]=useState("");
 const refresh=async()=>{setEvents(await call(`/sessions/${session.id}/events`,{headers:{authorization:`Bearer ${gmToken}`}}));setActors(await call(`/sessions/${session.id}/actors`,{headers:{authorization:`Bearer ${gmToken}`}}))};
 useEffect(()=>{call("/game/definitions").then(x=>{setDefs(x);setCheck(Object.keys(x.checks)[0]??"");setAction(Object.keys(x.actions)[0]??"")});refresh()},[session.id]);
 useEffect(()=>{const ws=sessionSocket(session.id,gmToken,e=>{if(["check.requested","check.resolved","actor.state","action.resolved","encounter.state"].includes(e.type))void refresh()});return()=>ws.close()},[session.id]);
 useEffect(()=>{if(!participantId&&participants[0])setParticipant(participants[0].id);if(!targetId&&participants[0])setTarget(participants[0].id)},[participants]);
 async function initialize(){for(const p of participants)if(!actors.some(a=>a.actorId===p.id))await gmPost(`/sessions/${session.id}/participants/${p.id}/initialize`,{},gmToken);await refresh()}
 async function sendCheck(){await gmPost(`/sessions/${session.id}/checks`,{participantId,checkId,difficulty,visibility:"full"},gmToken);await refresh()}
 async function action(){const definition=defs.actions[actionId],ids=definition?.target==="none"?[]:definition?.target==="self"?[participantId]:[targetId];await gmPost(`/sessions/${session.id}/actions`,{actorId:participantId,targetActorIds:ids,actionId,inputs:{difficulty}},gmToken);await refresh()}
 return <section><h2>GAME LIVE</h2><button className="secondary" onClick={initialize}>Initialize party runtime</button><h3>Party runtime</h3>{participants.map(p=>{const a=actors.find(x=>x.actorId===p.id);return <article key={p.id}><h3>{p.displayName}</h3>{a?Object.entries(a.resources).map(([k,v])=><div className="row" key={k}><b>{k}</b><span>{String(v)}</span></div>):<p className="muted">not initialized</p>}{a?.effects?.map((e:any)=><small key={e.id}>Effect: {e.definitionId}{e.remaining!==undefined?` (${e.remaining})`:""}</small>)}</article>})}
 <h3>Request check</h3><label>Player<select value={participantId} onChange={e=>setParticipant(e.target.value)}>{participants.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label>Check<select value={checkId} onChange={e=>setCheck(e.target.value)}>{Object.entries(defs.checks).map(([id,c]:any)=><option key={id} value={id}>{c.label}</option>)}</select></label><label>Difficulty<input type="number" value={difficulty} onChange={e=>setDifficulty(Number(e.target.value))}/></label><button onClick={sendCheck}>SEND CHECK</button>
 <h3>Action</h3><label>Action<select value={actionId} onChange={e=>setAction(e.target.value)}>{Object.entries(defs.actions).map(([id,a]:any)=><option key={id} value={id}>{a.label}</option>)}</select></label><label>Target<select value={targetId} onChange={e=>setTarget(e.target.value)}>{participants.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><button onClick={action}>APPLY ACTION</button>
 <h3>Game log</h3>{events.slice(-15).reverse().map(e=><div className="row" key={e.id}><b>#{e.sequence} {e.type}</b><small>{new Date(e.createdAt).toLocaleTimeString()}</small></div>)}</section>
}
export function PlayerGame({session,participant}:{session:any;participant:any}){
 const[pending,setPending]=useState<any[]>([]),[last,setLast]=useState<any>(),[actor,setActor]=useState<any>();
 async function refresh(){setPending(await call(`/sessions/${session.id}/participants/${participant.id}/checks`,{headers:{authorization:`Bearer ${participant.accessToken}`}}));const a=await call(`/sessions/${session.id}/actors`,{headers:{authorization:`Bearer ${participant.accessToken}`}});setActor(a.find((x:any)=>x.actorId===participant.id))}
 useEffect(()=>{refresh()},[session.id,participant.id]);
 useEffect(()=>{const ws=sessionSocket(session.id,participant.accessToken,e=>{if(["check.requested","check.resolved","actor.state","action.resolved","encounter.state"].includes(e.type))void refresh()});return()=>ws.close()},[session.id,participant.id]);
 async function roll(c:any){const r=await post(`/checks/${c.request.id}/roll`,{},participant.accessToken);setLast({request:c.request,resolution:r});await refresh()}
 const current=pending.find(x=>!x.resolution);
 return <section><h2>GAME LIVE</h2>{actor&&<article><h3>Resources</h3>{Object.entries(actor.resources).map(([k,v])=><div className="row" key={k}><b>{k}</b><span>{String(v)}</span></div>)}{actor.effects?.map((e:any)=><small key={e.id}>{e.definitionId}{e.remaining!==undefined?` · ${e.remaining} turns`:""}</small>)}</article>}{current?<article><h3>{current.request.checkId.toUpperCase()}</h3><p>Difficulty: <b>{current.request.difficulty}</b></p><button onClick={()=>roll(current)}>🎲 ROLL</button></article>:<p className="muted">Waiting for the GM…</p>}{last&&<article><h3>{last.resolution.outcome.toUpperCase()}</h3><div className="bigRoll">{last.resolution.total}</div><p>Dice {last.resolution.roll.total} + modifier {last.resolution.modifier}</p></article>}<button className="secondary" onClick={refresh}>Refresh state</button></section>
}
