import {useContentI18n} from './i18n/content-react.js';
import React, { useEffect, useMemo, useState } from "react";

type Scalar = string | number | boolean;
type Parameter =
  | { type: "string"; required?: boolean; default?: string; options?: string[] }
  | { type: "number"; required?: boolean; default?: number; min?: number; max?: number }
  | { type: "boolean"; required?: boolean; default?: boolean };
type Fragment = { id: string; version: string; name: string; description?: string; provides: string[]; requires: string[]; conflicts: string[]; parameters: Record<string, Parameter>; asset?: { type: string; tags: string[]; preview: { summary: string; highlights: string[] }; compatibility: { basePackIds: string[] }; dependencies: { id: string; version: string }[]; license: { spdx: string; attribution: string; source: string }; counts: Record<string, number>; media: { name: string; role: string; mediaType: string; checksum: string; size: number }[]; contentChecksum: string } };
type Selection = { fragmentId: string; version: string; parameters: Record<string, Scalar> };
type Report = { valid: boolean; diagnostics: { code: string; path: string; message: string }[]; providedCapabilities: string[]; writes: string[] };
type Project = { id: string; name: string; revision: number; seed: string; selections: Selection[]; decisions: Record<string, Scalar>; locks: string[]; compiled: { manifest: { id: string; version: string } }; report: Report };
type Question = { id: string; label: string; default: string; options: { value: string; label: string }[] };

interface Props {
  request: (path: string, init?: RequestInit) => Promise<any>;
  requestMedia: (path: string) => Promise<Blob>;
  pack: { universe?:import("./i18n/content.js").ContentPack["universe"]; manifest: { id: string; version: string }; questions: Question[] };
  onWorld: (world: any) => Promise<void> | void;
  onBack: () => void;
  onFork?: (project: any) => void;
}

function defaults(fragment: Fragment) {
  return Object.fromEntries(Object.entries(fragment.parameters).flatMap(([key, definition]) => definition.default === undefined ? [] : [[key, definition.default]]));
}

function AssetPreview({ fragment, requestMedia }: { fragment: Fragment; requestMedia: Props["requestMedia"] }) {
 const{c}=useContentI18n();
  const media = fragment.asset?.media[0], [url, setUrl] = useState("");
  useEffect(() => { let active = true, objectUrl = ""; if (media) void requestMedia(`/game-assets/media/${media.checksum}/${media.name.split("/").map(encodeURIComponent).join("/")}`).then(blob => { objectUrl = URL.createObjectURL(blob); if (active) setUrl(objectUrl); else URL.revokeObjectURL(objectUrl); }); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [media?.checksum, media?.name]);
  return url ? <img className="assetPreview" src={url} alt={`${c(fragment.name)} preview`}/> : null;
}

export function GameDescriptorBuilder({ request, requestMedia, pack, onWorld, onBack, onFork }: Props) {
 const{c}=useContentI18n(pack);
  const [fragments, setFragments] = useState<Fragment[]>([]), [projects, setProjects] = useState<Project[]>([]);
  const [project, setProject] = useState<Project | null>(null), [name, setName] = useState<string | undefined>(), [seed, setSeed] = useState("masterhost-game"), [selections, setSelections] = useState<Selection[]>([]);
  const resolvedName=name??c("Untitled One-shot");
  const [decisions, setDecisions] = useState<Record<string, Scalar>>(() => Object.fromEntries(pack.questions.map(question => [question.id, question.default]))), [locks, setLocks] = useState<string[]>([]);
  const [search, setSearch] = useState(""), [assetType, setAssetType] = useState("all"), [assetTag, setAssetTag] = useState("all"), [preview, setPreview] = useState<{ document: Project["compiled"]; report: Report } | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false);

  const loadProject = (next: Project) => {
    setProject(next); setName(next.name); setSeed(next.seed); setSelections(structuredClone(next.selections)); setDecisions(structuredClone(next.decisions)); setLocks([...next.locks]); setPreview(null); setDirty(false); setError("");
  };
  useEffect(() => { void Promise.all([request("/game-fragments"), request(`/game-assets?basePackId=${encodeURIComponent(pack.manifest.id)}`), request("/game-descriptors")]).then(([catalog, assets, saved]: [Fragment[], any[], Project[]]) => { const enriched = assets.map(asset => ({ ...asset.fragment, name: asset.name, description: asset.description, asset: { type: asset.type, tags: asset.tags, preview: asset.preview, compatibility: asset.compatibility, dependencies: asset.dependencies, license: asset.license, counts: asset.counts, media: asset.media, contentChecksum: asset.contentChecksum } })); setFragments([...catalog.filter(fragment => !enriched.some((asset: Fragment) => asset.id === fragment.id && asset.version === fragment.version)), ...enriched]); setProjects(saved); if (saved[0]) loadProject(saved[0]); }).catch((reason: Error) => setError(reason.message)); }, []);

  const assetTypes = useMemo(() => [...new Set(fragments.flatMap(fragment => fragment.asset ? [fragment.asset.type] : []))].sort(), [fragments]);
  const assetTags = useMemo(() => [...new Set(fragments.flatMap(fragment => fragment.asset?.tags ?? []))].sort(), [fragments]);
  const visible = useMemo(() => fragments.filter(fragment => assetType === "all" || fragment.asset?.type === assetType).filter(fragment => assetTag === "all" || fragment.asset?.tags.includes(assetTag)).filter(fragment => `${c(fragment.name)} ${fragment.description ?? ""} ${fragment.provides.join(" ")} ${fragment.asset?.tags.join(" ") ?? ""}`.toLowerCase().includes(search.toLowerCase())), [fragments, search, assetType, assetTag,c]);
  const selected = (fragment: Pick<Fragment, "id" | "version">) => selections.find(value => value.fragmentId === fragment.id && value.version === fragment.version);
  const change = (next: Selection[]) => { setSelections(next); setPreview(null); setDirty(true); };
  const toggle = (fragment: Fragment) => {
    const current = selected(fragment);
    if (current) { const removed = new Set([fragment.id]); let changed = true; while (changed) { changed = false; for (const candidate of fragments) if (candidate.asset?.dependencies.some(dependency => removed.has(dependency.id)) && !removed.has(candidate.id)) { removed.add(candidate.id); changed = true; } } change(selections.filter(value => !removed.has(value.fragmentId))); return; }
    const additions: Selection[] = [], included = new Set(selections.map(value => `${value.fragmentId}@${value.version}`));
    const include = (candidate: Fragment) => { for (const dependency of candidate.asset?.dependencies ?? []) { const required = fragments.find(value => value.id === dependency.id && value.version === dependency.version); if (required) include(required); } const identity = `${candidate.id}@${candidate.version}`; if (!included.has(identity)) { additions.push({ fragmentId: candidate.id, version: candidate.version, parameters: defaults(candidate) }); included.add(identity); } };
    include(fragment); change([...selections, ...additions]);
  };
  const setParameter = (fragmentId: string, key: string, value: Scalar) => change(selections.map(selection => selection.fragmentId === fragmentId ? { ...selection, parameters: { ...selection.parameters, [key]: value } } : selection));
  const payload = () => ({ name: resolvedName.trim(), seed: seed.trim(), basePack: pack.manifest, selections, decisions, locks });
  const run = async (action: () => Promise<void>) => { try { setBusy(true); setError(""); await action(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const save = async () => run(async () => {
    const next = await request(project ? `/game-descriptors/${project.id}` : "/game-descriptors", { method: project ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(project ? { ...payload(), expectedRevision: project.revision } : payload()) }) as Project;
    setProjects(current => [next, ...current.filter(value => value.id !== next.id)]); loadProject(next);
  });
  const inspect = async () => run(async () => { const prospective = !project || dirty; setPreview(await request(project ? `/game-descriptors/${project.id}/preview` : "/game-descriptors/preview", { method: "POST", ...(prospective ? { headers: { "content-type": "application/json" }, body: JSON.stringify(payload()) } : {}) })); });
  const compile = async () => run(async () => { if (!project || dirty) throw Error("Save the project before compiling it"); await onWorld(await request(`/game-descriptors/${project.id}/compile`, { method: "POST" })); });
  const fork = async () => run(async () => { if (!project || dirty) throw Error("Save the project before forking it"); const id = prompt("Custom Pack ID", `masterhost.custom.${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`); if (!id) return; const name = prompt("Custom Pack name", `${project.name} Custom`); if (!name) return; const forked = await request(`/game-descriptors/${project.id}/fork-pack`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, name, version: "0.1.0" }) }); onFork?.(forked); });

  const groupedDiagnostics = (preview?.report.diagnostics ?? []).reduce<Record<string, Report["diagnostics"]>>((groups, diagnostic) => { (groups[diagnostic.code] ??= []).push(diagnostic); return groups; }, {});
  return <main className="gameDescriptorBuilder">
    <div className="titleRow"><div><h1>{c("DYNAMIC GAME BUILDER")}</h1><p className="muted">{c("Choose Pack fragments explicitly. MasterHost composes a versioned game Descriptor.")}</p></div><button className="secondary" onClick={onBack}>{c("Back")}</button></div>
    {error && <p className="error">{error}</p>}
    {projects.length > 0 && <section><h2>{c("Saved games")}</h2><div className="actions">{projects.map(saved => <button key={saved.id} className={project?.id === saved.id ? "selected" : "secondary"} onClick={() => loadProject(saved)}>{saved.name} {c("· r")}{saved.revision}</button>)}</div><button className="secondary" onClick={() => { setProject(null); setName(undefined); setSeed("masterhost-game"); setSelections([]); setDecisions(Object.fromEntries(pack.questions.map(question => [question.id, question.default]))); setLocks([]); setPreview(null); setDirty(false); }}>{c("New game")}</button></section>}
    <section><h2>{c("Game identity")}</h2><label>{c("Game name")}<input aria-label={c("Game name")} value={resolvedName} onChange={event => { setName(event.target.value); setDirty(true); }}/></label><label>{c("Deterministic seed")}<input aria-label={c("Deterministic seed")} value={seed} onChange={event => { setSeed(event.target.value); setDirty(true); }}/></label><p className="muted">{c("Base Pack ·")} <code>{pack.manifest.id}@{pack.manifest.version}</code></p></section>
    <section><div className="titleRow"><div><h2>{c("Asset library")}</h2><p className="muted">{c("Selected assets and fragments ·")} {selections.length}</p></div><div><input aria-label={c("Search assets")} placeholder={c("Search assets")} value={search} onChange={event => setSearch(event.target.value)}/><select aria-label={c("Asset type")} value={assetType} onChange={event => setAssetType(event.target.value)}><option value="all">{c("All asset types")}</option>{assetTypes.map(value => <option key={value} value={value}>{c(value)}</option>)}</select><select aria-label={c("Asset tag")} value={assetTag} onChange={event => setAssetTag(event.target.value)}><option value="all">{c("All tags")}</option>{assetTags.map(value => <option key={value} value={value}>{c(value)}</option>)}</select></div></div><div className="fragmentGrid">{visible.map(fragment => <article key={`${fragment.id}@${fragment.version}`}><AssetPreview fragment={fragment} requestMedia={requestMedia}/><h3>{c(fragment.name)}</h3><p>{c(fragment.asset?.preview.summary ?? fragment.description)}</p>{fragment.asset && <><p>{fragment.asset.preview.highlights.map(value => <span className="tag" key={value}>{c(value)}</span>)}</p><small>{c(fragment.asset.type)} · {fragment.asset.tags.map(value=>c(value)).join(" · ")}</small><small>{c("Compatible Packs ·")} {fragment.asset.compatibility.basePackIds.join(" · ")}</small><small>{c("Content ·")} {Object.entries(fragment.asset.counts).filter(([, value]) => value > 0).map(([key, value]) => `${value} ${key}`).join(" · ") || "metadata"}</small><small>{c("License ·")} {fragment.asset.license.spdx} · {fragment.asset.license.attribution}</small><small>{c("Source ·")} {fragment.asset.license.source}</small><small>{c("Dependencies ·")} {fragment.asset.dependencies.map(value => `${value.id}@${value.version}`).join(" · ") || "none"}</small><small>{c("Checksum ·")} {fragment.asset.contentChecksum.slice(0, 12)}</small></>}<small>{c("Provides ·")} {fragment.provides.join(" · ") || "none"}</small><small>{c("Requires ·")} {fragment.requires.join(" · ") || "none"}</small><small>{c("Conflicts ·")} {fragment.conflicts.join(" · ") || "none"}</small><button data-fragment-id={fragment.id} className={selected(fragment) ? "selected" : "secondary"} onClick={() => toggle(fragment)}>{selected(fragment) ? "SELECTED" : "SELECT"}</button></article>)}</div></section>
    {selections.length > 0 && <section><h2>{c("Composition order")}</h2>{selections.map((selection, index) => { const fragment = fragments.find(value => value.id === selection.fragmentId); return <div className="compactRow" key={selection.fragmentId}><b>{index + 1}. {fragment ? c(fragment.name) : selection.fragmentId}</b><code>{selection.version}</code></div>; })}</section>}
    {selections.map(selection => { const fragment = fragments.find(value => value.id === selection.fragmentId); if (!fragment) return null; return <section key={selection.fragmentId}><h2>{c(fragment.name)} {c("parameters")}</h2>{Object.entries(fragment.parameters).map(([key, definition]) => <label key={key}>{key}{definition.type === "boolean" ? <input aria-label={`Parameter ${key}`} type="checkbox" checked={Boolean(selection.parameters[key])} onChange={event => setParameter(fragment.id, key, event.target.checked)}/> : definition.type === "string" && definition.options ? <select aria-label={`Parameter ${key}`} value={String(selection.parameters[key] ?? "")} onChange={event => setParameter(fragment.id, key, event.target.value)}>{definition.options.map(option => <option key={option} value={option}>{c(option)}</option>)}</select> : <input aria-label={`Parameter ${key}`} type={definition.type === "number" ? "number" : "text"} min={definition.type === "number" ? definition.min : undefined} max={definition.type === "number" ? definition.max : undefined} value={String(selection.parameters[key] ?? "")} onChange={event => setParameter(fragment.id, key, definition.type === "number" ? Number(event.target.value) : event.target.value)}/>}</label>)}</section>; })}
    {pack.questions.length > 0 && <section><h2>{c("World decisions")}</h2>{pack.questions.map(question => <div key={question.id}><label>{c(question.label)}<select value={String(decisions[question.id] ?? question.default)} onChange={event => { setDecisions(current => ({ ...current, [question.id]: event.target.value })); setDirty(true); }}>{question.options.map(option => <option key={option.value} value={option.value}>{c(option.label)}</option>)}</select></label><label className="lockChoice">{c("Lock decision")}<input type="checkbox" checked={locks.includes(question.id)} onChange={event => { setLocks(current => event.target.checked ? [...new Set([...current, question.id])] : current.filter(value => value !== question.id)); setDirty(true); }}/></label></div>)}</section>}
    <section className="packActions"><div className="actions"><button disabled={busy || !resolvedName.trim()} onClick={save}>{project ? c("SAVE REVISION") : c("CREATE PROJECT")}</button><button disabled={busy || !resolvedName.trim()} onClick={inspect}>{c("PREVIEW")}</button><button disabled={busy || !project || dirty} onClick={compile}>{c("COMPILE WORLD")}</button>{onFork&&<button className="secondary" disabled={busy || !project || dirty} onClick={fork}>{c("FORK AS FULL CUSTOM PACK")}</button>}</div>{project && <p className="muted">{c("Revision")} {project.revision} · <code>{project.compiled.manifest.id}@{project.compiled.manifest.version}</code>{dirty && ` · ${c("unsaved changes")}`}</p>}</section>
    {preview && <section><h2>{preview.report.valid ? "VALID" : "INVALID"}</h2><p>{c("Composed Pack ·")} <code>{preview.document.manifest.version}</code></p><p>{preview.report.providedCapabilities.map(capability => <span className="tag" key={capability}>{capability}</span>)}</p>{Object.entries(groupedDiagnostics).map(([code, diagnostics]) => <article key={code}><h3>{code}</h3>{diagnostics.map((diagnostic, index) => <p key={`${diagnostic.path}-${index}`}><code>{diagnostic.path}</code> · {diagnostic.message}</p>)}</article>)}</section>}
  </main>;
}
