import React,{useEffect,useState}from"react";import{resolvePin,joinGuest,sessionSocket}from"./session-client.js";import{CharacterBuilder,loadCharacterSchema,loadCharacters,selectCharacter}from"./character-builder.js";import{GmGame,PlayerGame}from"./game.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
async function post(path:string,body:any={},gmToken?:string){const r=await fetch(`${API}${path}`,{method:"POST",headers:{"content-type":"application/json",...(gmToken?{authorization:`Bearer ${gmToken}`}:{})},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw Error(x.message??`HTTP ${r.status}`);return x}
export function PlayerJoin(){
 const saved=useState<any>(()=>{try{const value=JSON.parse(localStorage.getItem("masterhost.join")??"null");return value?.participant?.accessToken?value:null}catch{return null}})[0];
 const[pin,setPin]=useState(""),[resolved,setResolved]=useState<any>(saved?.resolved),[name,setName]=useState(""),[participant,setParticipant]=useState<any>(saved?.participant),[state,setState]=useState<any>(),[error,setError]=useState(""),[schema,setSchema]=useState<any>(),[characters,setCharacters]=useState<any[]>([]),[character,setCharacter]=useState<any>(saved?.character);
 const ownerKey=useState(()=>{let k=localStorage.getItem("masterhost.ownerKey");if(!k){k=crypto.randomUUID();localStorage.setItem("masterhost.ownerKey",k)}return k})[0];
 useEffect(()=>{if(!participant)return;const ws=sessionSocket(participant.sessionId,participant.accessToken,(e:any)=>{if(e.type==="session.snapshot")setState(e.payload);if(e.type==="session.state")setState((s:any)=>({...s,session:e.payload}));if(e.type.startsWith("participant."))fetch(`${API}/sessions/${participant.sessionId}`,{headers:{authorization:`Bearer ${participant.accessToken}`}}).then(r=>r.json()).then(setState)});return()=>ws.close()},[participant]);
 useEffect(()=>{if(participant&&!character){loadCharacterSchema().then(sc=>{setSchema(sc);return loadCharacters(ownerKey,sc.pack.id,sc.pack.version)}).then(setCharacters).catch(e=>setError(e.message))}},[participant?.id]);
 useEffect(()=>{if(participant&&resolved)localStorage.setItem("masterhost.join",JSON.stringify({participant,character,resolved}))},[participant,character,resolved]);
 async function resolve(){try{setError("");const x=await resolvePin(pin);setResolved(x);const sc=await loadCharacterSchema();setSchema(sc);setCharacters(await loadCharacters(ownerKey,sc.pack.id,sc.pack.version))}catch(e:any){setError(e.message)}}
 async function join(){try{setParticipant(await joinGuest(resolved.session.id,resolved.session.pin,name))}catch(e:any){setError(e.message)}}
 async function choose(c:any){try{await selectCharacter(participant.id,c.id,ownerKey,participant.accessToken);setCharacter(c)}catch(e:any){setError(e.message)}}
 async function ready(){const p=await post(`/participants/${participant.id}/ready`,{ready:!participant.ready},participant.accessToken);setParticipant({...p,accessToken:participant.accessToken})}
 if(participant&&!character)return <main><header><h1>{resolved?.campaign?.name}</h1><p className="muted">Choose your character</p></header>{characters.length>0&&<section><h2>Saved characters</h2>{characters.map(c=><article key={c.id}><h3>{c.displayName}</h3><p className="muted">{Object.entries(c.values).map(([k,v])=>`${k}: ${v}`).join(" · ")}</p><button onClick={()=>choose(c)}>Select</button></article>)}</section>}<CharacterBuilder schema={schema?.schema} ownerKey={ownerKey} onCreated={async c=>{setCharacters([c,...characters]);await choose(c)}}/>{error&&<p className="error">{error}</p>}</main>;
 if(participant&&character&&state?.session?.state==="live")return <main><header><h1>{resolved?.campaign?.name}</h1></header><PlayerGame session={state.session} participant={participant}/></main>;
 if(participant&&character)return <main><header><h1>{resolved?.campaign?.name??"Session"}</h1><p className="muted">Session {state?.session?.state??resolved.session.state}</p></header><section><h2>{state?.session?.state==="live"?"GAME LIVE":"Waiting for GM…"}</h2><p><b>{character.displayName}</b> · player {participant.displayName}</p><button onClick={ready}>{participant.ready?"Not ready":"Ready"}</button><h3>Party</h3>{(state?.participants??[]).map((p:any)=><div className="row" key={p.id}><b>{p.displayName}</b><span>{p.ready?"READY":"waiting"}</span></div>)}</section></main>;
 if(resolved)return <main><header><h1>JOIN GAME</h1></header><section><h2>{resolved.campaign?.name}</h2><p className="muted">PIN {resolved.session.pin}</p><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Alex"/></label><button disabled={!name.trim()} onClick={join}>Continue</button>{error&&<p className="error">{error}</p>}</section></main>;
 return <main><header><h1>MASTERHOST</h1></header><section className="join"><h2>JOIN GAME</h2><label>Session PIN<input className="pin" inputMode="numeric" maxLength={5} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,5))} placeholder="74291"/></label><button disabled={pin.length!==5} onClick={resolve}>Join</button>{error&&<p className="error">{error}</p>}</section></main>
}
export function GmLobby({world,onBack}:{world:any,onBack:()=>void}){
 const gmSaved=useState<any>(()=>{try{return JSON.parse(sessionStorage.getItem(`masterhost.gm.${world.id}`)??"null")}catch{return null}})[0];
 const[campaign,setCampaign]=useState<any>(gmSaved?.campaign),[session,setSession]=useState<any>(gmSaved?.session),[participants,setParticipants]=useState<any[]>([]),[name,setName]=useState(`${world.name} Campaign`),[error,setError]=useState("");
 useEffect(()=>{if(campaign&&session)sessionStorage.setItem(`masterhost.gm.${world.id}`,JSON.stringify({campaign,session}))},[campaign,session,world.id]);
 useEffect(()=>{if(!session)return;const ws=sessionSocket(session.id,campaign.gmToken,(e:any)=>{if(e.type==="session.snapshot"){setSession(e.payload.session);setParticipants(e.payload.participants)}else if(e.type==="session.state")setSession(e.payload);else fetch(`${API}/sessions/${session.id}`,{headers:{authorization:`Bearer ${campaign.gmToken}`}}).then(r=>r.json()).then(x=>{setSession(x.session);setParticipants(x.participants)})});return()=>ws.close()},[session?.id]);
 async function create(){try{const c=await post("/campaigns",{worldId:world.id,name});setCampaign(c);setSession(await post(`/campaigns/${c.id}/sessions`,{},c.gmToken))}catch(e:any){setError(e.message)}}
 async function start(){setSession(await post(`/sessions/${session.id}/state`,{state:"live"},campaign.gmToken))}
 if(!session)return <main><header><h1>GM</h1></header><section><h2>Start campaign</h2><label>Campaign name<input value={name} onChange={e=>setName(e.target.value)}/></label><button onClick={create}>Create campaign & start lobby</button><button className="secondary" onClick={onBack}>Back</button>{error&&<p className="error">{error}</p>}</section></main>;
 if(session.state==="live")return <main><header><h1>{campaign?.name}</h1><p className="muted">GM</p></header><GmGame session={session} participants={participants} gmToken={campaign.gmToken}/></main>;
 return <main><header><h1>{campaign?.name}</h1><p className="muted">GM Lobby</p></header><section className="lobby"><div className="bigPin">{session.pin??"LIVE"}</div><p className="muted">Tell players to open <b>#join</b> and enter this PIN</p><h3>Players · {participants.length}</h3>{participants.length?participants.map(p=><div className="row" key={p.id}><b>{p.displayName}</b><span>{p.ready?"READY":"waiting"}</span></div>):<p className="muted">Waiting for players…</p>}<button disabled={session.state!=="lobby"||participants.length===0} onClick={start}>START GAME</button><button className="secondary" onClick={()=>location.hash="join"}>Open player join</button></section></main>
}
