import React,{useEffect,useState}from"react";import{resolvePin,joinGuest,sessionSocket}from"./session-client.js";import{CharacterBuilder,loadCharacterSchema,loadCharacters,selectCharacter}from"./character-builder.js";import{GmGame,PlayerGame}from"./game.js";import{realmHeaders,rememberRealm}from"./realm.js";import{LanguageSwitcher,useI18n}from"./i18n/react.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
async function post(path:string,body:any={},gmToken?:string){const r=await fetch(`${API}${path}`,{method:"POST",headers:realmHeaders({"content-type":"application/json",...(gmToken?{authorization:`Bearer ${gmToken}`}:{})}),body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw Error(x.message??`HTTP ${r.status}`);return x}
function Journey({active}:{active:number}){const{t}=useI18n(),labels=[t("lobby.game"),t("lobby.campaign"),t("lobby.playersStep"),t("lobby.startStep")];return <nav className="journey" aria-label="Game setup">{labels.map((label,index)=><span className={index<active?"done":index===active?"active":""} key={label}><b>{index<active?"✓":index+1}</b>{label}</span>)}</nav>}
export function buildInviteUrl(origin:string,pathname:string,realm:string,pin:string){return `${origin}${pathname}?realm=${encodeURIComponent(realm)}&pin=${encodeURIComponent(pin)}#join`}
export function PlayerJoin(){
 const{t}=useI18n(),invitePin=new URLSearchParams(location.search).get("pin")?.replace(/\D/g,"").slice(0,6)??"",saved=useState<any>(()=>{if(invitePin.length===6)return null;try{const value=JSON.parse(localStorage.getItem("masterhost.join")??"null");return value?.participant?.accessToken?value:null}catch{return null}})[0];
 const[pin,setPin]=useState(invitePin),[resolved,setResolved]=useState<any>(saved?.resolved),[name,setName]=useState(""),[participant,setParticipant]=useState<any>(saved?.participant),[state,setState]=useState<any>(),[error,setError]=useState(""),[schema,setSchema]=useState<any>(),[characters,setCharacters]=useState<any[]>([]),[character,setCharacter]=useState<any>(saved?.character);
 const ownerKey=useState(()=>{let k=localStorage.getItem("masterhost.ownerKey");if(!k){k=crypto.randomUUID();localStorage.setItem("masterhost.ownerKey",k)}return k})[0];
 useEffect(()=>{if(saved?.resolved?.realm?.slug)rememberRealm(saved.resolved.realm.slug)},[]);useEffect(()=>{if(!participant)return;const ws=sessionSocket(participant.sessionId,participant.accessToken,(e:any)=>{if(e.type==="session.snapshot"||e.type==="session.catchup")setState(e.payload);if(e.type==="session.state")setState((s:any)=>({...s,session:e.payload}));if(e.type.startsWith("participant."))fetch(`${API}/sessions/${participant.sessionId}`,{headers:realmHeaders({authorization:`Bearer ${participant.accessToken}`})}).then(r=>r.json()).then(setState)});return()=>ws.close()},[participant]);useEffect(()=>{if(participant&&!character){loadCharacterSchema().then(sc=>{setSchema(sc);return loadCharacters(ownerKey)}).then(setCharacters).catch(e=>setError(e.message))}},[participant?.id]);useEffect(()=>{if(participant&&resolved)localStorage.setItem("masterhost.join",JSON.stringify({participant,character,resolved}))},[participant,character,resolved]);
 useEffect(()=>{if(invitePin.length===6)void resolve(invitePin)},[]);
 async function resolve(value=pin){try{setError("");const x=await resolvePin(value);rememberRealm(x.realm.slug);setResolved(x);const sc=await loadCharacterSchema();setSchema(sc);setCharacters(await loadCharacters(ownerKey))}catch(e:any){setError(e.message)}}async function join(){try{setParticipant(await joinGuest(resolved.session.id,resolved.session.pin,name))}catch(e:any){setError(e.message)}}async function choose(c:any){try{const selected=await selectCharacter(participant.id,c.id,ownerKey,participant.accessToken);setCharacter(selected.character)}catch(e:any){setError(e.message)}}async function ready(){const p=await post(`/participants/${participant.id}/ready`,{ready:!participant.ready},participant.accessToken);setParticipant({...p,accessToken:participant.accessToken})}async function leaveCurrent(){try{if(participant?.accessToken)await post(`/participants/${participant.id}/leave`,{},participant.accessToken)}catch{}localStorage.removeItem("masterhost.join");setParticipant(null);setCharacter(null);setResolved(null);setState(undefined);setPin(invitePin);if(invitePin.length===6)void resolve(invitePin)}
 const header=(title:string)=><header className="productHeader compact"><div><p className="eyebrow">MasterHost</p><h1>{title}</h1></div><LanguageSwitcher/></header>;
 if(participant&&!character)return <main className="playerFlow">{header(resolved?.campaign?.name??t("join.title"))}<Journey active={2}/><section><h2>{t("join.character")}</h2>{characters.length>0&&<div className="characterCards">{characters.map(c=><article key={c.id}><h3>{c.displayName}</h3><p className="muted">{Object.entries(c.values).slice(0,4).map(([k,v])=>`${k}: ${v}`).join(" · ")}</p><span className={c.compatibility?.compatible?"tag good":"tag"}>{c.compatibility?.compatible?t("join.compatible"):t("join.unavailable")}</span><button disabled={!c.compatibility?.compatible} onClick={()=>choose(c)}>{t("join.select")}</button></article>)}</div>}<details open={!characters.length}><summary>{t("character.createNew")}</summary><CharacterBuilder schema={schema?.schema} ownerKey={ownerKey} onCreated={async c=>{setCharacters([c,...characters]);await choose(c)}}/></details>{error&&<p className="error">{error}</p>}<button className="secondary" onClick={leaveCurrent}>{t("join.other")}</button></section></main>;
 if(participant&&character&&state?.session?.state==="live")return <main className="playerGameShell">{header(resolved?.campaign?.name??"Game")}<PlayerGame session={state.session} participant={participant} onLeave={leaveCurrent}/></main>;
 if(participant&&character){const status=state?.session?.state??resolved.session.state,ended=["finished","cancelled"].includes(status);return <main className="playerFlow">{header(resolved?.campaign?.name??"Session")}<Journey active={3}/><section className="readyCard"><span className="homeIcon">✓</span><h2>{ended?t("join.ended"):t("join.waitGm")}</h2><p><b>{character.displayName}</b> · {participant.displayName}</p>{!ended&&<button onClick={ready}>{t("common.ready")}</button>}<h3>{t("join.party")}</h3>{(state?.participants??[]).map((p:any)=><div className="compactRow" key={p.id}><b>{p.displayName}</b><span>{p.ready?t("common.ready"):t("common.waiting")}</span></div>)}<button className="secondary" onClick={leaveCurrent}>{t("join.other")}</button></section></main>}
 if(resolved)return <main className="playerFlow">{header(t("join.title"))}<Journey active={1}/><section className="joinCard"><p className="eyebrow">{resolved.campaign?.name}</p><h2>PIN {resolved.session.pin}</h2><label>{t("join.name")}<input value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="Alex"/></label><button disabled={!name.trim()} onClick={join}>{t("common.continue")}</button>{error&&<p className="error">{error}</p>}</section></main>;
 return <main className="playerFlow">{header(t("join.title"))}<Journey active={0}/><section className="joinCard"><h2>{t("join.code")}</h2><p>{t("join.codeHelp")}</p><label>{t("lobby.code")}<input className="pin" inputMode="numeric" autoFocus maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="742911"/></label><button disabled={pin.length!==6} onClick={()=>void resolve()}>{t("common.continue")}</button>{error&&<p className="error">{error}</p>}</section></main>
}
export function GmLobby({world,onBack}:{world:any,onBack:()=>void}){
 const{t}=useI18n(),gmSaved=useState<any>(()=>{try{return JSON.parse(sessionStorage.getItem(`masterhost.gm.${world.id}`)??"null")}catch{return null}})[0];const[campaign,setCampaign]=useState<any>(gmSaved?.campaign),[session,setSession]=useState<any>(gmSaved?.session),[participants,setParticipants]=useState<any[]>([]),[name,setName]=useState(`${world.name} Campaign`),[characterPortability,setCharacterPortability]=useState<"exact"|"pack">("exact"),[error,setError]=useState(""),[copied,setCopied]=useState(false);
 useEffect(()=>{if(campaign&&session)sessionStorage.setItem(`masterhost.gm.${world.id}`,JSON.stringify({campaign,session}))},[campaign,session,world.id]);useEffect(()=>{if(!session)return;const ws=sessionSocket(session.id,campaign.gmToken,(e:any)=>{if(e.type==="session.snapshot"||e.type==="session.catchup"){setSession(e.payload.session);setParticipants(e.payload.participants)}else if(e.type==="session.state")setSession(e.payload);else fetch(`${API}/sessions/${session.id}`,{headers:realmHeaders({authorization:`Bearer ${campaign.gmToken}`})}).then(r=>r.json()).then(x=>{setSession(x.session);setParticipants(x.participants)})});return()=>ws.close()},[session?.id]);
 async function create(){try{const c=await post("/campaigns",{worldId:world.id,name,characterPortability});setCampaign(c);setSession(await post(`/campaigns/${c.id}/sessions`,{},c.gmToken))}catch(e:any){setError(e.message)}}async function start(){setSession(await post(`/sessions/${session.id}/state`,{state:"live"},campaign.gmToken))}function newCampaign(){sessionStorage.removeItem(`masterhost.gm.${world.id}`);setCampaign(undefined);setSession(undefined);setParticipants([])}async function copy(){await navigator.clipboard.writeText(buildInviteUrl(location.origin,location.pathname,new URLSearchParams(location.search).get("realm")??"default",session.pin));setCopied(true);setTimeout(()=>setCopied(false),1800)}
 const top=<header className="productHeader compact"><div><p className="eyebrow">{world.name}</p><h1>{campaign?.name??t("setup.title")}</h1></div><LanguageSwitcher/></header>;
 if(!session)return <main className="campaignFlow">{top}<Journey active={1}/><section className="campaignCard"><p className="eyebrow">{t("setup.eyebrow")}</p><h2>{t("setup.title")}</h2><p>{t("setup.help")}</p><label>{t("setup.name")}<input value={name} onChange={e=>setName(e.target.value)}/></label><details><summary>{t("setup.advanced")}</summary><label>{t("setup.policy")}<select value={characterPortability} onChange={e=>setCharacterPortability(e.target.value as"exact"|"pack")}><option value="exact">{t("setup.exact")}</option><option value="pack">{t("setup.portable")}</option></select></label></details><div className="actions"><button className="secondary" onClick={onBack}>{t("setup.games")}</button><button onClick={create}>{t("setup.create")}</button></div>{error&&<p className="error">{error}</p>}</section></main>;
 if(session.state==="live")return <main className="gmGameShell">{top}<GmGame session={session} participants={participants} gmToken={campaign.gmToken}/></main>;
 const canStart=session.state==="lobby"&&participants.length>0;
 return <main className="campaignFlow">{top}<Journey active={session.state==="lobby"?2:3}/><div className="lobbyGrid"><section className="inviteCard"><p className="eyebrow">{t("lobby.code")}</p><div className="bigPin">{session.state==="lobby"?session.pin:session.state.toUpperCase()}</div>{session.state==="lobby"&&<><p>{t("lobby.share")}</p><div className="actions"><button onClick={()=>void copy()}>{copied?t("lobby.copied"):t("lobby.copy")}</button><button className="secondary" onClick={()=>location.hash="join"}>{t("lobby.openPlayer")}</button></div></>}</section><section><div className="titleRow"><h2>{t("lobby.players",{count:participants.length})}</h2>{canStart&&<span className="tag good">{t("lobby.canStart")}</span>}</div>{participants.length?participants.map(p=><div className="personRow" key={p.id}><span className="avatar">{p.displayName.slice(0,2).toUpperCase()}</span><b>{p.displayName}</b><span>{p.ready?t("common.ready"):t("common.waiting")}</span></div>):<p className="muted">{t("lobby.empty")}</p>}</section></div>{session.state==="lobby"&&<div className="startBar"><p>{canStart?t("lobby.canStart"):t("lobby.needPlayer")}</p><button disabled={!canStart} onClick={start}>{t("lobby.startGame")}</button></div>}{["finished","cancelled"].includes(session.state)&&<button className="secondary" onClick={newCampaign}>{t("lobby.new")}</button>}</main>
}
