import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";import{PlayerJoin,GmLobby}from"./lobby.js";
import { EntityImages } from "./entity-images.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,init);const type=r.headers.get("content-type")??"";const body=type.includes("json")?await r.json():await r.text();if(!r.ok)throw Error((body as any)?.message??`HTTP ${r.status}`);return body}
function App(){
 const[hash,setHash]=useState(location.hash.slice(1));useEffect(()=>{const f=()=>setHash(location.hash.slice(1));addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);

 const[pack,setPack]=useState<any>(),[choices,setChoices]=useState<Record<string,string>>({}),[world,setWorld]=useState<any>(),[error,setError]=useState(""),[report,setReport]=useState<any>(),[impact,setImpact]=useState<any>(),[explain,setExplain]=useState<any>();
 const[worlds,setWorlds]=useState<any[]>([]),[worldFilter,setWorldFilter]=useState(""),[selectedWorldId,setSelectedWorldId]=useState(""),[snapshots,setSnapshots]=useState<any[]>([]),[selectedSnapshotId,setSelectedSnapshotId]=useState(""),[forkName,setForkName]=useState("");
 useEffect(()=>{api("/pack").then((p:any)=>{setPack(p);setChoices(Object.fromEntries(p.questions.map((q:any)=>[q.id,q.default])))}).catch((e:any)=>setError(e.message))},[]);
 const loadWorlds=async(p=pack)=>{const all=await api("/worlds") as any[];const compatible=all.filter(w=>w.packId===p.manifest.id&&w.packVersion===p.manifest.version);setWorlds(compatible);setSelectedWorldId(current=>compatible.some(w=>w.id===current&&`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?current:compatible.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?.id??"")};
 const loadMeta=async(w:any)=>{const [nextReport,nextSnapshots]=await Promise.all([api(`/worlds/${w.id}/report`),api(`/worlds/${w.id}/snapshots`)]);setWorld(w);sessionStorage.setItem("masterhost.worldId",w.id);setReport(nextReport);setSnapshots(nextSnapshots as any[]);setSelectedSnapshotId("");setForkName(`${w.name} Fork`);setImpact(undefined);setExplain(undefined)};
 useEffect(()=>{if(!pack)return;void loadWorlds(pack).catch((e:any)=>setError(e.message));const id=sessionStorage.getItem("masterhost.worldId");if(id)void api(`/worlds/${id}`).then(async(w:any)=>{if(w.packId!==pack.manifest.id||w.packVersion!==pack.manifest.version)throw Error("incompatible saved World");await loadMeta(w)}).catch(()=>sessionStorage.removeItem("masterhost.worldId"))},[pack]);
 async function generate(){try{setError("");await loadMeta(await api("/worlds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choices})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function importWorld(file:File){try{setError("");await loadMeta(await api("/worlds/import",{method:"POST",headers:{"content-type":"application/vnd.masterhost.world+zip"},body:file}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function openWorld(){try{setError("");await loadMeta(await api(`/worlds/${selectedWorldId}`))}catch(e:any){setError(e.message)}}
 async function fork(){try{setError("");await loadMeta(await api(`/worlds/${world.id}/fork`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:forkName.trim()})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function restore(){try{setError("");await loadMeta(await api(`/snapshots/${selectedSnapshotId}/restore`,{method:"POST"}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function preview(){setImpact(await api(`/worlds/${world.id}/regenerate/preview`,{method:"POST"}))}
 async function regen(){await loadMeta(await api(`/worlds/${world.id}/regenerate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotName:`Before regeneration r${world.revision}`})}))}
 async function customize(entity:any,key:string,current:any){const value=prompt(`New value for ${key}`,String(current));if(value===null)return;await loadMeta(await api(`/worlds/${world.id}/values`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entityId:entity.id,key,value,locked:true})}))}
 async function why(e:any,k:string){setExplain(await api(`/worlds/${world.id}/entities/${e.id}/explain/${encodeURIComponent(k)}`))}
 async function snapshot(){try{setError("");await api(`/worlds/${world.id}/snapshots`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:`Manual snapshot r${world.revision}`})});const next=await api(`/worlds/${world.id}/snapshots`) as any[];setSnapshots(next);setSelectedSnapshotId(next[0]?.id??"")}catch(e:any){setError(e.message)}}
 async function uploadAsset(file:File){try{setError("");await loadMeta(await api(`/worlds/${world.id}/assets?name=${encodeURIComponent(file.name)}`,{method:"POST",headers:{"content-type":"application/octet-stream","x-asset-media-type":file.type},body:file}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function assignImage(entityId:string,role:string,name:string|null){try{setError("");await loadMeta(await api(`/worlds/${world.id}/entities/${entityId}/assets/${role}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 const visibleWorlds=worlds.filter(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()));
 if(hash==="join")return <PlayerJoin/>;
 if(hash==="gm"&&world)return <GmLobby world={world} onBack={()=>location.hash=""}/>;
 if(!pack)return <main><h1>MASTERHOST</h1><p>{error||"Loading…"}</p></main>;
 return <main><header><h1>MASTERHOST</h1><p className="muted">{pack.manifest.name} · {pack.manifest.version}</p></header>{error&&<p className="error">{error}</p>}
 {!world?<section><h2>Quick World</h2><p className="muted">Choose only what matters. The pack resolves the rest.</p>{pack.questions.map((q:any)=><label key={q.id}>{q.label}<select value={choices[q.id]??q.default} onChange={e=>setChoices({...choices,[q.id]:e.target.value})}>{q.options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}<button onClick={generate}>Generate world</button><label>Import .mhworld<input type="file" accept=".mhworld" onChange={e=>{const file=e.target.files?.[0];if(file)void importWorld(file);e.target.value=""}}/></label>{worlds.length>0&&<article><h3>Open saved World</h3><label>Find World<input value={worldFilter} onChange={e=>{const query=e.target.value;setWorldFilter(query);setSelectedWorldId(worlds.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(query.toLowerCase()))?.id??"")}}/></label><label>World<select value={selectedWorldId} onChange={e=>setSelectedWorldId(e.target.value)}>{visibleWorlds.map(w=><option key={w.id} value={w.id}>{w.name} · revision {w.revision} · {w.id.slice(0,8)}</option>)}</select></label><button className="secondary" disabled={!selectedWorldId} onClick={openWorld}>Open World</button></article>}</section>
 :<section><div className="titleRow"><div><h2>{world.name}</h2><p className="muted">Seed <code>{world.seed}</code> · revision {world.revision}</p></div><button className="secondary" onClick={()=>{setWorld(undefined);setReport(undefined);sessionStorage.removeItem("masterhost.worldId")}}>New world</button></div>
 {report&&<article><h3>Generation report</h3><div className="row"><b>Entities</b><span>{report.entities}</span><small>{Object.entries(report.kinds).map(([k,v])=>`${k}: ${v}`).join(" · ")}</small></div></article>}
 {world.entities.map((e:any)=><article key={e.id}><h3>{e.kind} <small>{e.materializationPath}</small></h3>{Object.entries(e.values).map(([k,v]:any)=><div className="row" key={k}><b>{k}</b><span>{String(v.value)}</span><small>{v.source}{v.locked?" · LOCKED":""}</small><button className="tiny" onClick={()=>why(e,k)}>Why?</button><button className="tiny" onClick={()=>customize(e,k,v.value)}>Edit + lock</button></div>)}<EntityImages worldId={world.id} entity={e} images={world.assets??{}} api={API} onAssign={(role,name)=>assignImage(e.id,role,name)}/></article>)}
 <div className="actions"><button onClick={()=>location.hash="gm"}>Start campaign</button><button onClick={preview}>Preview regeneration</button><button onClick={regen}>Snapshot + regenerate</button><button className="secondary" onClick={snapshot}>Create snapshot</button><a className="button secondary" href={`${API}/worlds/${world.id}/export`}>Export .mhworld</a></div>
 <article><h3>World history</h3>{snapshots.length>0?<><label>Snapshot<select value={selectedSnapshotId} onChange={e=>setSelectedSnapshotId(e.target.value)}><option value="">Choose snapshot…</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.name} · revision {s.revision}</option>)}</select></label><button className="secondary" disabled={!selectedSnapshotId} onClick={restore}>Restore snapshot as new revision</button></>:<p className="muted">No snapshots yet.</p>}<label>Fork name<input value={forkName} onChange={e=>setForkName(e.target.value)}/></label><button className="secondary" disabled={!forkName.trim()} onClick={fork}>Fork World</button></article>
 <article><h3>World images</h3><label>Add PNG, JPEG or WebP (up to 2 MB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadAsset(file);e.target.value=""}}/></label>{Object.entries(world.assets??{}).map(([name,ref]:[string,any])=><div className="row" key={name}><b>{name}</b><small>{ref.mediaType} · {ref.size} bytes</small><a href={`${API}/worlds/${world.id}/assets/${encodeURIComponent(name)}`}>Download</a></div>)}</article>
 {impact&&<article><h3>Regeneration impact</h3><p>Change {impact.changed} · Create {impact.created} · Remove {impact.removed} · Preserve {impact.preserved} · Locked {impact.blockedByLocks}</p></article>}
 {explain&&<article><h3>Why?</h3><pre>{JSON.stringify(explain,null,2)}</pre><button className="secondary" onClick={()=>setExplain(undefined)}>Close</button></article>}
 </section>}</main>
}
createRoot(document.getElementById("root")!).render(<App/>);
