import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";import{PlayerJoin,GmLobby}from"./lobby.js";
import { WorldBuilder } from "./world-builder.js";
import { PackCreator } from "./pack-creator.js";
import { RealmConsole } from "./realm-console.js";
import { currentRealm,realmHeaders } from "./realm.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
const REALM=currentRealm();
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,{...init,headers:realmHeaders(init?.headers)});const type=r.headers.get("content-type")??"";const body=type.includes("json")?await r.json():await r.text();if(!r.ok)throw Error((body as any)?.message??`HTTP ${r.status}`);return body}
function App(){
 const[hash,setHash]=useState(location.hash.slice(1));useEffect(()=>{const f=()=>setHash(location.hash.slice(1));addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);

 const[realm,setRealm]=useState<any>(),[pack,setPack]=useState<any>(),[choices,setChoices]=useState<Record<string,string>>({}),[world,setWorld]=useState<any>(),[error,setError]=useState(""),[report,setReport]=useState<any>(),[impact,setImpact]=useState<any>();
 const[worlds,setWorlds]=useState<any[]>([]),[worldFilter,setWorldFilter]=useState(""),[selectedWorldId,setSelectedWorldId]=useState(""),[snapshots,setSnapshots]=useState<any[]>([]),[selectedSnapshotId,setSelectedSnapshotId]=useState(""),[forkName,setForkName]=useState("");
 useEffect(()=>{Promise.all([api("/host/realm"),api("/pack")]).then(([r,p]:any[])=>{setRealm(r);setPack(p);setChoices(Object.fromEntries(p.questions.map((q:any)=>[q.id,q.default])));const root=document.documentElement;root.style.setProperty("--realm-primary",r.brand.theme.primary);root.style.setProperty("--realm-accent",r.brand.theme.accent);root.style.setProperty("--realm-background",r.brand.theme.background);document.title=r.name;if(r.assets?.favicon){let icon=document.querySelector("link[rel='icon']")as HTMLLinkElement|null;if(!icon){icon=document.createElement("link");icon.rel="icon";document.head.append(icon)}icon.href=`${API}/cdn/${r.assets.favicon.checksum}`}}).catch((e:any)=>setError(e.message))},[]);
 const loadWorlds=async(p=pack)=>{const all=await api("/worlds") as any[];const compatible=all.filter(w=>w.packId===p.manifest.id&&w.packVersion===p.manifest.version);setWorlds(compatible);setSelectedWorldId(current=>compatible.some(w=>w.id===current&&`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?current:compatible.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?.id??"")};
 const loadMeta=async(w:any)=>{const [nextReport,nextSnapshots]=await Promise.all([api(`/worlds/${w.id}/report`),api(`/worlds/${w.id}/snapshots`)]);setWorld(w);sessionStorage.setItem(`masterhost.worldId.${REALM}`,w.id);setReport(nextReport);setSnapshots(nextSnapshots as any[]);setSelectedSnapshotId("");setForkName(`${w.name} Fork`);setImpact(undefined)};
 useEffect(()=>{if(!pack)return;void loadWorlds(pack).catch((e:any)=>setError(e.message));const key=`masterhost.worldId.${REALM}`,id=sessionStorage.getItem(key);if(id)void api(`/worlds/${id}`).then(async(w:any)=>{if(w.packId!==pack.manifest.id||w.packVersion!==pack.manifest.version)throw Error("incompatible saved World");await loadMeta(w)}).catch(()=>sessionStorage.removeItem(key))},[pack]);
 async function generate(){try{setError("");await loadMeta(await api("/worlds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choices})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function importWorld(file:File){try{setError("");await loadMeta(await api("/worlds/import",{method:"POST",headers:{"content-type":"application/vnd.masterhost.world+zip"},body:file}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function openWorld(){try{setError("");await loadMeta(await api(`/worlds/${selectedWorldId}`))}catch(e:any){setError(e.message)}}
 async function fork(){try{setError("");await loadMeta(await api(`/worlds/${world.id}/fork`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:forkName.trim()})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function restore(){try{setError("");await loadMeta(await api(`/snapshots/${selectedSnapshotId}/restore`,{method:"POST"}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function preview(){setImpact(await api(`/worlds/${world.id}/regenerate/preview`,{method:"POST"}))}
 async function regen(){await loadMeta(await api(`/worlds/${world.id}/regenerate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotName:`Before regeneration r${world.revision}`})}))}
 async function snapshot(){try{setError("");await api(`/worlds/${world.id}/snapshots`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:`Manual snapshot r${world.revision}`})});const next=await api(`/worlds/${world.id}/snapshots`) as any[];setSnapshots(next);setSelectedSnapshotId(next[0]?.id??"")}catch(e:any){setError(e.message)}}
 const visibleWorlds=worlds.filter(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()));
 if(hash==="join")return <PlayerJoin/>;
 if(hash==="gm"&&world)return <GmLobby world={world} onBack={()=>location.hash=""}/>;
 if(hash==="pack")return <PackCreator request={api} apiRoot={API} onBack={()=>location.hash=""}/>;
 if(hash==="realm")return <RealmConsole request={api} onBack={()=>location.hash=""}/>;
 if(!pack||!realm)return <main><h1>MASTERHOST</h1><p>{error||"Loading…"}</p></main>;
 const terms=realm.brand.terminology;
 return <main>{realm.assets?.landing&&<img className="realmLanding" src={`${API}/cdn/${realm.assets.landing.checksum}`} alt=""/>}<header className="titleRow"><div className="realmIdentity">{realm.assets?.logo&&<img src={`${API}/cdn/${realm.assets.logo.checksum}`} alt=""/>}<div><h1>{realm.name}</h1><p className="muted">{pack.manifest.name} · {pack.manifest.version}</p></div></div><div className="actions"><button className="secondary" onClick={()=>location.hash="pack"}>Create {terms.world} Pack</button><button className="secondary" onClick={()=>location.hash="realm"}>Realm settings</button></div></header>{error&&<p className="error">{error}</p>}
 {!world?<section><h2>Quick {terms.world}</h2><p className="muted">Choose only what matters. The Pack resolves the rest.</p>{pack.questions.map((q:any)=><label key={q.id}>{q.label}<select value={choices[q.id]??q.default} onChange={e=>setChoices({...choices,[q.id]:e.target.value})}>{q.options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}<button onClick={generate}>Generate {terms.world}</button><label>Import .mhworld<input type="file" accept=".mhworld" onChange={e=>{const file=e.target.files?.[0];if(file)void importWorld(file);e.target.value=""}}/></label>{realm.catalog?.length>0&&<p className="muted">Published in this Realm · {realm.catalog.length}</p>}{worlds.length>0&&<article><h3>Open saved {terms.world}</h3><label>Find {terms.world}<input value={worldFilter} onChange={e=>{const query=e.target.value;setWorldFilter(query);setSelectedWorldId(worlds.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(query.toLowerCase()))?.id??"")}}/></label><label>{terms.world}<select value={selectedWorldId} onChange={e=>setSelectedWorldId(e.target.value)}>{visibleWorlds.map(w=><option key={w.id} value={w.id}>{w.name} · revision {w.revision} · {w.id.slice(0,8)}</option>)}</select></label><button className="secondary" disabled={!selectedWorldId} onClick={openWorld}>Open {terms.world}</button></article>}</section>
 :<section><div className="titleRow"><div><h2>{world.name}</h2><p className="muted">Seed <code>{world.seed}</code> · revision {world.revision}</p></div><button className="secondary" onClick={()=>{setWorld(undefined);setReport(undefined);sessionStorage.removeItem(`masterhost.worldId.${REALM}`)}}>New world</button></div>
 {report&&<article><h3>Generation report</h3><div className="row"><b>Entities</b><span>{report.entities}</span><small>{Object.entries(report.kinds).map(([k,v])=>`${k}: ${v}`).join(" · ")}</small></div></article>}
 <WorldBuilder world={world} request={api} apiRoot={API} onWorld={async next=>{await loadMeta(next);await loadWorlds()}}/>
 <div className="actions"><button onClick={()=>location.hash="gm"}>Start campaign</button><button onClick={preview}>Preview regeneration</button><button onClick={regen}>Snapshot + regenerate</button><button className="secondary" onClick={snapshot}>Create snapshot</button><a className="button secondary" href={`${API}/worlds/${world.id}/export?realm=${encodeURIComponent(REALM)}`}>Export .mhworld</a></div>
 <article><h3>World history</h3>{snapshots.length>0?<><label>Snapshot<select value={selectedSnapshotId} onChange={e=>setSelectedSnapshotId(e.target.value)}><option value="">Choose snapshot…</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.name} · revision {s.revision}</option>)}</select></label><button className="secondary" disabled={!selectedSnapshotId} onClick={restore}>Restore snapshot as new revision</button></>:<p className="muted">No snapshots yet.</p>}<label>Fork name<input value={forkName} onChange={e=>setForkName(e.target.value)}/></label><button className="secondary" disabled={!forkName.trim()} onClick={fork}>Fork World</button></article>
 {impact&&<article><h3>Regeneration impact</h3><p>Change {impact.changed} · Create {impact.created} · Remove {impact.removed} · Preserve {impact.preserved} · Locked {impact.blockedByLocks}</p></article>}
 </section>}</main>
}
createRoot(document.getElementById("root")!).render(<App/>);
