import {SessionAdmin} from "./session-admin.js";
import {useContentI18n} from './i18n/content-react.js';
import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";import{PlayerJoin,GmLobby}from"./lobby.js";
import { WorldBuilder } from "./world-builder.js";
import { PackCreator } from "./pack-creator.js";
import { RealmConsole } from "./realm-console.js";
import { OfficialLibrary } from "./official-library.js";
import { GameDescriptorBuilder } from "./game-descriptor-builder.js";
import { QuickGameBuilder } from "./quick-game-builder.js";
import { currentRealm,realmHeaders } from "./realm.js";
import { I18nProvider,LanguageSwitcher } from "./i18n/react.js";
import { ProductHome } from "./product-home.js";
import { UniverseCatalog } from "./universe-catalog.js";
import { GameHub } from "./game-hub.js";
const API=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
const REALM=currentRealm();
async function api(path:string,init?:RequestInit){const r=await fetch(`${API}${path}`,{...init,headers:realmHeaders(init?.headers)});const type=r.headers.get("content-type")??"";const body=type.includes("json")?await r.json():await r.text();if(!r.ok)throw Error((body as any)?.message??`HTTP ${r.status}`);return body}
async function apiMedia(path:string){const r=await fetch(`${API}${path}`,{headers:realmHeaders()});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.blob()}
async function download(path:string,fallback:string){const r=await fetch(`${API}${path}`,{headers:realmHeaders()});if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(body.message??`HTTP ${r.status}`)}const blob=await r.blob(),match=r.headers.get("content-disposition")?.match(/filename="([^"]+)"/),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=match?.[1]??fallback;a.click();URL.revokeObjectURL(url)}
function App(){
 const[hash,setHash]=useState(location.hash.slice(1));useEffect(()=>{const f=()=>setHash(location.hash.slice(1));addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);

 const[realm,setRealm]=useState<any>(),[pack,setPack]=useState<any>(),[choices,setChoices]=useState<Record<string,string>>({}),[world,setWorld]=useState<any>(),[worldContentPack,setWorldContentPack]=useState<any>(),[error,setError]=useState(""),[report,setReport]=useState<any>(),[impact,setImpact]=useState<any>();
 const{c}=useContentI18n(pack);
 const[worlds,setWorlds]=useState<any[]>([]),[worldFilter,setWorldFilter]=useState(""),[selectedWorldId,setSelectedWorldId]=useState(""),[snapshots,setSnapshots]=useState<any[]>([]),[selectedSnapshotId,setSelectedSnapshotId]=useState(""),[forkName,setForkName]=useState(""),[installed,setInstalled]=useState<any>();
 useEffect(()=>{Promise.all([api("/host/realm"),api("/pack")]).then(([r,p]:any[])=>{setRealm(r);setPack(p);setChoices(Object.fromEntries(p.questions.map((q:any)=>[q.id,q.default])));const root=document.documentElement;root.style.setProperty("--realm-primary",r.brand.theme.primary);root.style.setProperty("--realm-accent",r.brand.theme.accent);root.style.setProperty("--realm-background",r.brand.theme.background);document.title=r.name;if(r.assets?.favicon){let icon=document.querySelector("link[rel='icon']")as HTMLLinkElement|null;if(!icon){icon=document.createElement("link");icon.rel="icon";document.head.append(icon)}icon.href=`${API}/cdn/${r.assets.favicon.checksum}`}}).catch((e:any)=>setError(e.message))},[]);
 const loadWorlds=async(p=pack)=>{const all=await api("/worlds") as any[];const compatible=all.filter(w=>(w.packId===p.manifest.id&&w.packVersion===p.manifest.version)||Boolean(w.descriptor?.composition));setWorlds(compatible);setSelectedWorldId(current=>compatible.some(w=>w.id===current&&`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?current:compatible.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()))?.id??"")};
 const loadMeta=async(w:any)=>{const [nextReport,nextSnapshots,nextContentPack]=await Promise.all([api(`/worlds/${w.id}/report`),api(`/worlds/${w.id}/snapshots`),api(`/worlds/${w.id}/content-localization`)]);setWorldContentPack(nextContentPack);setWorld(w);localStorage.setItem(`masterhost.worldId.${REALM}`,w.id);setReport(nextReport);setSnapshots(nextSnapshots as any[]);setSelectedSnapshotId("");setForkName(`${w.name} Fork`);setImpact(undefined)};
 useEffect(()=>{if(!pack)return;void loadWorlds(pack).catch((e:any)=>setError(e.message));const key=`masterhost.worldId.${REALM}`,id=localStorage.getItem(key)??sessionStorage.getItem(key);if(id)void api(`/worlds/${id}`).then(async(w:any)=>{if((w.packId!==pack.manifest.id||w.packVersion!==pack.manifest.version)&&!w.descriptor?.composition)throw Error("incompatible saved World");await loadMeta(w)}).catch(()=>{localStorage.removeItem(key);sessionStorage.removeItem(key)})},[pack]);
 async function generate(){try{setError("");await loadMeta(await api("/worlds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choices})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function importWorld(file:File){try{setError("");await loadMeta(await api("/worlds/import",{method:"POST",headers:{"content-type":"application/vnd.masterhost.world+zip"},body:file}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function importGame(file:File){try{setError("");const result=await api("/games/import",{method:"POST",headers:{"content-type":"application/vnd.masterhost.game+zip"},body:file}),[nextRealm,nextPack]=await Promise.all([api("/host/realm"),api("/pack")]);setRealm(nextRealm);setPack(nextPack);setInstalled(result);await loadMeta(await api(`/worlds/${result.worldId}`));await loadWorlds(nextPack)}catch(e:any){setError(e.message)}}
 async function exportGame(){try{setError("");await download(`/worlds/${world.id}/export-game`,`${world.name}.mhgame`)}catch(e:any){setError(e.message)}}
 async function openWorld(){try{setError("");await loadMeta(await api(`/worlds/${selectedWorldId}`))}catch(e:any){setError(e.message)}}
 async function fork(){try{setError("");await loadMeta(await api(`/worlds/${world.id}/fork`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:forkName.trim()})}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function restore(){try{setError("");await loadMeta(await api(`/snapshots/${selectedSnapshotId}/restore`,{method:"POST"}));await loadWorlds()}catch(e:any){setError(e.message)}}
 async function preview(){setImpact(await api(`/worlds/${world.id}/regenerate/preview`,{method:"POST"}))}
 async function regen(){await loadMeta(await api(`/worlds/${world.id}/regenerate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotName:`Before regeneration r${world.revision}`})}))}
 async function snapshot(){try{setError("");await api(`/worlds/${world.id}/snapshots`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:`Manual snapshot r${world.revision}`})});const next=await api(`/worlds/${world.id}/snapshots`) as any[];setSnapshots(next);setSelectedSnapshotId(next[0]?.id??"")}catch(e:any){setError(e.message)}}
 const visibleWorlds=worlds.filter(w=>`${w.name} ${w.id}`.toLowerCase().includes(worldFilter.toLowerCase()));
 if(hash==="join")return <PlayerJoin/>;
 if(hash==="gm"&&world)return <GmLobby world={world} onBack={()=>location.hash="game"}/>;
 if(hash==="pack")return <PackCreator request={api} requestMedia={apiMedia} apiRoot={API} onBack={()=>location.hash=""}/>;
 if(hash==="admin")return <SessionAdmin request={api} onBack={()=>location.hash=""}/>;
 if(hash==="realm")return <RealmConsole request={api} onBack={()=>location.hash=""}/>;
 if(hash==="official")return <OfficialLibrary realm={realm} request={api} onBack={()=>location.hash=""}/>;
 if(!pack||!realm)return <main><h1>{c("MASTERHOST")}</h1><p>{error||"Loading…"}</p></main>;
 if(hash==="universes")return <UniverseCatalog request={api} onBack={()=>location.hash=""} onAdvanced={()=>location.hash="advanced-game-builder"} onPlay={async value=>{try{setError("");if(pack.manifest.id!==value.basePack.id||pack.manifest.version!==value.basePack.version){await api(`/host/realms/${realm.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({activePack:value.basePack})});const next=await api("/pack");setPack(next);setChoices(Object.fromEntries(next.questions.map((q:any)=>[q.id,q.default])))}location.hash="game-builder"}catch(reason:any){throw reason}}}/>;
 if(hash==="game-builder")return <QuickGameBuilder request={api} requestMedia={apiMedia} pack={pack} onWorld={async next=>{await loadMeta(next);await loadWorlds();location.hash="game"}} onBack={()=>location.hash="universes"} onAdvanced={()=>location.hash="advanced-game-builder"}/>;
 if(hash==="advanced-game-builder")return <GameDescriptorBuilder request={api} requestMedia={apiMedia} pack={pack} onWorld={async next=>{await loadMeta(next);await loadWorlds();location.hash="game"}} onBack={()=>location.hash="game-builder"} onFork={project=>{sessionStorage.setItem("masterhost.packProject",project.id);location.hash="pack"}}/>;
 if(hash==="game"&&world)return <GameHub world={world} pack={worldContentPack} onStart={()=>location.hash="gm"} onEdit={()=>location.hash="world"} onBack={()=>location.hash=""}/>;
 if(hash!=="world")return <ProductHome realm={realm} pack={pack} worlds={worlds} currentWorld={world} onRun={async next=>{await loadMeta(next);location.hash="game"}} onEdit={async next=>{await loadMeta(next);location.hash="world"}}/>;
 const terms=realm.brand.terminology;
 return <main className="worldWorkspace"><div className="workspaceTop"><button className="secondary" onClick={()=>location.hash=""}>{c("← Home")}</button><LanguageSwitcher/></div>{realm.assets?.landing&&<img className="realmLanding" src={`${API}/cdn/${realm.assets.landing.checksum}`} alt=""/>}<header className="titleRow"><div className="realmIdentity">{realm.assets?.logo&&<img src={`${API}/cdn/${realm.assets.logo.checksum}`} alt=""/>}<div><h1>{world?.name??realm.name}</h1><p className="muted">{c(pack.manifest.name)} · {pack.manifest.version}</p></div></div><div className="actions"><button onClick={()=>location.hash="gm"}>{c("Prepare campaign")}</button><button className="secondary" onClick={()=>location.hash="game-builder"}>{c("Build another game")}</button></div></header>{error&&<p className="error">{error}</p>}
 {!world?<section><h2>{c("Quick")} {terms.world}</h2><p className="muted">{c("Choose only what matters. The Pack resolves the rest.")}</p>{pack.questions.map((q:any)=><label key={q.id}>{c(q.label)}<select value={choices[q.id]??q.default} onChange={e=>setChoices({...choices,[q.id]:e.target.value})}>{q.options.map((o:any)=><option key={o.value} value={o.value}>{c(o.label)}</option>)}</select></label>)}<button onClick={generate}>{c("Generate")} {terms.world}</button><label>{c("Install complete game (.mhgame)")}<input type="file" accept=".mhgame,application/vnd.masterhost.game+zip" onChange={e=>{const file=e.target.files?.[0];if(file)void importGame(file);e.target.value=""}}/></label><label>{c("Import World only (.mhworld)")}<input type="file" accept=".mhworld" onChange={e=>{const file=e.target.files?.[0];if(file)void importWorld(file);e.target.value=""}}/></label>{realm.catalog?.length>0&&<p className="muted">{c("Published in this Realm ·")} {realm.catalog.length}</p>}{worlds.length>0&&<article><h3>{c("Open saved")} {terms.world}</h3><label>{c("Find")} {terms.world}<input value={worldFilter} onChange={e=>{const query=e.target.value;setWorldFilter(query);setSelectedWorldId(worlds.find(w=>`${w.name} ${w.id}`.toLowerCase().includes(query.toLowerCase()))?.id??"")}}/></label><label>{terms.world}<select value={selectedWorldId} onChange={e=>setSelectedWorldId(e.target.value)}>{visibleWorlds.map(w=><option key={w.id} value={w.id}>{w.name} {c("· revision")} {w.revision} · {w.id.slice(0,8)}</option>)}</select></label><button className="secondary" disabled={!selectedWorldId} onClick={openWorld}>{c("Open")} {terms.world}</button></article>}</section>
 :<section><div className="titleRow"><div><h2>{world.name}</h2><p className="muted">{c("Seed")} <code>{world.seed}</code> {c("· revision")} {world.revision} {c("· Pack")} <code>{world.packId}@{world.packVersion}</code></p></div><button className="secondary" onClick={()=>{setWorld(undefined);setReport(undefined);localStorage.removeItem(`masterhost.worldId.${REALM}`);sessionStorage.removeItem(`masterhost.worldId.${REALM}`)}}>{c("New world")}</button></div>
 {report&&<article><h3>{c("Generation report")}</h3><div className="row"><b>{c("Entities")}</b><span>{report.entities}</span><small>{Object.entries(report.kinds).map(([k,v])=>`${k}: ${v}`).join(" · ")}</small></div></article>}
 <WorldBuilder world={world} request={api} requestMedia={apiMedia} onWorld={async next=>{await loadMeta(next);await loadWorlds()}}/>
 {installed&&installed.worldId===world.id&&<article className="notice"><b>{c("Complete game installed.")}</b><p>{c("Runtime Pack")} <code>{installed.runtimePack.id}@{installed.runtimePack.version}</code> {c("is active. An editable Pack fork is ready in the Pack Creator.")}</p><button className="secondary" onClick={()=>{sessionStorage.setItem("masterhost.packProject",installed.editablePackProjectId);location.hash="pack"}}>{c("Edit imported Pack")}</button></article>}
 <div className="actions"><button onClick={()=>location.hash="gm"}>{c("Start campaign")}</button><button onClick={preview}>{c("Preview regeneration")}</button><button onClick={regen}>{c("Snapshot + regenerate")}</button><button className="secondary" onClick={snapshot}>{c("Create snapshot")}</button><button className="secondary" onClick={exportGame}>{c("Export complete .mhgame")}</button><a className="button secondary" href={`${API}/worlds/${world.id}/export?realm=${encodeURIComponent(REALM)}`}>{c("Export .mhworld")}</a></div>
 <article><h3>{c("World history")}</h3>{snapshots.length>0?<><label>{c("Snapshot")}<select value={selectedSnapshotId} onChange={e=>setSelectedSnapshotId(e.target.value)}><option value="">{c("Choose snapshot…")}</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.name} {c("· revision")} {s.revision}</option>)}</select></label><button className="secondary" disabled={!selectedSnapshotId} onClick={restore}>{c("Restore snapshot as new revision")}</button></>:<p className="muted">{c("No snapshots yet.")}</p>}<label>{c("Fork name")}<input value={forkName} onChange={e=>setForkName(e.target.value)}/></label><button className="secondary" disabled={!forkName.trim()} onClick={fork}>{c("Fork World")}</button></article>
 {impact&&<article><h3>{c("Regeneration impact")}</h3><p>{c("Change")} {impact.changed} {c("· Create")} {impact.created} {c("· Remove")} {impact.removed} {c("· Preserve")} {impact.preserved} {c("· Locked")} {impact.blockedByLocks}</p></article>}
 </section>}</main>
}
const hot=(import.meta as ImportMeta & {hot?:{data:{root?:ReturnType<typeof createRoot>}}}).hot;
const root=hot?.data.root??createRoot(document.getElementById("root")!);
if(hot)hot.data.root=root;
root.render(<I18nProvider><App/></I18nProvider>);
