import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,it,expect} from 'vitest';
import {I18nProvider} from './i18n/react.js';
import {supportedLocales,translate} from './i18n/catalog.js';
import {MobileTableNav,MobileTableMenu,mobileCopy,ParticipantRemovalDialog,attemptParticipantRemoval} from './mobile-table.js';
function setup(locale:string){Object.defineProperty(globalThis,'location',{value:{search:`?lang=${locale}`},configurable:true});Object.defineProperty(globalThis,'navigator',{value:{languages:[locale]},configurable:true});Object.defineProperty(globalThis,'localStorage',{value:{getItem:()=>null},configurable:true})}
describe('mobile table navigation',()=>{
 it('retains a failed confirmation error inside its dialog and allows a successful retry',async()=>{setup('ru');let calls=0;const remove=async(id:string)=>{expect(id).toBe('player');if(++calls===1)throw Error('Session state changed')};const failed=await attemptParticipantRemoval('player',remove,'Disconnected');expect(failed).toEqual({removed:false,error:'Session state changed'});if(failed.removed)throw Error('failure expected');const html=renderToStaticMarkup(<I18nProvider><ParticipantRemovalDialog name="Alex" error={failed.error} disabled={false} busy={false} onCancel={()=>{}} onConfirm={()=>{}}/></I18nProvider>);expect(html).toContain('role="alert"');expect(html).toContain('Session state changed');expect(html).toContain('Alex');expect(await attemptParticipantRemoval('player',remove,'Disconnected')).toEqual({removed:true});expect(calls).toBe(2)});
 it('does not accept an explicitly unsuccessful callback as removal',async()=>{expect(await attemptParticipantRemoval('player',async()=>false,'Removal refused')).toEqual({removed:false,error:'Removal refused'})});
 it('exposes distinct role workspaces without GM controls to players',()=>{setup('ru');const player=renderToStaticMarkup(<I18nProvider><MobileTableNav role="player" active="character" onSelect={()=>{}}/></I18nProvider>),gm=renderToStaticMarkup(<I18nProvider><MobileTableNav role="gm" active="party" onSelect={()=>{}}/></I18nProvider>);expect(player).toContain('Персонаж');expect(player).not.toContain('Сцены');expect(gm).toContain('Сцены');expect(gm).not.toContain('Персонаж');expect(player.match(/aria-current="page"/g)).toHaveLength(1);expect(gm.match(/aria-current="page"/g)).toHaveLength(1)});
 for(const locale of supportedLocales)it(`uses authored navigation labels in ${locale}`,()=>{setup(locale);const html=renderToStaticMarkup(<I18nProvider><MobileTableNav role="player" active="map" onSelect={()=>{}}/></I18nProvider>);for(const key of ['player.map','player.character','player.journal'] as const)expect(html).toContain(translate(locale,key));expect(html).toContain(mobileCopy[locale].actions);expect(html).not.toContain('player.map');expect(html).not.toContain('player.abilities')});
 it('keeps menu children in the tree even while closed',()=>{setup('ru');const html=renderToStaticMarkup(<I18nProvider><MobileTableMenu open={false} onClose={()=>{}}><textarea defaultValue="unsent private note"/></MobileTableMenu></I18nProvider>);expect(html).toContain('unsent private note');expect(html).toContain('<dialog');expect(html).not.toContain('<dialog open')});
});
