import {useContentI18n} from './i18n/content-react.js';
import React,{useEffect,useState}from"react";
export function OfficialLibrary({realm,request,onBack}:{realm:any;request:(path:string,init?:RequestInit)=>Promise<any>;onBack:()=>void}){
 const {c}=useContentI18n();
 const[packs,setPacks]=useState<any[]>([]),[message,setMessage]=useState("");useEffect(()=>{void request("/official-packs").then(setPacks).catch(error=>setMessage(error.message))},[]);
 async function activate(pack:any){try{if(!realm)throw Error(c("Realm is still loading"));await request(`/host/realms/${realm.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({activePack:{id:pack.manifest.id,version:pack.manifest.version}})});location.hash="";location.reload()}catch(error:any){setMessage(error.message)}}
 const api=(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api";
 return <main><div className="titleRow"><div><h1>{c("OFFICIAL WORLDS")}</h1><p className="muted">{c("Production content for the generic MasterHost engine.")}</p></div><button className="secondary" onClick={onBack}>{c("Back")}</button></div>{message&&<p className="error">{message}</p>}<div className="officialGrid">{packs.map(pack=><article key={pack.manifest.id}><img src={`${api}/official-packs/${encodeURIComponent(pack.manifest.id)}/assets/ui/background.svg`} alt=""/><div className="titleRow"><h2>{c(pack.manifest.name,pack.manifest.id)}</h2><span className="tag">{c("OFFICIAL")}</span></div><p>{c(pack.manifest.description,pack.manifest.id)}</p><p className="muted">{c(pack.manifest.contentRating)} · {pack.manifest.license.spdx} · {pack.assessment.metrics.templates} {c("templates")} · {pack.assessment.metrics.assets} {c("artworks")}</p><p><b>{c("World:")}</b> {pack.content.kinds.map((value:string)=>c(value,pack.manifest.id)).join(" · ")}</p><p><b>{c("Characters:")}</b> {pack.content.characters.map((value:string)=>c(value,pack.manifest.id)).join(" → ")}</p><p><b>{c("Rules:")}</b> {pack.content.checks.map((value:string)=>c(value,pack.manifest.id)).join(" · ")}</p><p><b>{c("NPCs:")}</b> {pack.content.actors.map((value:string)=>c(value,pack.manifest.id)).join(" · ")}</p>{realm?.activePack?.id===pack.manifest.id?<button disabled>{c("Active in this Realm")}</button>:realm?.role==="owner"?<button onClick={()=>void activate(pack)}>{c("Activate in this Realm")}</button>:null}<small>{pack.manifest.license.attribution}</small></article>)}</div></main>
}
