import React,{useEffect,useState}from"react";import{currentRealm}from"./realm.js";import{AuthenticatedImage}from"./authenticated-image.js";import{CharacterPanel,OverviewPanel,RulesPanel,WorldPanel}from"./pack-editor-panels.js";import{removePackEntry,type PackCollection}from"./pack-editor-model.js";import{DeepUniverseDashboard}from"./deep-universe-dashboard.js";
const tabs=["overview","universe","decisions","world","characters","rules","assets","source","validate"] as const;type Tab=typeof tabs[number];
export function parsePackSource(value:string){const document=JSON.parse(value);if(!document||typeof document!=="object"||Array.isArray(document))throw Error("Pack source must be a JSON object");return document}
export function PackCreator({request,requestMedia,apiRoot,onBack}:{request:(path:string,init?:RequestInit)=>Promise<any>;requestMedia:(path:string)=>Promise<Blob>;apiRoot:string;onBack:()=>void}){
 const scoped=(path:string)=>`${apiRoot}${path}${path.includes("?")?"&":"?"}realm=${encodeURIComponent(currentRealm())}`;
 const[projects,setProjects]=useState<any[]>([]),[project,setProject]=useState<any>(),[tab,setTab]=useState<Tab>("overview"),[message,setMessage]=useState(""),[validation,setValidation]=useState<any>(),[deepAssessment,setDeepAssessment]=useState<any>(),[source,setSource]=useState<any>(),[sourceDraft,setSourceDraft]=useState(""),[sourceError,setSourceError]=useState(""),[generated,setGenerated]=useState<any>();
 const[create,setCreate]=useState({id:"masterhost.sky-isles",name:"Sky Isles",version:"0.1.0",worldKind:"archipelago",worldName:"The Shattered Sky",childKind:"island",childName:"First Haven"});const json={"content-type":"application/json"};
 const refresh=async()=>{const next=await request("/pack-projects");setProjects(next);const requested=sessionStorage.getItem("masterhost.packProject");if(requested){const selected=next.find((value:any)=>value.id===requested);if(selected)setProject(selected);sessionStorage.removeItem("masterhost.packProject")}};useEffect(()=>{void refresh()},[]);useEffect(()=>{if(project?.document?.universe)void request(`/pack-projects/${project.id}/deep-universe`).then(setDeepAssessment).catch((error:any)=>setMessage(error.message));else setDeepAssessment(undefined)},[project?.id,project?.revision]);const draft=project?.status==="draft";
 async function createProject(){try{setMessage("");const next=await request("/pack-projects",{method:"POST",headers:json,body:JSON.stringify(create)});setProject(next);await refresh()}catch(error:any){setMessage(error.message)}}
 async function save(){try{const next=await request(`/pack-projects/${project.id}`,{method:"PUT",headers:json,body:JSON.stringify({document:project.document})});setProject(next);setMessage(`Draft revision ${next.revision} saved`);await refresh()}catch(error:any){setMessage(error.message)}}
 const change=(mutate:(document:any)=>void)=>{const next=structuredClone(project);mutate(next.document);setProject(next);setValidation(undefined);setDeepAssessment(undefined)};
 const manifest=(key:string,value:string)=>change(document=>document.manifest[key]=value),term=(key:string,value:string)=>change(document=>document.terminology[key]=value);
 const remove=(collection:PackCollection,id:string)=>{try{const next=structuredClone(project);next.document=removePackEntry(next.document,collection,id);setProject(next);setValidation(undefined);setMessage(`${collection} ${id} removed from draft`)}catch(error){setMessage(error instanceof Error?error.message:String(error))}};
 async function assessDeep(){if(!project.document.universe){setDeepAssessment(undefined);return}try{setDeepAssessment(await request(`/pack-projects/${project.id}/deep-universe`,{method:"POST",headers:json,body:JSON.stringify({document:project.document})}))}catch(error:any){setMessage(error.message)}}
 async function validate(){try{const[value,deep]=await Promise.all([request(`/pack-projects/${project.id}/validate`,{method:"POST",headers:json,body:JSON.stringify({document:project.document})}),project.document.universe?request(`/pack-projects/${project.id}/deep-universe`,{method:"POST",headers:json,body:JSON.stringify({document:project.document})}):Promise.resolve(undefined)]);setValidation(value);setDeepAssessment(deep);setTab("validate")}catch(error:any){setMessage(error.message)}}
 async function publish(){try{await save();const value=await request(`/pack-projects/${project.id}/publish`,{method:"POST"});setProject(value.project);setValidation(value.conformance);setMessage(`${value.project.document.manifest.id}@${value.project.document.manifest.version} published`);await refresh()}catch(error:any){setMessage(error.message)}}
 async function generate(){try{const world=await request(`/pack-projects/${project.id}/generate-world`,{method:"POST",headers:json,body:JSON.stringify({choices:Object.fromEntries(project.document.content.questions.map((question:any)=>[question.id,question.default]))})});setGenerated(world);setMessage(`Generated ${world.name} with ${world.entities.length} entities`)}catch(error:any){setMessage(error.message)}}
 async function loadSource(){const[jsonSource,yaml]=await Promise.all([request(`/pack-projects/${project.id}/source/json`),request(`/pack-projects/${project.id}/source/yaml`)]),json=typeof jsonSource==="string"?jsonSource:JSON.stringify(jsonSource,null,2);setSource({json,yaml});setSourceDraft(JSON.stringify(project.document,null,2));setSourceError("");setTab("source")}
 function applySource(){try{const document=parsePackSource(sourceDraft);change(current=>{for(const key of Object.keys(current))delete current[key];Object.assign(current,document)});setSourceError("");setMessage("JSON source applied to the unsaved draft")}catch(error:any){setSourceError(`Invalid JSON: ${error.message}`)}}
 async function upload(file:File){try{const next=await request(`/pack-projects/${project.id}/assets?name=${encodeURIComponent(file.name)}`,{method:"POST",headers:{"content-type":"application/octet-stream","x-asset-media-type":file.type},body:file});setProject(next);await refresh()}catch(error:any){setMessage(error.message)}}
 async function importPack(file:File){try{const next=await request("/pack-projects/import",{method:"POST",headers:{"content-type":"application/vnd.masterhost.pack+zip"},body:file});setProject(next);await refresh()}catch(error:any){setMessage(error.message)}}
 async function cloneVersion(){const version=prompt("New immutable version",project.document.manifest.version.replace(/(\d+)$/,(value:string)=>String(Number(value)+1)));if(!version)return;const next=await request(`/pack-projects/${project.id}/clone`,{method:"POST",headers:json,body:JSON.stringify({version})});setProject(next);setValidation(undefined);setGenerated(undefined);await refresh()}
 if(!project)return <main><div className="titleRow"><div><h1>WORLD PACK CREATOR</h1><p className="muted">Visual authoring · validation · portable publishing</p></div><button className="secondary" onClick={onBack}>Back</button></div>{message&&<p className="error">{message}</p>}<section><h2>New setting</h2>{Object.entries(create).map(([key,value])=><label key={key}>{key}<input value={value} onChange={event=>setCreate({...create,[key]:event.target.value})}/></label>)}<button onClick={createProject}>Create complete starter Pack</button><label>Import .mhpack<input type="file" accept=".mhpack" onChange={event=>{const file=event.target.files?.[0];if(file)void importPack(file);event.target.value=""}}/></label></section>{projects.length>0&&<section><h2>Pack projects</h2>{projects.map(item=><button className="projectCard secondary" key={item.id} onClick={()=>setProject(item)}><b>{item.document.manifest.name}</b><span>{item.document.manifest.id}@{item.document.manifest.version}</span><small>{item.status.toUpperCase()} · revision {item.revision}</small></button>)}</section>}</main>;
 const document=project.document,content=document.content;
 return <main className="packCreator"><div className="titleRow"><div><h1>{document.manifest.name}</h1><p className="muted">{document.manifest.id}@{document.manifest.version} · {project.status.toUpperCase()} · revision {project.revision}</p>{project.lineage?.source==="game-descriptor"&&<p className="muted">Forked from Descriptor <code>{project.lineage.projectId}</code> revision {project.lineage.revision}</p>}{project.lineage?.source==="mhgame"&&<p className="muted">Editable fork from imported game <code>{project.lineage.packageId}</code> · source Pack <code>{project.lineage.sourcePack.id}@{project.lineage.sourcePack.version}</code></p>}</div><button className="secondary" onClick={()=>setProject(undefined)}>All Packs</button></div>{message&&<p className={message.includes("saved")||message.includes("published")||message.includes("Generated")?"notice":"error"}>{message}</p>}<nav className="tabs">{tabs.map(value=><button key={value} className={tab===value?"":"secondary"} onClick={()=>value==="source"?void loadSource():setTab(value)}>{value}</button>)}</nav>
 {tab==="overview"&&<OverviewPanel document={document} draft={draft} change={change} remove={remove}/>}
 {tab==="universe"&&<DeepUniverseDashboard document={document} assessment={deepAssessment} draft={draft} canPublish={project.status==="published"||Boolean(validation?.valid&&(!document.universe||deepAssessment?.passed))} onAssess={()=>void assessDeep()} onDiagnostic={path=>{setMessage(`Review ${path} in declarative source`);void loadSource()}}/>}
 {tab==="decisions"&&<><section><div className="titleRow"><div><h2>Decision graph</h2><p className="muted">Questions become one normalized Descriptor.</p></div>{draft&&<button onClick={()=>change(doc=>doc.content.questions.push({id:`world.choice${doc.content.questions.length+1}`,label:"New choice",type:"choice",default:"yes",options:[{value:"yes",label:"Yes"},{value:"no",label:"No"}]}))}>Add decision</button>}</div>{content.questions.map((question:any,index:number)=><article key={index}><label>ID<input disabled={!draft} value={question.id} onChange={event=>change(doc=>doc.content.questions[index].id=event.target.value)}/></label><label>Label<input disabled={!draft} value={question.label} onChange={event=>change(doc=>doc.content.questions[index].label=event.target.value)}/></label><label>Options<input disabled={!draft} value={question.options.map((value:any)=>`${value.value}:${value.label}`).join(", ")} onChange={event=>change(doc=>{const options=event.target.value.split(",").map(value=>value.trim()).filter(Boolean).map(value=>{const[id,label]=value.split(":");return{value:id,label:label??id}});doc.content.questions[index].options=options;if(!options.some(value=>value.value===doc.content.questions[index].default))doc.content.questions[index].default=options[0]?.value??""})}/></label><label>Default<select disabled={!draft} value={question.default} onChange={event=>change(doc=>doc.content.questions[index].default=event.target.value)}>{question.options.map((value:any)=><option key={value.value} value={value.value}>{value.label}</option>)}</select></label></article>)}</section><section><h2>Dependencies and migrations</h2>{document.dependencies.map((value:any,index:number)=><div className="compactRow" key={index}><input disabled={!draft} value={value.id} onChange={event=>change(doc=>doc.dependencies[index].id=event.target.value)}/><input disabled={!draft} value={value.version} onChange={event=>change(doc=>doc.dependencies[index].version=event.target.value)}/></div>)}{draft&&<button className="secondary" onClick={()=>change(doc=>doc.dependencies.push({id:"dependency.pack",version:"1.0.0"}))}>Add immutable dependency</button>}{document.migrations.map((value:any,index:number)=><article key={index}><label>From<input disabled={!draft} value={value.fromVersion} onChange={event=>change(doc=>doc.migrations[index].fromVersion=event.target.value)}/></label><label>To<input disabled={!draft} value={value.toVersion} onChange={event=>change(doc=>doc.migrations[index].toVersion=event.target.value)}/></label><label>Notes<input disabled={!draft} value={value.notes} onChange={event=>change(doc=>doc.migrations[index].notes=event.target.value)}/></label></article>)}{draft&&<button className="secondary" onClick={()=>change(doc=>doc.migrations.push({fromVersion:"0.0.1",toVersion:doc.manifest.version,notes:"Describe declarative migration"}))}>Add migration</button>}</section></>}
 {tab==="world"&&<WorldPanel document={document} draft={draft} change={change} remove={remove}/>}
 {tab==="characters"&&<CharacterPanel document={document} draft={draft} change={change} remove={remove}/>}
 {tab==="rules"&&<RulesPanel document={document} draft={draft} change={change} remove={remove}/>}
 {tab==="assets"&&<section><h2>Pack assets</h2>{draft&&<label>Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value=""}}/></label>}<div className="mediaGrid">{Object.entries(document.assets).map(([name,asset]:any)=><article key={name}><AuthenticatedImage requestMedia={requestMedia} path={`/pack-projects/${project.id}/assets/${encodeURIComponent(name)}`} alt={name} onError={setMessage}/><h3>{name}</h3><small>{asset.mediaType} · {asset.size} bytes</small></article>)}</div></section>}
 {tab==="source"&&<section><div className="titleRow"><div><h2>Declarative source</h2><p className="muted">Edit the complete draft as JSON, apply it locally, then validate and save.</p></div><div className="actions"><a className="button secondary" href={scoped(`/pack-projects/${project.id}/source/yaml`)}>Download YAML</a><a className="button secondary" href={scoped(`/pack-projects/${project.id}/source/json`)}>Download JSON</a></div></div>{draft?<><label>Draft JSON<textarea aria-label="Editable Pack JSON source" rows={32} value={sourceDraft} onChange={event=>{setSourceDraft(event.target.value);setSourceError("")}}/></label>{sourceError&&<p className="error">{sourceError}</p>}<button onClick={applySource}>Apply JSON to draft</button></>:<pre>{source?.json}</pre>}<details><summary>Saved YAML snapshot</summary><pre>{source?.yaml}</pre></details></section>}
 {tab==="validate"&&<section><h2>Validation and conformance</h2>{validation?<><p className={validation.valid?"notice":"error"}>{validation.valid?"PASS":"FAIL"}</p>{validation.fixtures?.map((fixture:any)=><div className="compactRow" key={fixture.id}><b>{fixture.id}</b><span>{fixture.passed?"PASS":"FAIL"}</span><small>{fixture.entities} entities · {fixture.kinds?.join(", ")}</small></div>)}{validation.diagnostics.map((value:any,index:number)=><div className="compactRow" key={index}><b>{value.code}</b><span>{value.message}</span><small>{value.path}</small></div>)}</>:<p>Run conformance before publishing.</p>}</section>}
 <section className="packActions"><div className="actions">{draft&&<button onClick={save}>Save draft</button>}<button className="secondary" onClick={validate}>Validate</button>{draft&&<button disabled={!validation?.valid||Boolean(document.universe&&!deepAssessment?.passed)} onClick={publish}>Publish immutable version</button>}{project.status==="published"&&<><button onClick={generate}>Generate World</button><button className="secondary" onClick={cloneVersion}>Create next version</button></>}<a className="button secondary" href={scoped(`/pack-projects/${project.id}/export`)}>Export .mhpack</a></div>{generated&&<article><h3>Generated World: {generated.name}</h3><p>{generated.entities.length} entities · {generated.packId}@{generated.packVersion}</p><p>{[...new Set(generated.entities.map((value:any)=>value.kind))].join(" · ")}</p></article>}</section>
 </main>
}
