import React from"react";import{LanguageSwitcher,useI18n}from"./i18n/react.js";
type World={id:string;name:string;revision:number;packId:string;packVersion:string;entities?:unknown[]};
export function ProductHome({realm,pack,worlds,currentWorld,onRun,onEdit}:{realm:any;pack:any;worlds:World[];currentWorld?:World;onRun:(world:World)=>void;onEdit:(world:World)=>void}){const{t}=useI18n(),preferred=currentWorld??worlds[0];return <main className="productHome">
 <header className="productHeader"><div className="realmIdentity">{realm.assets?.logo&&<img src={`${(import.meta as any).env?.VITE_API_URL??"http://localhost:8080/api"}/cdn/${realm.assets.logo.checksum}`} alt=""/>}<div><strong>{realm.name}</strong><small>{pack.manifest.name}</small></div></div><LanguageSwitcher/></header>
 <section className="homeHero"><p className="eyebrow">{t("home.eyebrow")}</p><h1>{t("home.title")}</h1><p>{t("home.subtitle")}</p></section>
 <section className="homeChoices">
  <article><span className="homeIcon">♛</span><h2>{t("home.run")}</h2><p>{t("home.runHint")}</p><button disabled={!preferred} onClick={()=>preferred&&onRun(preferred)}>{t("home.choose")}</button></article>
  <article><span className="homeIcon">↪</span><h2>{t("home.join")}</h2><p>{t("home.joinHint")}</p><button className="secondary" onClick={()=>location.hash="join"}>{t("home.enterCode")}</button></article>
  <article><span className="homeIcon">✦</span><h2>{t("home.create")}</h2><p>{t("home.createHint")}</p><button className="secondary" onClick={()=>location.hash="game-builder"}>{t("home.startBuild")}</button></article>
 </section>
 <div className="sectionHeading"><h2>{t("home.saved",{count:worlds.length})}</h2>{worlds.length>1&&<span className="tag">{t("home.all")}</span>}</div>
 {worlds.length===0?<section className="emptyState"><h2>{t("home.noGames")}</h2><button onClick={()=>location.hash="game-builder"}>{t("home.startBuild")}</button></section>:<section className="gameLibrary">{worlds.map((item,index)=><article className="gameCard" key={item.id}><div className="gameCover" aria-hidden="true"><span>{item.name.slice(0,2).toUpperCase()}</span></div><div><h3>{item.name}</h3><p>{item.packId.replace("masterhost.","").replaceAll("-"," ")} · {Array.isArray(item.entities)?item.entities.length:0} entries</p><div><span className="tag">{index===0?t("home.continue"):t("common.ready")}</span></div></div><div className="gameCardActions"><button onClick={()=>onRun(item)}>{t("home.openTable")}</button><button className="secondary" onClick={()=>onEdit(item)}>{t("home.edit")}</button></div></article>)}</section>}
 <details className="advancedTools"><summary>{t("home.advanced")}</summary><div className="toolGrid"><button className="secondary" onClick={()=>location.hash="official"}>{t("home.official")}</button><button className="secondary" onClick={()=>location.hash="pack"}>{t("home.pack")}</button><button className="secondary" onClick={()=>location.hash="realm"}>{t("home.realm")}</button><button className="secondary" onClick={()=>location.hash="world"}>{t("home.world")}</button></div></details>
 </main>}
