import React,{useEffect,useState}from"react";
import{currentRealm}from"./realm.js";
const json={"content-type":"application/json"};
export function RealmConsole({request,onBack}:{request:(path:string,init?:RequestInit)=>Promise<any>;onBack:()=>void}){
 const[token,setToken]=useState(()=>sessionStorage.getItem(`masterhost.realmAdmin.${currentRealm()}`)??""),[accessToken,setAccessToken]=useState(()=>sessionStorage.getItem(`masterhost.realmAccess.${currentRealm()}`)??""),[realm,setRealm]=useState<any>(),[packs,setPacks]=useState<any[]>([]),[worlds,setWorlds]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[usage,setUsage]=useState<any>(),[telemetry,setTelemetry]=useState<any[]>([]),[message,setMessage]=useState(""),[kind,setKind]=useState<"world"|"pack">("world"),[resourceId,setResourceId]=useState(""),[visibility,setVisibility]=useState("private"),[policy,setPolicy]=useState({allowCampaigns:true,allowFork:true,allowModify:true,allowCharacters:true}),[backup,setBackup]=useState<any>();
 const admin=(init:RequestInit={}):RequestInit=>({...init,headers:{...(init.headers as any),authorization:`Bearer ${token}`}});
 const load=async()=>{const r=await request("/host/realm");setRealm(r);if(!token)return;const[p,w,c,u,t]=await Promise.all([request("/pack-projects",admin()),request("/worlds",admin()),request("/host/catalog",admin()),request(`/host/realms/${r.id}/usage`,admin()),request(`/host/realms/${r.id}/telemetry`,admin())]);setPacks(p);setWorlds(w);setCatalog(c);setUsage(u);setTelemetry(t);setResourceId(current=>current||w[0]?.id||p.find((value:any)=>value.status==="published")?.id||"")};
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[]);
 const connect=()=>{sessionStorage.setItem(`masterhost.realmAdmin.${currentRealm()}`,token);sessionStorage.setItem(`masterhost.realmAccess.${currentRealm()}`,token);setAccessToken(token);setMessage("");void load().then(()=>setMessage("Administrator data loaded")).catch(error=>setMessage(error.message))};
 const saveAccess=()=>{sessionStorage.setItem(`masterhost.realmAccess.${currentRealm()}`,accessToken);setMessage("Realm access saved for this session")};
 const change=(path:string,value:any)=>setRealm((current:any)=>{const next=structuredClone(current);const keys=path.split(".");let target=next;for(const key of keys.slice(0,-1))target=target[key];target[keys.at(-1)!]=value;return next});
 async function save(){try{sessionStorage.setItem(`masterhost.realmAdmin.${currentRealm()}`,token);const body={name:realm.name,domain:realm.domain??null,guestAccess:realm.guestAccess,activePack:realm.activePack??null,brand:realm.brand,quotas:realm.quotas};setRealm(await request(`/host/realms/${realm.id}`,admin({method:"PUT",headers:json,body:JSON.stringify(body)})));setMessage("Realm configuration saved")}catch(error:any){setMessage(error.message)}}
 async function upload(role:string,file:File){try{await request(`/host/realms/${realm.id}/assets/${role}`,admin({method:"POST",headers:{"content-type":"application/octet-stream","x-asset-media-type":file.type},body:file}));setMessage(`${role} uploaded`);await load()}catch(error:any){setMessage(error.message)}}
 async function publish(){try{const value=await request(`/host/realms/${realm.id}/publications`,admin({method:"POST",headers:json,body:JSON.stringify({kind,resourceId,visibility,policies:policy})}));setMessage(`${value.kind} published as ${value.visibility}`);await load()}catch(error:any){setMessage(error.message)}}
 async function createBackup(){try{const value=await request(`/host/realms/${realm.id}/backups`,admin({method:"POST"}));setBackup(value);setMessage(`Backup ${value.id} created`);await load()}catch(error:any){setMessage(error.message)}}
 async function restore(){if(!backup)return;try{await request(`/host/realms/${realm.id}/backups/${backup.id}/restore`,admin({method:"POST"}));setMessage(`Backup ${backup.id} restored`);await load()}catch(error:any){setMessage(error.message)}}
 if(!realm)return <main><h1>REALM CONSOLE</h1><p>{message||"Loading…"}</p></main>;
 const resources=kind==="world"?worlds:packs.filter(value=>value.status==="published");
 return <main className="packCreator"><div className="titleRow"><div><h1>REALM CONSOLE</h1><p className="muted">{realm.slug} · tenant {realm.id.slice(0,8)}</p></div><button className="secondary" onClick={onBack}>Back</button></div>{message&&<p className={message.includes("saved")||message.includes("uploaded")||message.includes("published")||message.includes("restored")||message.includes("created")?"notice":"error"}>{message}</p>}
 <section><h2>Access</h2><label>Creator or GM token<input type="password" value={accessToken} onChange={event=>setAccessToken(event.target.value)}/></label><button onClick={saveAccess}>Use for Realm actions</button><label>Realm admin token<input type="password" value={token} onChange={event=>setToken(event.target.value)}/></label><button onClick={connect}>Load administrator data</button><p className="muted">Tokens are kept in this browser session only.</p></section>
 <section><h2>Brand and domain</h2><label>Name<input value={realm.name} onChange={event=>change("name",event.target.value)}/></label><label>Domain<input value={realm.domain??""} onChange={event=>change("domain",event.target.value)}/></label>{Object.entries(realm.brand.theme).map(([key,value]:any)=><label key={key}>{key}<input type="color" value={value} onChange={event=>change(`brand.theme.${key}`,event.target.value)}/></label>)}{Object.entries(realm.brand.terminology).map(([key,value]:any)=><label key={key}>Term: {key}<input value={value} onChange={event=>change(`brand.terminology.${key}`,event.target.value)}/></label>)}{["logo","favicon","landing"].map(role=><label key={role}>{role}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(role,file);event.target.value=""}}/></label>)}</section>
 <section><h2>Active Pack and quotas</h2><label>Pack<select value={realm.activePack?`${realm.activePack.id}@${realm.activePack.version}`:""} onChange={event=>{const selected=packs.find(value=>`${value.document.manifest.id}@${value.document.manifest.version}`===event.target.value);change("activePack",selected?{id:selected.document.manifest.id,version:selected.document.manifest.version}:undefined)}}><option value="">No active Pack</option>{packs.filter(value=>value.status==="published").map(value=><option key={value.id}>{value.document.manifest.id}@{value.document.manifest.version}</option>)}</select></label>{Object.entries(realm.quotas).map(([key,value]:any)=><label key={key}>{key}<input type="number" min="0" value={value} onChange={event=>change(`quotas.${key}`,Number(event.target.value))}/></label>)}<button onClick={save}>Save Realm</button>{usage&&<p className="muted">Usage · {Object.entries(usage.usage).map(([key,value])=>`${key}: ${value}/${usage.quotas[key]}`).join(" · ")}</p>}</section>
 <section><h2>Publish World or Pack</h2><label>Kind<select value={kind} onChange={event=>{const next=event.target.value as"world"|"pack";setKind(next);setResourceId("")}}><option value="world">World</option><option value="pack">Pack</option></select></label><label>Resource<select value={resourceId} onChange={event=>setResourceId(event.target.value)}><option value="">Choose…</option>{resources.map(value=><option key={value.id} value={value.id}>{kind==="world"?value.name:`${value.document.manifest.name}@${value.document.manifest.version}`}</option>)}</select></label><label>Visibility<select value={visibility} onChange={event=>setVisibility(event.target.value)}><option>private</option><option>unlisted</option><option>public</option></select></label>{Object.entries(policy).map(([key,value])=><label key={key}>{key}<input type="checkbox" checked={value} onChange={event=>setPolicy({...policy,[key]:event.target.checked})}/></label>)}<button disabled={!resourceId} onClick={publish}>Publish</button>{catalog.map(value=><div className="compactRow" key={value.id}><b>{value.kind}</b><span>{value.visibility}</span><small>{value.resourceId}</small></div>)}</section>
 <section><h2>Operations</h2><div className="actions"><button onClick={createBackup}>Create verified backup</button><button className="secondary" disabled={!backup} onClick={restore}>Restore latest backup</button></div>{backup&&<p className="muted">{backup.id} · {backup.checksum.slice(0,16)} · {Object.entries(backup.counts).map(([key,value])=>`${key}: ${value}`).join(" · ")}</p>}{telemetry.map(value=><div className="compactRow" key={value.event}><b>{value.event}</b><span>{value.total}</span><small>{value.latest}</small></div>)}</section>
 </main>
}
