import {describe,it,expect,vi} from 'vitest';
import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {I18nProvider} from './i18n/react.js';import {ProductHome} from './product-home.js';import {GmLobby,PlayerJoin,buildInviteUrl} from './lobby.js';
import {openNextSession,watchSessionSnapshot} from './lobby-state.js';
function environment(saved:unknown=null){Object.defineProperty(globalThis,'location',{value:{search:'?lang=ru'},configurable:true});Object.defineProperty(globalThis,'navigator',{value:{languages:['ru']},configurable:true});Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>key.startsWith('masterhost.gm.')?JSON.stringify(saved):null},configurable:true});Object.defineProperty(globalThis,'sessionStorage',{value:{getItem:()=>null},configurable:true});}
const wrap=(child:React.ReactNode)=>renderToStaticMarkup(<I18nProvider>{child}</I18nProvider>);
describe('visible session lifecycle',()=>{
 it('keeps the selected language in a shared invitation',()=>{expect(buildInviteUrl('https://example.test','/','my realm','123456','ru')).toBe('https://example.test/?realm=my%20realm&pin=123456&lang=ru#join')});
 it('does not label an arbitrary saved world as a continued session',()=>{environment();const html=wrap(<ProductHome realm={{name:'MasterHost'}} pack={{}} worlds={[{id:'w',name:'Saved world',revision:1,packId:'pack',packVersion:'1'}]} onRun={()=>{}} onEdit={()=>{}}/>);expect(html).not.toContain('Продолжить');expect(html).toContain('Сохранённые миры');});
 it('shows a closed GM session with a working next-session action',()=>{environment({campaign:{id:'c',name:'Campaign',gmToken:'token'},session:{id:'s',state:'finished'}});const html=wrap(<GmLobby world={{id:'w',name:'World'}} onBack={()=>{}}/>);expect(html).toContain('Сессия завершена');expect(html).toContain('Новая сессия');expect(html).not.toContain('FINISHED');expect(html).not.toContain('Код игры');});
 it('shows a finished session before character selection for a joined player',()=>{environment();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>key==='masterhost.ownerKey'?'owner':key==='masterhost.join'?JSON.stringify({participant:{id:'p',sessionId:'s',accessToken:'token'},resolved:{session:{id:'s',state:'finished'},campaign:{name:'Campaign'}}}):null},configurable:true});const html=wrap(<PlayerJoin/>);expect(html).toContain('Сессия завершена');expect(html).not.toContain('characterBuilder');});
 it('starts a new live session in the same campaign using its existing authorization',async()=>{const calls:unknown[]=[];const result=await openNextSession('c','secret',async(path,body,token)=>{calls.push([path,body,token]);return {id:'next',state:path.endsWith('/state')?'live':'lobby'}});expect(result.state).toBe('live');expect(calls).toEqual([['/campaigns/c/sessions',{},'secret'],['/sessions/next/state',{state:'live'},'secret']]);});
 it('refreshes lifecycle without a WebSocket event and cancels late snapshots',async()=>{vi.useFakeTimers();try{let state='live';const received:string[]=[];const stop=watchSessionSnapshot(async()=>state,value=>received.push(value),()=>{});state='finished';await vi.advanceTimersByTimeAsync(5000);expect(received).toEqual(['finished']);stop();state='live';await vi.advanceTimersByTimeAsync(5000);expect(received).toEqual(['finished']);}finally{vi.useRealTimers()}});
 it('preserves a closed session when the new-session request fails',async()=>{await expect(openNextSession('c','token',async()=>{throw Error('offline')})).rejects.toThrow('offline')});
 it('ignores an in-flight snapshot after its session screen unmounts',async()=>{vi.useFakeTimers();try{let complete!:(value:string)=>void;const apply=vi.fn(),load=vi.fn(()=>new Promise<string>(resolve=>{complete=resolve}));const stop=watchSessionSnapshot(load,apply,()=>{});await vi.advanceTimersByTimeAsync(15000);expect(load).toHaveBeenCalledTimes(1);stop();complete('stale session');await Promise.resolve();expect(apply).not.toHaveBeenCalled()}finally{vi.useRealTimers()}});
});
