import React,{useEffect,useState,useRef} from 'react';
import {useI18n,LanguageSwitcher} from './i18n/react.js';
import {currentRealm} from './realm.js';
const copy={
 en:{title:'Session administration',hint:'End a stuck session without deleting the campaign, or resume its saved table. Quiet games are not automatically considered stuck.',access:'Administrator access',connect:'Connect',refresh:'Refresh',back:'Back',empty:'No sessions',last:'Last activity',none:'No actions recorded',players:'Players',finish:'End session',resume:'Resume saved session',remove:'Disconnect',confirm:'Confirm',cancel:'Cancel',warning:'The campaign, characters, map and journal will be preserved.',live:'Live',lobby:'Preparing',finished:'Ended',preparing:'Preparing',cancelled:'Cancelled',error:'Administrator access is required. Use your Realm administrator access.',done:'Operation completed',pin:'Join code'},
 ru:{title:'Управление сессиями',hint:'Завершите зависшую сессию без удаления кампании или вернитесь к сохранённому столу. Тихая игра не считается зависшей автоматически.',access:'Доступ администратора',connect:'Подключить',refresh:'Обновить',back:'Назад',empty:'Сессий пока нет',last:'Последнее действие',none:'Действий ещё не было',players:'Игроки',finish:'Завершить сессию',resume:'Возобновить сохранённую сессию',remove:'Отключить',confirm:'Подтвердить',cancel:'Отмена',warning:'Кампания, персонажи, карта и журнал сохранятся.',live:'Идёт игра',lobby:'Подготовка',finished:'Завершена',preparing:'Подготовка',cancelled:'Отменена',error:'Нужен доступ администратора пространства. Введите свой ключ администратора.',done:'Операция выполнена',pin:'Код подключения'},
 es:{title:'Administración de sesiones',hint:'Finaliza una sesión bloqueada sin borrar la campaña o reanuda la mesa guardada. Una partida silenciosa no se considera bloqueada automáticamente.',access:'Acceso de administrador',connect:'Conectar',refresh:'Actualizar',back:'Volver',empty:'No hay sesiones',last:'Última acción',none:'Sin acciones',players:'Jugadores',finish:'Finalizar sesión',resume:'Reanudar sesión guardada',remove:'Desconectar',confirm:'Confirmar',cancel:'Cancelar',warning:'Se conservarán la campaña, los personajes, el mapa y el diario.',live:'En juego',lobby:'Preparación',finished:'Finalizada',preparing:'Preparación',cancelled:'Cancelada',error:'Se requiere acceso de administrador del espacio.',done:'Operación completada',pin:'Código de acceso'},
 ja:{title:'セッション管理',hint:'キャンペーンを削除せずに停止したセッションを終了するか、保存済みの卓を再開します。静かなゲームを自動的に停止と判定しません。',access:'管理者アクセス',connect:'接続',refresh:'更新',back:'戻る',empty:'セッションはありません',last:'最後のゲーム操作',none:'操作なし',players:'プレイヤー',finish:'セッションを終了',resume:'保存済みセッションを再開',remove:'切断',confirm:'確認',cancel:'キャンセル',warning:'キャンペーン、キャラクター、マップ、記録は保存されます。',live:'プレイ中',lobby:'準備中',finished:'終了',preparing:'準備中',cancelled:'キャンセル済み',error:'スペースの管理者アクセスが必要です。',done:'操作が完了しました',pin:'参加コード'},
 'zh-CN':{title:'会话管理',hint:'结束卡住的会话而不删除战役，或恢复已保存的游戏桌。安静的游戏不会自动被判定为卡住。',access:'管理员访问',connect:'连接',refresh:'刷新',back:'返回',empty:'暂无会话',last:'最后一次游戏操作',none:'暂无操作',players:'玩家',finish:'结束会话',resume:'恢复已保存的会话',remove:'断开连接',confirm:'确认',cancel:'取消',warning:'战役、角色、地图和日志将保留。',live:'游戏中',lobby:'准备中',finished:'已结束',preparing:'准备中',cancelled:'已取消',error:'需要空间管理员权限。',done:'操作已完成',pin:'加入代码'},
 ko:{title:'세션 관리',hint:'캠페인을 삭제하지 않고 멈춘 세션을 종료하거나 저장된 테이블을 재개합니다. 조용한 게임은 자동으로 멈춘 것으로 판단하지 않습니다.',access:'관리자 접근',connect:'연결',refresh:'새로 고침',back:'뒤로',empty:'세션 없음',last:'마지막 게임 행동',none:'기록된 행동 없음',players:'플레이어',finish:'세션 종료',resume:'저장된 세션 재개',remove:'연결 해제',confirm:'확인',cancel:'취소',warning:'캠페인, 캐릭터, 지도와 기록은 보존됩니다.',live:'진행 중',lobby:'준비 중',finished:'종료됨',preparing:'준비 중',cancelled:'취소됨',error:'공간 관리자 접근 권한이 필요합니다.',done:'작업 완료',pin:'참가 코드'},
};
export function sessionAdminTitle(locale:keyof typeof copy){return copy[locale].title}
type Session={id:string;campaignName:string;state:'live'|'lobby'|'preparing'|'finished'|'cancelled';lastActivityAt:string|null;pin?:string;participants:{id:string;displayName:string}[]};
export function SessionAdmin({request,onBack}:{request:(path:string,init?:RequestInit)=>Promise<unknown>;onBack:()=>void}){
 const {locale}=useI18n(),c=copy[locale],key=`masterhost.realmAdmin.${currentRealm()}`;
 const [token,setToken]=useState(()=>sessionStorage.getItem(key)??''),[sessions,setSessions]=useState<Session[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[pending,setPending]=useState<{session:Session;action:'finish'|'resume'|'remove';participantId?:string}>();
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(pending)dialog.current?.showModal()},[pending]);
 const headers={authorization:`Bearer ${token}`,'content-type':'application/json'};
 async function load(){setBusy(true);try{const data=await request('/admin/sessions',{headers});setSessions(data as Session[]);setConnected(true);setMessage('')}catch{setConnected(false);setMessage(c.error)}finally{setBusy(false)}}
 useEffect(()=>{if(token)void load()},[]);
 async function manage(){if(!pending)return;setBusy(true);try{await request(`/admin/sessions/${pending.session.id}/manage`,{method:'POST',headers,body:JSON.stringify({action:pending.action,expectedState:pending.session.state,participantId:pending.participantId})});setPending(undefined);await load();setMessage(c.done)}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 return <main className="packCreator"><header className="titleRow"><h1>{c.title}</h1><LanguageSwitcher/><button className="secondary" onClick={onBack}>{c.back}</button></header><p>{c.hint}</p>{message&&<p role="status">{message}</p>}
 {!connected&&<section><label>{c.access}<input type="password" value={token} onChange={e=>setToken(e.target.value)}/></label><button disabled={busy||!token} onClick={()=>{sessionStorage.setItem(key,token);void load()}}>{c.connect}</button></section>}
 {connected&&<><button className="secondary" disabled={busy} onClick={()=>void load()}>{c.refresh}</button>{sessions.length===0&&<p>{c.empty}</p>}{sessions.map(s=><section key={s.id}><h2>{s.campaignName}</h2><p>{c[s.state]} · {c.players}: {s.participants.length}</p><p>{c.last}: {s.lastActivityAt?new Date(s.lastActivityAt).toLocaleString(locale):c.none}</p>{s.pin&&<p>{c.pin}: <strong>{s.pin}</strong></p>}<div className="actions">{['live','lobby','preparing'].includes(s.state)&&<button disabled={busy} onClick={()=>setPending({session:s,action:'finish'})}>{c.finish}</button>}{s.state==='finished'&&<button disabled={busy} onClick={()=>setPending({session:s,action:'resume'})}>{c.resume}</button>}</div>{s.participants.map(p=><div className="titleRow" key={p.id}><span>{p.displayName}</span>{['live','lobby'].includes(s.state)&&<button className="secondary" disabled={busy} onClick={()=>setPending({session:s,action:'remove',participantId:p.id})}>{c.remove}</button>}</div>)}</section>)}</>}
 {pending&&<dialog ref={dialog} onCancel={()=>setPending(undefined)} aria-label={c[pending.action]}><h2>{c[pending.action]} · {pending.session.campaignName}</h2><p>{c.warning}</p><button disabled={busy} onClick={()=>void manage()}>{c.confirm}</button><button className="secondary" disabled={busy} onClick={()=>setPending(undefined)}>{c.cancel}</button></dialog>}
 </main>;
}
