import React, { useEffect, useMemo, useState } from "react";
import { LanguageSwitcher, useI18n } from "./i18n/react.js";

type Complexity = "beginner" | "intermediate" | "advanced";
type Pattern = { id: string; name: string; summary: string };
export type UniverseCatalogItem = { id: string; name: string; summary: string; genres: string[]; tones: string[]; complexity: Complexity; recommendedPlayers: { min: number; max: number }; gameLoop: string[]; patterns: Pattern[]; targetPack: { id: string; version: string }; sourceLocale?: string; fallbackLocales?: string[]; availability: "planned" | "ready"; playToday?: { patternId: string; campaignKitId: string; visualThemeId: string } };
export type UniverseQuickStart = { universeId: string; universeName: string; basePack: { id: string; version: string }; patternId: string; campaignKitId: string; visualThemeId: string };
type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">;
type Filters = { query: string; genre: string; tone: string; complexity: string };
const handoffKey = "masterhost.universeQuickStart.v1";

export const genreLabel=(value:string)=>value.replaceAll("-"," ");
export function filterUniverseCatalog(items: UniverseCatalogItem[], filters: Filters) {
  const query = filters.query.trim().toLowerCase();
  return items.filter(item => (!query || [item.name, item.summary, ...item.gameLoop, ...item.patterns.flatMap(pattern => [pattern.name, pattern.summary])].join(" ").toLowerCase().includes(query)) && (!filters.genre || item.genres.some(value=>genreLabel(value)===genreLabel(filters.genre))) && (!filters.tone || item.tones.includes(filters.tone)) && (!filters.complexity || item.complexity === filters.complexity));
}

export function writeQuickStartHandoff(storage: StorageLike, value: UniverseQuickStart) { storage.setItem(handoffKey, JSON.stringify(value)); }
export function readQuickStartHandoff(storage: StorageLike): UniverseQuickStart | undefined {
  const raw = storage.getItem(handoffKey); storage.removeItem(handoffKey); if (!raw) return undefined;
  try { const value = JSON.parse(raw); return value?.universeId && value?.universeName && value?.basePack?.id && value?.basePack?.version && value?.patternId && value?.campaignKitId && value?.visualThemeId ? value : undefined; } catch { return undefined; }
}

export async function attemptUniversePlay(value:UniverseQuickStart,onPlay:(value:UniverseQuickStart)=>void|Promise<void>):Promise<string|undefined>{try{await onPlay(value);return undefined}catch(error){return error instanceof Error?error.message:String(error)}}
export function UniverseCatalog({ request, onBack, onAdvanced, onPlay, initialItems, initialSelectedId }: { request: (path: string) => Promise<any>; onBack: () => void; onAdvanced: () => void; onPlay: (value: UniverseQuickStart) => void | Promise<void>; initialItems?: UniverseCatalogItem[]; initialSelectedId?: string }) {
  const { t, locale } = useI18n(), [items, setItems] = useState<UniverseCatalogItem[]>(initialItems ?? []), [selectedId, setSelectedId] = useState(initialSelectedId ?? ""), [filters, setFilters] = useState<Filters>({ query: "", genre: "", tone: "", complexity: "" }), [error, setError] = useState(""), [playing,setPlaying]=useState(false);
  useEffect(() => { if (!initialItems) void request("/universes").then(setItems).catch(reason => setError(reason instanceof Error ? reason.message : String(reason))); }, [initialItems]);
  const visible = useMemo(() => filterUniverseCatalog(items, filters), [items, filters]), selected = items.find(item => item.id === selectedId);
  const genres = [...new Set(items.flatMap(item => item.genres.map(genreLabel)))].sort(), tones = [...new Set(items.flatMap(item => item.tones))].sort();
  const play = async (item: UniverseCatalogItem) => { if (item.availability !== "ready" || !item.playToday) return; const value: UniverseQuickStart = { universeId: item.id, universeName: item.name, basePack: item.targetPack, ...item.playToday }; if (typeof sessionStorage !== "undefined") writeQuickStartHandoff(sessionStorage, value); setPlaying(true);setError("");setError(await attemptUniversePlay(value,onPlay)??"");setPlaying(false); };
  return <main className="universeCatalog">
    <header className="productHeader compact"><div><p className="eyebrow">{t("universe.eyebrow")}</p><h1>{t("universe.title")}</h1><p>{t("universe.subtitle")}</p></div><div className="actions"><LanguageSwitcher/><button className="secondary" onClick={onAdvanced}>{t("universe.advanced")}</button><button className="secondary" onClick={onBack}>{t("common.back")}</button></div></header>
    {error && <section role="alert"><p className="error">{/role required|authorization required/i.test(error)?t("universe.accessNeeded"):error}</p>{/role required|authorization required/i.test(error)&&<button onClick={()=>{location.hash="realm"}}>{t("home.realm")}</button>}</section>}
    <section className="universeFilters"><label>{t("universe.search")}<input value={filters.query} onChange={event => setFilters({ ...filters, query: event.target.value })}/></label><label>{t("universe.genre")}<select value={filters.genre} onChange={event => setFilters({ ...filters, genre: event.target.value })}><option value="">{t("universe.all")}</option>{genres.map(value => <option key={value}>{value}</option>)}</select></label><label>{t("universe.tone")}<select value={filters.tone} onChange={event => setFilters({ ...filters, tone: event.target.value })}><option value="">{t("universe.all")}</option>{tones.map(value => <option key={value}>{value}</option>)}</select></label><label>{t("universe.complexity")}<select value={filters.complexity} onChange={event => setFilters({ ...filters, complexity: event.target.value })}><option value="">{t("universe.all")}</option>{["beginner", "intermediate", "advanced"].map(value => <option key={value}>{value}</option>)}</select></label></section>
    <section className="universeLayout"><div className="universeGrid">{visible.map(item => <article className={selectedId === item.id ? "selected" : ""} key={item.id}><div className="universeCardTop"><span className={`availability ${item.availability}`}>{t(item.availability === "ready" ? "universe.ready" : "universe.planned")}</span><span>{item.complexity}</span></div><h2>{item.name}</h2><p>{item.summary}</p><p>{item.genres.map(value => <span className="tag" key={value}>{value}</span>)}</p><button className="secondary" onClick={() => setSelectedId(item.id)}>{t("universe.preview")}</button><button disabled={playing || item.availability !== "ready" || !item.playToday} onClick={() => play(item)}>{item.availability === "ready" ? t("universe.playToday") : t("universe.planned")}</button></article>)}</div>
    {selected && <aside className="universePreview"><button className="tiny secondary" onClick={() => setSelectedId("")}>{t("universe.close")}</button><p className="eyebrow">{selected.genres.join(" · ")}</p><h2>{selected.name}</h2><p>{selected.summary}</p>{selected.fallbackLocales?.includes(locale)&&<p className="notice">{t("universe.contentFallback",{locale:selected.sourceLocale??"en"})}</p>}<dl><div><dt>{t("universe.players")}</dt><dd>{selected.recommendedPlayers.min}–{selected.recommendedPlayers.max}</dd></div><div><dt>{t("universe.complexity")}</dt><dd>{selected.complexity}</dd></div></dl><h3>{t("universe.loop")}</h3><ol className="gameLoop">{selected.gameLoop.map(step => <li key={step}>{step}</li>)}</ol><h3>{t("universe.patterns")}</h3>{selected.patterns.map(pattern => <article key={pattern.id}><h4>{pattern.name}</h4><p>{pattern.summary}</p></article>)}<button disabled={playing || selected.availability !== "ready" || !selected.playToday} onClick={() => play(selected)}>{selected.availability === "ready" ? t("universe.playToday") : t("universe.planned")}</button></aside>}</section>
  </main>;
}
