import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe, expect, it, vi} from 'vitest';
import {I18nProvider} from './i18n/react.js';
import {UniverseCatalog,filterUniverseCatalog, type UniverseCatalogItem} from './universe-catalog.js';

const item:UniverseCatalogItem={id:'classic-fantasy',name:'Classic Fantasy',summary:'Heroic journeys through rival kingdoms, dangerous roads, ancient ruins, and bright fellowship.',genres:['fantasy'],tones:['heroic'],complexity:'beginner',recommendedPlayers:{min:2,max:6},gameLoop:['travel'],patterns:[{id:'border-kingdoms',name:'Border Kingdoms',summary:'Defend small realms where wilderness, monsters, and old grudges meet.'}],targetPack:{id:'masterhost.classic-fantasy',version:'2.0.0'},availability:'ready',playToday:{patternId:'border-kingdoms',campaignKitId:'kit.border-watch',visualThemeId:'theme.illustrated'}};
function render(locale:string){Object.defineProperty(globalThis,'location',{value:{search:`?lang=${locale}`},configurable:true});Object.defineProperty(globalThis,'localStorage',{value:{getItem:()=>null,setItem:()=>undefined},configurable:true});return renderToStaticMarkup(React.createElement(I18nProvider,{children:React.createElement(UniverseCatalog,{request:async()=>[],onBack:()=>undefined,onAdvanced:()=>undefined,onPlay:()=>undefined,initialItems:[item],initialSelectedId:item.id})}));}
describe('selected locale applies to universe authored content',()=>{
 it('renders Russian universe and pattern descriptions with canonical choice identities',()=>{const html=render('ru');expect(html).not.toContain('Heroic journeys through');expect(html).not.toContain('Defend small realms');expect(html).not.toContain('>Classic Fantasy<');expect(html).toContain('value="beginner"');expect(html).toContain('value="fantasy"');expect(item.name).toBe('Classic Fantasy');expect(item.patterns[0]!.id).toBe('border-kingdoms');});
 it.each(['ru','es','ja','zh-CN','ko'])('renders authored descriptions in %s while retaining canonical IDs',locale=>{const html=render(locale);expect(html).not.toContain(item.summary);expect(html).not.toContain(item.patterns[0]!.summary);expect(html).toContain('value="fantasy"');expect(html).toContain('value="beginner"');expect(item.targetPack.id).toBe('masterhost.classic-fantasy');});
 it('searches both translated and canonical copy with stable genre/complexity filters',()=>{const filters={query:'Классическое',genre:'fantasy',tone:'heroic',complexity:'beginner'};expect(filterUniverseCatalog([item],filters,text=>text==='Classic Fantasy'?'Классическое фэнтези':text).map(value=>value.id)).toEqual(['classic-fantasy']);expect(filterUniverseCatalog([item],{...filters,query:'Classic Fantasy'},text=>text==='Classic Fantasy'?'Классическое фэнтези':text).map(value=>value.id)).toEqual(['classic-fantasy']);});
 it('renders original authored content in English',()=>{expect(render('en')).toContain('Heroic journeys through');});
});

import {CharacterBuilder,loadCharacterSchema} from './character-builder.js';
import {CharacterChoices} from './character-choice.js';
import {characterSheetValues} from './game.js';
import {createContentTranslator} from './i18n/content.js';
describe('custom Pack authored labels and user content',()=>{
 const schema={localization:{sourceLocale:'en',strings:{en:{step:'Choose a role',role:'Role',scout:'Scout'},ru:{step:'Выберите роль',role:'Роль',scout:'Разведчик'}}},steps:[{id:'role',title:'Choose a role',fields:[{id:'name',label:'Name',type:'text',default:'Scout'},{id:'role',label:'Role',type:'choice',default:'scout',options:[{value:'scout',label:'Scout'}]},{id:'bio',label:'Story',type:'text'}]}]};
 it('renders own Pack labels while retaining canonical option and entered free text',()=>{render('ru');const html=renderToStaticMarkup(React.createElement(I18nProvider,{children:React.createElement(CharacterBuilder,{schema,ownerKey:'owner',onCreated:()=>undefined})}));expect(html).toContain('Выберите роль');expect(html).toContain('Роль');expect(html).toContain('Разведчик');expect(html).toContain('value="scout"');expect(html).toContain('value="Scout"');expect(schema.steps[0]!.fields[1]!.default).toBe('scout');});
 it('localizes selected character choice labels without rewriting player name and free text',()=>{render('ru');const html=renderToStaticMarkup(React.createElement(I18nProvider,{children:React.createElement(CharacterChoices,{schema,characters:[{id:'pc-1',displayName:'Scout',values:{name:'Scout',role:'scout',bio:'Scout'},compatibility:{compatible:true}}],onChoose:()=>undefined})}));expect(html).toContain('<h3>Scout</h3>');expect(html).toContain('Роль: Разведчик');expect(html).toContain('Story: Scout');});
 it('switches display language without changing selected values',()=>{const values={name:'Scout',role:'scout',bio:'Scout'};const before=JSON.stringify(values);const ru=characterSheetValues(schema,values,createContentTranslator('ru',{},schema)),en=characterSheetValues(schema,values,createContentTranslator('en',{},schema));expect(ru.find(field=>field.id==='role')?.value).toBe('Разведчик');expect(en.find(field=>field.id==='role')?.value).toBe('Scout');expect(ru.find(field=>field.id==='bio')?.value).toBe('Scout');expect(JSON.stringify(values)).toBe(before);});
 it('uses the source universe scope for a generated game Character schema',async()=>{render('ru');vi.stubGlobal('fetch',async()=>({ok:true,json:async()=>({pack:{id:'masterhost.game.generated',universe:{id:'space-opera'}},schema:{steps:[{id:'crew',title:'Crew',fields:[{id:'crewRole',label:'Crew role',type:'choice',required:true,options:[{value:'pilot',label:'Rescue Pilot'}]}]}],calculated:[{id:'readiness',operation:'sum',fields:['nerve']}]}})}));try{const loaded=await loadCharacterSchema('session-1');const html=renderToStaticMarkup(React.createElement(I18nProvider,{children:React.createElement(CharacterBuilder,{schema:loaded.schema,ownerKey:'owner',onCreated:()=>undefined})}));expect(html).toContain('Роль в команде');expect(html).toContain('Спасательный пилот');expect(html).toContain('Готовность: 0');expect(html).toContain('value="pilot"');expect(loaded.schema.manifest.id).toBe('masterhost.game.generated');}finally{vi.unstubAllGlobals();}});
});

import {QuickGameBuilder} from './quick-game-builder.js';
describe('localized automatic game names',()=>{it('starts a new Russian game with a translated suggested name',()=>{render('ru');Object.defineProperty(globalThis,'sessionStorage',{value:{getItem:()=>null,removeItem:()=>undefined},configurable:true});const html=renderToStaticMarkup(React.createElement(I18nProvider,{children:React.createElement(QuickGameBuilder,{pack:{manifest:{id:'masterhost.classic-fantasy',version:'2.0.0'},questions:[]},request:async()=>[],requestMedia:async()=>new Blob(),onWorld:()=>undefined,onBack:()=>undefined,onAdvanced:()=>undefined})}));expect(html).not.toContain('Untitled One-shot');});});
