#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; CONTAINER="masterhost-m14-gate-$$"; PG_PORT="${M14_PG_PORT:-55474}"; API_PORT="${M14_API_PORT:-8181}"; WEB_PORT="${M14_WEB_PORT:-8182}"; CDP_PORT="${M14_CDP_PORT:-9354}"
STATE="${TMPDIR:-/tmp}/masterhost-m14-state-$$.json"; ARCHIVE="${TMPDIR:-/tmp}/masterhost-m14-game-$$.mhgame"; SERVER_LOG="${TMPDIR:-/tmp}/masterhost-m14-server-$$.log"; WEB_LOG="${TMPDIR:-/tmp}/masterhost-m14-web-$$.log"; SERVER_PID=""; WEB_PID=""
cleanup(){ [[ -z "$WEB_PID" ]] || { kill "$WEB_PID" 2>/dev/null || true; wait "$WEB_PID" 2>/dev/null || true; }; [[ -z "$SERVER_PID" ]] || { kill "$SERVER_PID" 2>/dev/null || true; wait "$SERVER_PID" 2>/dev/null || true; }; docker rm -f "$CONTAINER" >/dev/null 2>&1 || true; rm -rf "$STATE" "$ARCHIVE" "$SERVER_LOG" "$WEB_LOG" "${TMPDIR:-/tmp}/masterhost-m14-empty-$$"; }
trap cleanup EXIT; cd "$ROOT"; ./node_modules/.bin/tsc --noEmit -p tsconfig.json; ./node_modules/.bin/vitest run; (cd apps/web && ./node_modules/.bin/vite build)
docker run --rm --name "$CONTAINER" -e POSTGRES_USER=masterhost -e POSTGRES_PASSWORD=masterhost -e POSTGRES_DB=m14_a -p "$PG_PORT:5432" -d postgres:17-alpine >/dev/null; for _ in {1..30}; do docker exec "$CONTAINER" pg_isready -U masterhost -d m14_a >/dev/null 2>&1 && break; sleep 1; done; docker exec "$CONTAINER" createdb -U masterhost m14_b; docker exec "$CONTAINER" createdb -U masterhost m14_tests
TEST_DATABASE_URL="postgresql://masterhost:masterhost@127.0.0.1:$PG_PORT/m14_tests" ./node_modules/.bin/vitest run tests/m14-mhgame.test.ts tests/m10-game-descriptor-repository.test.ts
start_server(){ local db="$1" assets="${2:-game-assets/library}" pack_path="${3:-worldpacks/classic-fantasy-test}"; DATABASE_URL="postgresql://masterhost:masterhost@127.0.0.1:$PG_PORT/$db" PORT="$API_PORT" GAME_ASSET_LIBRARY_PATH="$assets" WORLD_PACK_PATH="$pack_path" MASTERHOST_DEFAULT_REALM_ADMIN=local-default-realm-admin ./node_modules/.bin/tsx apps/server/src/index.ts >"$SERVER_LOG" 2>&1 & SERVER_PID=$!; for _ in {1..30}; do curl -sf "http://127.0.0.1:$API_PORT/health" >/dev/null && return; sleep 1; done; cat "$SERVER_LOG" >&2; return 1; }
run_phase(){ M14_PHASE="$1" M14_STATE_FILE="$STATE" M14_ARCHIVE_FILE="$ARCHIVE" MASTERHOST_API_URL="http://127.0.0.1:$API_PORT/api" node scripts/m14-acceptance.mjs; }
start_server m14_a game-assets/library worldpacks/space-opera; run_phase export; kill "$SERVER_PID"; wait "$SERVER_PID" 2>/dev/null || true; SERVER_PID=""; mkdir -p "${TMPDIR:-/tmp}/masterhost-m14-empty-$$"; start_server m14_b "${TMPDIR:-/tmp}/masterhost-m14-empty-$$"; run_phase import; kill "$SERVER_PID"; wait "$SERVER_PID" 2>/dev/null || true; SERVER_PID=""; start_server m14_b "${TMPDIR:-/tmp}/masterhost-m14-empty-$$"; run_phase verify
(cd apps/web && exec env VITE_API_URL="http://127.0.0.1:$API_PORT/api" ./node_modules/.bin/vite --host 127.0.0.1 --port "$WEB_PORT") >"$WEB_LOG" 2>&1 & WEB_PID=$!; for _ in {1..30}; do curl -sf "http://127.0.0.1:$WEB_PORT/?realm=default" >/dev/null && break; sleep 1; done
M14_STATE_FILE="$STATE" M14_WEB_URL="http://127.0.0.1:$WEB_PORT" M14_CDP_PORT="$CDP_PORT" node scripts/m14-browser-acceptance.mjs
echo "M14 gate passed: transport security, all tests, build, two clean installations, empty source library, restart, gameplay, browser edit and atomic rejection."
