import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import postgres from "postgres";
import { endEncounter, startEncounter } from "@masterhost/game-runtime";
import { ActorStateRepository, EncounterRepository, GameRepository, RuntimeMutationRepository, RuntimeReplayRepository, RuntimeRepository } from "@masterhost/persistence";

const url = process.env.DATABASE_URL ?? "postgresql://masterhost:masterhost@localhost:5432/masterhost";
const sql = postgres(url);
const sessionId = randomUUID(), actorId = randomUUID();
const runtime = new RuntimeRepository(url), actors = new ActorStateRepository(url), encounters = new EncounterRepository(url), game = new GameRepository(url), mutations = new RuntimeMutationRepository(url), replay = new RuntimeReplayRepository(url);
try {
  await runtime.migrate();
  await game.migrate();
  await actors.migrate();
  await encounters.migrate();
  await mutations.migrate();
  await replay.migrate();
  await sql`insert into sessions(id,realm_id,campaign_id,state) values(${sessionId},${randomUUID()},${randomUUID()},'finished')`;
  const initial = { actorId, resources: { health: 20 }, effects: [] };
  await mutations.commit(sessionId, [{ type: "ActorInitialized", payload: { ...initial } }], [initial]);
  const started = startEncounter({ sessionId, participantIds: [actorId], policy: "none" });
  await mutations.commit(sessionId, started.events, [], started.encounter);
  const ended = endEncounter(started.encounter);
  await mutations.commit(sessionId, ended.events, [], ended.encounter, { encounterVersion: 1 });
  const checkpoint = await replay.createSnapshot(sessionId);
  assert.equal(checkpoint.eventCount, 4);
  assert.deepEqual(await replay.createSnapshot(sessionId), checkpoint);
  const afterDamage = { ...initial, resources: { health: 15 } };
  await mutations.commit(sessionId, [{ type: "ResourceChanged", payload: { actorId, resource: "health", before: 20, after: 15 } }], [afterDamage], undefined, { actorVersions: { [actorId]: 1 } });
  assert.deepEqual(await replay.verifyFromSnapshot(sessionId), { matching: true, eventCount: 5, actorIds: [], encounterIds: [], issues: [], snapshotSequence: checkpoint.lastSequence, replayedEventCount: 1 });
  await sql`update actor_runtime_state set state=jsonb_set(state,'{resources,health}','99'::jsonb) where session_id=${sessionId} and actor_id=${actorId}`;
  await sql`update encounters set state=jsonb_set(state,'{round}','9'::jsonb) where session_id=${sessionId} and id=${started.encounter.id}`;
  assert.deepEqual((await replay.verify(sessionId)).actorIds, [actorId]);
  assert.deepEqual((await replay.verify(sessionId)).encounterIds, [started.encounter.id]);
  assert.deepEqual((await replay.verifyFromSnapshot(sessionId)).actorIds, [actorId]);
  assert.deepEqual((await replay.verifyFromSnapshot(sessionId)).encounterIds, [started.encounter.id]);
  await assert.rejects(replay.createSnapshot(sessionId), error => error instanceof Error && "statusCode" in error && error.statusCode === 409);
  const repaired = await replay.repairFinishedSession(sessionId);
  assert.equal(repaired.repaired, true);
  assert.deepEqual(repaired.actorIds, [actorId]);
  assert.deepEqual(repaired.encounterIds, [started.encounter.id]);
  assert.equal((await actors.get(sessionId, actorId))?.resources.health, 15);
  assert.equal((await encounters.get(started.encounter.id))?.round, 0);
  assert.equal((await replay.verify(sessionId)).matching, true);
  assert.equal((await replay.verifyFromSnapshot(sessionId)).matching, true);
  assert.equal((await replay.repairFinishedSession(sessionId)).repaired, false);
  assert.equal((await sql`select count(*)::int as count from runtime_repair_log where session_id=${sessionId}`)[0]?.count, 1);
  await sql`update sessions set state='live' where id=${sessionId}`;
  await assert.rejects(replay.repairFinishedSession(sessionId), error => error instanceof Error && "statusCode" in error && error.statusCode === 409);
  await sql`update sessions set state='finished' where id=${sessionId}`;
  await game.event(sessionId, "UnknownMutation", {});
  await assert.rejects(replay.repairFinishedSession(sessionId), error => error instanceof Error && "statusCode" in error && error.statusCode === 409);
  console.log("Runtime recovery smoke passed: checkpoint replay, corruption detection, finished-session repair, audit, and unsafe replay rejection.");
} finally {
  await sql`delete from runtime_repair_log where session_id=${sessionId}`;
  await sql`delete from runtime_replay_snapshots where session_id=${sessionId}`;
  await sql`delete from runtime_command_receipts where session_id=${sessionId}`;
  await sql`delete from game_events where session_id=${sessionId}`;
  await sql`delete from actor_runtime_state where session_id=${sessionId}`;
  await sql`delete from encounters where session_id=${sessionId}`;
  await sql`delete from sessions where id=${sessionId}`;
  await Promise.all([sql.end(), runtime.close(), actors.close(), encounters.close(), game.close(), mutations.close(), replay.close()]);
}
