import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";

const base = process.env.MASTERHOST_API_URL ?? "http://localhost:8080/api";
async function call(path, body, token, key) {
  const response = await fetch(`${base}${path}`, { method: body === undefined ? "GET" : "POST", headers: { ...(body === undefined ? {} : { "content-type": "application/json" }), ...(token ? { authorization: `Bearer ${token}` } : {}), ...(key ? { "idempotency-key": key } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  return { status: response.status, data: await response.json() };
}
const valid = async (path, body, token, key) => { const result = await call(path, body, token, key); assert.ok(result.status >= 200 && result.status < 300, `${path}: ${result.status} ${JSON.stringify(result.data)}`); return result.data; };

const pack = await valid("/pack");
assert.equal(pack.manifest.id, "masterhost.classic-fantasy-test");
const world = await valid("/worlds", { seed: "runtime-smoke", choices: {} });
const campaign = await valid("/campaigns", { worldId: world.id, name: "Runtime smoke" });
assert.equal((await call(`/campaigns/${campaign.id}/sessions`, {})).status, 403);
const session = await valid(`/campaigns/${campaign.id}/sessions`, {}, campaign.gmToken);
assert.match(session.pin, /^\d{5}$/);
assert.equal((await valid("/join/resolve", { pin: session.pin })).session.id, session.id);
const player = await valid(`/sessions/${session.id}/join`, { pin: session.pin, displayName: "Smoke player" });
assert.ok(player.accessToken);
assert.equal((await call(`/sessions/${session.id}/join`, { pin: "00000", displayName: "Intruder" })).status >= 400, true);
assert.equal((await call(`/sessions/${session.id}`)).status, 403);
const ownerKey = randomUUID();
assert.equal((await call("/characters")).status, 403);
assert.equal((await call("/characters", { ownerKey, values: { name: "Aria", archetype: "invalid" } })).status, 400);
const character = await valid("/characters", { ownerKey, values: { name: "Aria", archetype: "warrior" } });
assert.equal((await call(`/participants/${player.id}/character`, { characterId: character.id, ownerKey: "wrong" })).status, 403);
assert.equal((await call(`/participants/${player.id}/character`, { characterId: character.id, ownerKey })).status, 403);
await valid(`/participants/${player.id}/character`, { characterId: character.id, ownerKey }, player.accessToken);
assert.equal((await call(`/participants/${player.id}/ready`, { ready: true })).status, 403);
await valid(`/participants/${player.id}/ready`, { ready: true }, player.accessToken);
assert.equal((await call(`/sessions/${session.id}/state`, { state: "live" })).status, 403);
await valid(`/sessions/${session.id}/state`, { state: "live" }, campaign.gmToken);
assert.equal((await call("/join/resolve", { pin: session.pin })).status, 200);
const playerInitKey = randomUUID();
const initializedPlayer = await valid(`/sessions/${session.id}/participants/${player.id}/initialize`, {}, campaign.gmToken, playerInitKey);
assert.deepEqual(await valid(`/sessions/${session.id}/participants/${player.id}/initialize`, {}, campaign.gmToken, playerInitKey), initializedPlayer);
assert.equal((await call(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [randomUUID()], actionId: "take-damage" }, campaign.gmToken)).status, 400);
const damageBody = { actorId: player.id, targetActorIds: [player.id], actionId: "take-damage" }, damageKey = randomUUID();
assert.equal((await call(`/sessions/${session.id}/actions`, damageBody, campaign.gmToken, "invalid key")).status, 400);
const firstDamage = await valid(`/sessions/${session.id}/actions`, damageBody, campaign.gmToken, damageKey);
assert.deepEqual(await valid(`/sessions/${session.id}/actions`, damageBody, campaign.gmToken, damageKey), firstDamage);
assert.equal((await call(`/sessions/${session.id}/actions`, { ...damageBody, actionId: "heal" }, campaign.gmToken, damageKey)).status, 409);
await valid(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [player.id], actionId: "poison" }, campaign.gmToken);
const checkBody = { participantId: player.id, checkId: "perception", difficulty: 12 }, checkKey = randomUUID();
const repeatedChecks = await Promise.all(Array.from({ length: 2 }, () => call(`/sessions/${session.id}/checks`, checkBody, campaign.gmToken, checkKey)));
assert.deepEqual(repeatedChecks.map(result => result.status), [200, 200]);
assert.deepEqual(repeatedChecks[0].data, repeatedChecks[1].data);
const check = repeatedChecks[0].data;
assert.deepEqual(await valid(`/sessions/${session.id}/checks`, checkBody, campaign.gmToken, checkKey), check);
assert.equal((await call(`/sessions/${session.id}/checks`, { ...checkBody, difficulty: 13 }, campaign.gmToken, checkKey)).status, 409);
assert.equal((await call(`/checks/${check.id}/roll`, {})).status, 403);
const rolls = await Promise.all(Array.from({ length: 8 }, () => call(`/checks/${check.id}/roll`, {}, player.accessToken)));
assert.ok(rolls.every(result => result.status === 200));
for (const result of rolls) assert.deepEqual(result.data, rolls[0].data);
const checkEvents = await valid(`/sessions/${session.id}/events`, undefined, campaign.gmToken);
assert.equal(checkEvents.filter(event => event.type === "CheckRequested" && event.payload.id === check.id).length, 1);
assert.equal(checkEvents.filter(event => event.type === "DiceRolled" && event.payload.requestId === check.id).length, 1);
assert.equal(checkEvents.filter(event => event.type === "CheckResolved" && event.payload.requestId === check.id).length, 1);
assert.equal((await call(`/sessions/${session.id}/runtime/snapshots`, {})).status, 403);
const runtimeSnapshot = await valid(`/sessions/${session.id}/runtime/snapshots`, {}, campaign.gmToken);
assert.ok(runtimeSnapshot.lastSequence > 0);
assert.deepEqual(await valid(`/sessions/${session.id}/runtime/snapshots`, {}, campaign.gmToken), runtimeSnapshot);
async function websocketSnapshot(token) {
  return new Promise((resolve, reject) => {
    const socket = new WebSocket(`ws://localhost:8080/ws/sessions/${session.id}`);
    const timeout = setTimeout(() => { socket.close(); reject(Error("WebSocket timeout")); }, 3000);
    socket.addEventListener("open", () => socket.send(JSON.stringify({ type: "authenticate", token })));
    socket.addEventListener("message", event => { clearTimeout(timeout); socket.close(); resolve(JSON.parse(event.data)); });
    socket.addEventListener("close", event => { clearTimeout(timeout); if (event.code === 1008) resolve({ denied: true }); });
    socket.addEventListener("error", error => { clearTimeout(timeout); reject(error); });
  });
}
assert.equal((await websocketSnapshot("wrong")).denied, true);
const snapshot = await websocketSnapshot(player.accessToken);
assert.equal(snapshot.type, "session.snapshot");
assert.equal(snapshot.payload.session.id, session.id);
assert.ok(!JSON.stringify(snapshot).includes(player.accessToken));
const otherPlayer = await valid(`/sessions/${session.id}/join`, { pin: session.pin, displayName: "Other player" });
assert.equal((await call(`/participants/${player.id}/ready`, { ready: false }, otherPlayer.accessToken)).status, 403);
assert.equal((await call(`/sessions/${session.id}/participants/${player.id}/checks`, undefined, otherPlayer.accessToken)).status, 403);
const otherOwnerKey = randomUUID();
const otherCharacter = await valid("/characters", { ownerKey: otherOwnerKey, values: { name: "Borin", archetype: "scholar" } });
await valid(`/participants/${otherPlayer.id}/character`, { characterId: otherCharacter.id, ownerKey: otherOwnerKey }, otherPlayer.accessToken);
await valid(`/sessions/${session.id}/participants/${otherPlayer.id}/initialize`, {}, campaign.gmToken);
assert.equal((await call(`/sessions/${session.id}/actors`, { templateId: "goblin" }, player.accessToken)).status, 403);
assert.equal((await call(`/sessions/${session.id}/actors`, { templateId: "unknown" }, campaign.gmToken)).status, 400);
const goblinKey = randomUUID(), goblinBody = { templateId: "goblin" };
const goblinAttempts = await Promise.all(Array.from({ length: 2 }, () => call(`/sessions/${session.id}/actors`, goblinBody, campaign.gmToken, goblinKey)));
assert.deepEqual(goblinAttempts.map(result => result.status), [200, 200]);
assert.deepEqual(goblinAttempts[0].data, goblinAttempts[1].data);
const goblin = goblinAttempts[0].data;
assert.equal(goblin.kind, "npc");
assert.equal(goblin.resources.health, 8);
await valid(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [goblin.actorId], actionId: "take-damage" }, campaign.gmToken);
await valid(`/sessions/${session.id}/actions`, { actorId: goblin.actorId, targetActorIds: [goblin.actorId], actionId: "heal" }, campaign.gmToken);
assert.equal((await valid(`/sessions/${session.id}/actors`, undefined, campaign.gmToken)).find(actor => actor.actorId === goblin.actorId).resources.health, 8);
assert.equal((await call(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [player.id, player.id], actionId: "rally" }, campaign.gmToken)).status, 400);
await valid(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [player.id, otherPlayer.id], actionId: "rally" }, campaign.gmToken);
const rallied = await valid(`/sessions/${session.id}/actors`, undefined, campaign.gmToken);
for (const id of [player.id, otherPlayer.id]) assert.ok(rallied.find(actor => actor.actorId === id).effects.some(effect => effect.definitionId === "inspired"));
const before = await valid(`/sessions/${session.id}/actors`, undefined, player.accessToken);
assert.equal(before.find(actor => actor.actorId === player.id).resources.health, 15);
assert.equal(before.find(actor => actor.actorId === player.id).effects[0].remaining, 3);
const competingStarts = await Promise.all(Array.from({ length: 2 }, () => call(`/sessions/${session.id}/encounters`, { participantIds: [player.id] }, campaign.gmToken)));
assert.deepEqual(competingStarts.map(result => result.status).sort(), [200, 409]);
const encounter = competingStarts.find(result => result.status === 200).data;
assert.equal(encounter.encounter.orderingPolicy, "fixed");
assert.equal((await call(`/sessions/${session.id}/encounters`, { participantIds: [goblin.actorId] }, campaign.gmToken)).status, 409);
const turnKey = randomUUID();
const firstTurn = await valid(`/encounters/${encounter.encounter.id}/advance`, {}, campaign.gmToken, turnKey);
assert.deepEqual(await valid(`/encounters/${encounter.encounter.id}/advance`, {}, campaign.gmToken, turnKey), firstTurn);
for (let i = 0; i < 2; i++) await valid(`/encounters/${encounter.encounter.id}/advance`, {}, campaign.gmToken);
const after = await valid(`/sessions/${session.id}/actors`, undefined, player.accessToken);
assert.equal(after.find(actor => actor.actorId === player.id).effects.length, 0);
const events = await valid(`/sessions/${session.id}/events`, undefined, campaign.gmToken);
for (const type of ["ActionRequested", "ResourceChanged", "EffectApplied", "EncounterStarted", "RoundStarted", "TurnStarted", "EffectTicked", "EffectExpired"]) assert.ok(events.some(event => event.type === type), `${type} missing`);
const beforeAdvance = (await valid(`/sessions/${session.id}/encounters`, undefined, campaign.gmToken)).find(value => value.id === encounter.encounter.id);
const parallelAdvance = await Promise.all(Array.from({ length: 2 }, () => call(`/encounters/${encounter.encounter.id}/advance`, {}, campaign.gmToken)));
assert.ok(parallelAdvance.every(result => result.status === 200 || result.status === 409));
const afterAdvance = (await valid(`/sessions/${session.id}/encounters`, undefined, campaign.gmToken)).find(value => value.id === encounter.encounter.id);
assert.equal(afterAdvance.turn - beforeAdvance.turn, parallelAdvance.filter(result => result.status === 200).length);
const endKey = randomUUID(), ended = await valid(`/encounters/${encounter.encounter.id}/end`, {}, campaign.gmToken, endKey);
assert.deepEqual(await valid(`/encounters/${encounter.encounter.id}/end`, {}, campaign.gmToken, endKey), ended);
const nextKey = randomUUID(), nextBody = { participantIds: [goblin.actorId] };
const repeatedStarts = await Promise.all(Array.from({ length: 2 }, () => call(`/sessions/${session.id}/encounters`, nextBody, campaign.gmToken, nextKey)));
assert.deepEqual(repeatedStarts.map(result => result.status), [200, 200]);
assert.deepEqual(repeatedStarts[0].data, repeatedStarts[1].data);
const nextEncounter = repeatedStarts[0].data;
await valid(`/encounters/${nextEncounter.encounter.id}/end`, {}, campaign.gmToken);
const poisonBody = { actorId: player.id, targetActorIds: [player.id], actionId: "poison" }, poisonKey = randomUUID();
const repeatedActions = await Promise.all(Array.from({ length: 2 }, () => call(`/sessions/${session.id}/actions`, poisonBody, campaign.gmToken, poisonKey)));
assert.deepEqual(repeatedActions.map(result => result.status), [200, 200]);
assert.deepEqual(repeatedActions[0].data, repeatedActions[1].data);
const beforeParallel = await valid(`/sessions/${session.id}/actors`, undefined, campaign.gmToken);
const parallel = await Promise.all(Array.from({ length: 12 }, () => call(`/sessions/${session.id}/actions`, { actorId: player.id, targetActorIds: [player.id], actionId: "poison" }, campaign.gmToken)));
assert.ok(parallel.every(result => result.status === 200 || result.status === 409));
const accepted = parallel.filter(result => result.status === 200).length;
const afterParallel = await valid(`/sessions/${session.id}/actors`, undefined, campaign.gmToken);
assert.equal(afterParallel.find(actor => actor.actorId === player.id).effects.length, beforeParallel.find(actor => actor.actorId === player.id).effects.length + accepted);
const afterParallelEvents = await valid(`/sessions/${session.id}/events`, undefined, campaign.gmToken);
assert.equal(afterParallelEvents.filter(event => event.type === "EffectApplied").length, events.filter(event => event.type === "EffectApplied").length + 1 + accepted);
assert.equal((await call(`/sessions/${session.id}/runtime/verify`, undefined, player.accessToken)).status, 403);
const replayVerification = await valid(`/sessions/${session.id}/runtime/verify`, undefined, campaign.gmToken);
assert.deepEqual(replayVerification, { matching: true, eventCount: afterParallelEvents.length, actorIds: [], encounterIds: [], issues: [] });
const snapshotVerification = await valid(`/sessions/${session.id}/runtime/verify-snapshot`, undefined, campaign.gmToken);
assert.equal(snapshotVerification.matching, true);
assert.equal(snapshotVerification.eventCount, replayVerification.eventCount);
assert.equal(snapshotVerification.snapshotSequence, runtimeSnapshot.lastSequence);
assert.equal(snapshotVerification.replayedEventCount, afterParallelEvents.length - runtimeSnapshot.eventCount);
await valid(`/sessions/${session.id}/state`, { state: "finished" }, campaign.gmToken);
assert.deepEqual(await valid(`/sessions/${session.id}/checks`, checkBody, campaign.gmToken, checkKey), check);
assert.equal((await call(`/sessions/${session.id}/checks`, checkBody, campaign.gmToken)).status, 409);
assert.deepEqual(await valid(`/sessions/${session.id}/actions`, damageBody, campaign.gmToken, damageKey), firstDamage);
assert.deepEqual(await valid(`/sessions/${session.id}/actors`, goblinBody, campaign.gmToken, goblinKey), goblin);
assert.deepEqual(await valid(`/sessions/${session.id}/participants/${player.id}/initialize`, {}, campaign.gmToken, playerInitKey), initializedPlayer);
assert.equal((await call(`/sessions/${session.id}/actors`, { templateId: "goblin" }, campaign.gmToken)).status, 409);
assert.equal((await call(`/sessions/${session.id}/participants/${player.id}/initialize`, {}, campaign.gmToken)).status, 409);
assert.equal((await call("/join/resolve", { pin: session.pin })).status, 404);
console.log(`Runtime smoke passed: PIN, participant and GM authorization, concurrent Check roll, Action commands (${accepted} accepted, ${12 - accepted} conflicts), encounter, effect lifecycle, expiry.`);
