import postgres from "postgres";
import {createHash,randomBytes,randomUUID,timingSafeEqual} from "node:crypto";
import {filterCommunityCatalog} from "@masterhost/game-runtime";
import type {ExplorationBoard,ExplorationNode,FogRegion,TableState} from "@masterhost/game-runtime";
import type {WorldPackProject} from "@masterhost/worldpack-sdk";

const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const tokenMatches=(token:string,expected:string)=>{if(!token||!expected)return false;const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)};
const conflict=()=>Object.assign(Error("revision changed; reload and retry"),{statusCode:409});

export class AdvancedEcosystemRepository{
 private sql;constructor(url:string){this.sql=postgres(url)}
 async migrate(){
  await this.sql`create table if not exists exploration_boards(session_id uuid primary key,world_id uuid not null,revision int not null,state jsonb not null,updated_at timestamptz not null default now())`;
  await this.sql`create table if not exists session_table_state(session_id uuid primary key,revision int not null,state jsonb not null,updated_at timestamptz not null default now())`;
  await this.sql`create table if not exists spectator_grants(id uuid primary key,session_id uuid not null,label text not null,token_hash text unique not null,revoked_at timestamptz null,created_at timestamptz not null default now())`;
  await this.sql`create table if not exists realm_canon_facts(realm_id uuid not null,fact_key text not null,revision int not null,title text not null,value jsonb not null,source_campaign_id uuid not null,source_session_id uuid not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(realm_id,fact_key))`;
  await this.sql`create table if not exists collaboration_documents(id uuid primary key,realm_id uuid not null,resource_kind text not null,resource_id text not null,revision int not null,content jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(realm_id,resource_kind,resource_id))`;
  await this.sql`create table if not exists collaboration_revisions(document_id uuid not null,revision int not null,author_id text not null,summary text not null,content jsonb not null,created_at timestamptz not null default now(),primary key(document_id,revision))`;
 }
 private mapBoard(row:any):ExplorationBoard|null{return row?row.state as ExplorationBoard:null}
 async board(sessionId:string){return this.mapBoard((await this.sql`select state from exploration_boards where session_id=${sessionId}`)[0])}
 async createBoard(input:{sessionId:string;worldId:string;nodes:ExplorationNode[];fog?:FogRegion[]}){const now=new Date().toISOString(),state:ExplorationBoard={id:randomUUID(),sessionId:input.sessionId,worldId:input.worldId,revision:1,nodes:input.nodes,tokens:[],fog:input.fog??[],updatedAt:now};return this.sql.begin(async tx=>{const inserted=await tx`insert into exploration_boards(session_id,world_id,revision,state) values(${input.sessionId},${input.worldId},1,${tx.json(state as any)}) on conflict(session_id) do nothing returning state`;if(inserted.length){await tx`insert into game_events(id,session_id,event_type,payload,schema_version) values(gen_random_uuid(),${input.sessionId},'ExplorationStarted',${tx.json({boardId:state.id,nodeCount:state.nodes.length,fogCount:state.fog.length} as any)},'1')`;return{board:state,created:true}}const row=(await tx`select state from exploration_boards where session_id=${input.sessionId}`)[0];return{board:row.state as ExplorationBoard,created:false}})}
 async updateBoard(sessionId:string,expectedRevision:number,mutate:(board:ExplorationBoard)=>void,event:{type:string;payload:Record<string,unknown>}){return this.sql.begin(async tx=>{const row=(await tx`select revision,state from exploration_boards where session_id=${sessionId} for update`)[0];if(!row)throw Object.assign(Error("exploration board not found"),{statusCode:404});if(Number(row.revision)!==expectedRevision)throw conflict();const board=structuredClone(row.state as ExplorationBoard);mutate(board);board.revision++;board.updatedAt=new Date().toISOString();await tx`update exploration_boards set revision=${board.revision},state=${tx.json(board as any)},updated_at=now() where session_id=${sessionId}`;await tx`insert into game_events(id,session_id,event_type,payload,schema_version) values(gen_random_uuid(),${sessionId},${event.type},${tx.json({...event.payload,boardRevision:board.revision} as any)},'1')`;return board})}
 async table(sessionId:string){const row=(await this.sql`select state from session_table_state where session_id=${sessionId}`)[0];return(row?.state??null)as TableState|null}
 async createTable(state:TableState){return this.sql.begin(async tx=>{const inserted=await tx`insert into session_table_state(session_id,revision,state) values(${state.sessionId},1,${tx.json({...state,revision:1} as any)}) on conflict(session_id) do nothing returning state`;if(inserted.length){await tx`insert into game_events(id,session_id,event_type,payload,schema_version) values(gen_random_uuid(),${state.sessionId},'TableStarted',${tx.json({sceneCount:state.scenes.length,phase:state.phase} as any)},'1')`;return{table:inserted[0]!.state as TableState,created:true}}const row=(await tx`select state from session_table_state where session_id=${state.sessionId}`)[0];return{table:row.state as TableState,created:false}})}
 async updateTable(sessionId:string,expectedRevision:number,mutate:(table:TableState)=>void,event:{type:string;payload:Record<string,unknown>}){return this.sql.begin(async tx=>{const row=(await tx`select revision,state from session_table_state where session_id=${sessionId} for update`)[0];if(!row)throw Object.assign(Error("table state not found"),{statusCode:404});if(Number(row.revision)!==expectedRevision)throw conflict();const table=structuredClone(row.state as TableState);mutate(table);table.revision++;table.updatedAt=new Date().toISOString();await tx`update session_table_state set revision=${table.revision},state=${tx.json(table as any)},updated_at=now() where session_id=${sessionId}`;const payload=event.type==="TablePrivateNoteRecorded"?{noteCount:table.privateNotes.length,tableRevision:table.revision}:{...event.payload,tableRevision:table.revision};await tx`insert into game_events(id,session_id,event_type,payload,schema_version) values(gen_random_uuid(),${sessionId},${event.type},${tx.json(payload as any)},'1')`;return table})}
 async createSpectator(sessionId:string,label:string){const id=randomUUID(),accessToken=randomBytes(32).toString("base64url");await this.sql`insert into spectator_grants(id,session_id,label,token_hash) values(${id},${sessionId},${label.trim()||"Spectator"},${hash(accessToken)})`;return{id,sessionId,label:label.trim()||"Spectator",accessToken,createdAt:new Date().toISOString()}}
 async verifySpectator(sessionId:string,token:string){const row=(await this.sql`select token_hash from spectator_grants where session_id=${sessionId} and revoked_at is null and token_hash=${hash(token)} limit 1`)[0];return typeof row?.token_hash==="string"&&tokenMatches(token,row.token_hash)}
 async revokeSpectator(id:string,sessionId:string){await this.sql`update spectator_grants set revoked_at=now() where id=${id} and session_id=${sessionId}`;return{revoked:true}}
 async promoteFact(input:{realmId:string;key:string;title:string;value:unknown;campaignId:string;sessionId:string}){return this.sql.begin(async tx=>{const row=(await tx`insert into realm_canon_facts(realm_id,fact_key,revision,title,value,source_campaign_id,source_session_id) values(${input.realmId},${input.key},1,${input.title},${tx.json(input.value as any)},${input.campaignId},${input.sessionId}) on conflict(realm_id,fact_key) do update set revision=realm_canon_facts.revision+1,title=excluded.title,value=excluded.value,source_campaign_id=excluded.source_campaign_id,source_session_id=excluded.source_session_id,updated_at=now() returning revision`)[0]!,revision=Number(row.revision);await tx`insert into game_events(id,session_id,event_type,payload,schema_version) values(gen_random_uuid(),${input.sessionId},'CanonFactPromoted',${tx.json({key:input.key,title:input.title,revision} as any)},'1')`;return{...input,revision,updatedAt:new Date().toISOString()}})}
 async canon(realmId:string){const rows=await this.sql`select * from realm_canon_facts where realm_id=${realmId} order by fact_key`;return rows.map(row=>({realmId:row.realm_id,key:row.fact_key,revision:Number(row.revision),title:row.title,value:row.value,sourceCampaignId:row.source_campaign_id,sourceSessionId:row.source_session_id,updatedAt:new Date(row.updated_at).toISOString()}))}
 async collaboration(realmId:string,kind:string,resourceId:string){const row=(await this.sql`select * from collaboration_documents where realm_id=${realmId} and resource_kind=${kind} and resource_id=${resourceId}`)[0];return row?{id:row.id,realmId:row.realm_id,resourceKind:row.resource_kind,resourceId:row.resource_id,revision:Number(row.revision),content:row.content,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()}:null}
 async saveCollaboration(input:{realmId:string;resourceKind:string;resourceId:string;expectedRevision:number;content:unknown;authorId:string;summary:string;project:WorldPackProject}){return this.sql.begin(async tx=>{const projectRow=(await tx`select revision,status from world_pack_projects where id=${input.resourceId} and realm_id=${input.realmId} for update`)[0];if(!projectRow||projectRow.status!=="draft")throw Object.assign(Error("draft Pack project not found in Realm"),{statusCode:404});if(Number(projectRow.revision)!==input.project.revision)throw conflict();let row=(await tx`select * from collaboration_documents where realm_id=${input.realmId} and resource_kind=${input.resourceKind} and resource_id=${input.resourceId} for update`)[0];if(!row){if(input.expectedRevision!==0)throw conflict();const id=randomUUID();await tx`insert into collaboration_documents(id,realm_id,resource_kind,resource_id,revision,content) values(${id},${input.realmId},${input.resourceKind},${input.resourceId},1,${tx.json(input.content as any)})`;row={id,revision:1,created_at:new Date()}}else{if(Number(row.revision)!==input.expectedRevision)throw conflict();row.revision=Number(row.revision)+1;await tx`update collaboration_documents set revision=${row.revision},content=${tx.json(input.content as any)},updated_at=now() where id=${row.id}`}const next=structuredClone(input.project);next.document=input.content as WorldPackProject["document"];next.revision++;next.updatedAt=new Date().toISOString();await tx`update world_pack_projects set pack_id=${next.document.manifest.id},pack_version=${next.document.manifest.version},revision=${next.revision},data=${tx.json(next as any)},updated_at=now() where id=${next.id}`;await tx`insert into collaboration_revisions(document_id,revision,author_id,summary,content) values(${row.id},${row.revision},${input.authorId},${input.summary.trim()||"Updated draft"},${tx.json(input.content as any)})`;return{id:row.id,realmId:input.realmId,resourceKind:input.resourceKind,resourceId:input.resourceId,revision:Number(row.revision),content:input.content,createdAt:new Date(row.created_at??Date.now()).toISOString(),updatedAt:new Date().toISOString()}})}
  async collaborationHistory(id:string){const rows=await this.sql`select revision,author_id,summary,created_at from collaboration_revisions where document_id=${id} order by revision desc`;return rows.map(row=>({revision:Number(row.revision),authorId:row.author_id,summary:row.summary,createdAt:new Date(row.created_at).toISOString()}))}
 async communityCatalog(filter:{query?:string;tag?:string;license?:string}){const rows=await this.sql`select r.slug,p.data from hosted_publications h join realms r on r.id=h.realm_id join world_pack_projects p on p.id::text=h.resource_id where h.kind='pack' and h.visibility='public' and p.status='published' order by h.published_at desc`;const catalog=rows.map(row=>{const manifest=(row.data as any).document.manifest;return{realmSlug:row.slug as string,packId:String(manifest.id),version:String(manifest.version),name:String(manifest.name),description:manifest.description?String(manifest.description):undefined,tags:Array.isArray(manifest.tags)?manifest.tags.map(String):[],license:manifest.license?.spdx?String(manifest.license.spdx):manifest.license?String(manifest.license):undefined}});return filterCommunityCatalog(catalog,filter)}
 async close(){await this.sql.end()}
}
