import postgres from "postgres";
import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";

export type PublicationVisibility = "private" | "unlisted" | "public";
export interface PublicationPolicy { allowCampaigns:boolean; allowFork:boolean; allowModify:boolean; allowCharacters:boolean }
export interface RealmBrand {
  logo?:string; favicon?:string; landing?:string;
  theme:{primary:string;accent:string;background:string};
  terminology:{world:string;character:string;gameMaster:string};
}
export interface RealmQuotas { worlds:number; packs:number; activeSessions:number; assetBytes:number }
export interface HostedRealm {
  id:string; slug:string; name:string; domain?:string; guestAccess:boolean;
  activePack?:{id:string;version:string}; brand:RealmBrand; quotas:RealmQuotas;
  createdAt:string; updatedAt:string;
}
export interface HostedPublication {
  id:string; realmId:string; kind:"world"|"pack"; resourceId:string;
  visibility:PublicationVisibility; policies:PublicationPolicy; publishedAt:string;
}
const hash=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const canonical=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(",")}]`:`{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${canonical((value as any)[key])}`).join(",")}}`;
const safeToken=(actual:string,expected:string)=>{if(!actual||!expected)return false;const a=Buffer.from(hash(actual),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)};
const defaultBrand=(name:string):RealmBrand=>({theme:{primary:"#6dd6a8",accent:"#7aa7dd",background:"#0f131a"},terminology:{world:"World",character:"Character",gameMaster:"Game Master"}});
const defaultQuotas:RealmQuotas={worlds:100,packs:20,activeSessions:20,assetBytes:20_000_000};

export class HostedPlatformRepository {
  private sql;
  constructor(url:string){this.sql=postgres(url)}
  async migrate(){
    await this.sql`create table if not exists realms(id uuid primary key,slug text unique not null,name text not null,guest_access boolean not null default true,created_at timestamptz not null default now())`;await this.sql`alter table realms add column if not exists domain text unique`;await this.sql`alter table realms add column if not exists admin_token_hash text`;await this.sql`alter table realms add column if not exists config jsonb not null default '{}'::jsonb`;await this.sql`alter table realms add column if not exists updated_at timestamptz not null default now()`;
    await this.sql`create table if not exists hosted_publications(id uuid primary key,realm_id uuid not null,kind text not null check(kind in ('world','pack')),resource_id text not null,visibility text not null check(visibility in ('private','unlisted','public')),policies jsonb not null,published_at timestamptz not null default now(),unique(realm_id,kind,resource_id))`;
    await this.sql`create table if not exists hosted_objects(checksum text primary key,media_type text not null,data bytea not null,created_at timestamptz not null default now())`;
    await this.sql`create table if not exists hosted_realm_assets(realm_id uuid not null,role text not null,checksum text not null,primary key(realm_id,role))`;
    await this.sql`create table if not exists hosted_telemetry(id bigserial primary key,realm_id uuid not null,event text not null,amount bigint not null default 1,created_at timestamptz not null default now())`;
    await this.sql`create table if not exists hosted_backups(id uuid primary key,realm_id uuid not null,checksum text not null,snapshot jsonb not null,created_at timestamptz not null default now())`;
    await this.sql`create table if not exists realm_memberships(id uuid primary key,realm_id uuid not null,name text not null,role text not null check(role in ('creator','gm','player')),token_hash text unique not null,created_at timestamptz not null default now())`;
  }
  private mapRealm(row:any):HostedRealm {const config=row.config??{};return{id:row.id,slug:row.slug,name:row.name,domain:row.domain??undefined,guestAccess:Boolean(row.guest_access),activePack:config.activePack,brand:config.brand??defaultBrand(row.name),quotas:{...defaultQuotas,...config.quotas},createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()}}
  async ensureDefault(id:string){const token=process.env.MASTERHOST_DEFAULT_REALM_ADMIN??"local-default-realm-admin";await this.sql`insert into realms(id,slug,name,admin_token_hash,config) values(${id},'default','MasterHost',${hash(token)},${this.sql.json({brand:defaultBrand("MasterHost"),quotas:defaultQuotas} as any)}) on conflict(id) do update set admin_token_hash=coalesce(realms.admin_token_hash,excluded.admin_token_hash),config=case when realms.config='{}'::jsonb then excluded.config else realms.config end`;return this.realm(id)}
  async create(input:{slug:string;name:string;domain?:string;guestAccess?:boolean;brand?:Partial<RealmBrand>;quotas?:Partial<RealmQuotas>}){const slug=input.slug.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9-]{1,62}$/.test(slug)||!input.name.trim())throw Object.assign(Error("invalid Realm identity"),{statusCode:400});const id=randomUUID(),adminToken=randomBytes(32).toString("base64url"),brand={...defaultBrand(input.name.trim()),...input.brand,theme:{...defaultBrand(input.name).theme,...input.brand?.theme},terminology:{...defaultBrand(input.name).terminology,...input.brand?.terminology}},quotas={...defaultQuotas,...input.quotas};await this.sql`insert into realms(id,slug,domain,name,guest_access,admin_token_hash,config) values(${id},${slug},${input.domain?.trim().toLowerCase()||null},${input.name.trim()},${input.guestAccess??true},${hash(adminToken)},${this.sql.json({brand,quotas} as any)})`;return{realm:(await this.realm(id))!,adminToken}}
  async realm(id:string){const row=(await this.sql`select * from realms where id=${id}`)[0];return row?this.mapRealm(row):null}
  async resolve(selector:string){const value=selector.trim().toLowerCase();const row=(await this.sql`select * from realms where slug=${value} or domain=${value} limit 1`)[0];return row?this.mapRealm(row):null}
  async list(){return(await this.sql`select * from realms order by created_at`).map(row=>this.mapRealm(row))}
  async verifyAdmin(id:string,token:string){const row=(await this.sql`select admin_token_hash from realms where id=${id}`)[0];return typeof row?.admin_token_hash==="string"&&safeToken(token,row.admin_token_hash)}
  async createMembership(realmId:string,name:string,role:"creator"|"gm"|"player"){if(!name.trim()||!["creator","gm","player"].includes(role))throw Object.assign(Error("invalid Realm membership"),{statusCode:400});const id=randomUUID(),accessToken=randomBytes(32).toString("base64url");await this.sql`insert into realm_memberships(id,realm_id,name,role,token_hash) values(${id},${realmId},${name.trim()},${role},${hash(accessToken)})`;return{id,realmId,name:name.trim(),role,accessToken}}
  async role(realmId:string,token:string):Promise<"owner"|"creator"|"gm"|"player"|null>{if(await this.verifyAdmin(realmId,token))return"owner";if(!token)return null;const row=(await this.sql`select role from realm_memberships where realm_id=${realmId} and token_hash=${hash(token)}`)[0];return(row?.role??null)as any}
  async update(id:string,patch:{name?:string;domain?:string|null;guestAccess?:boolean;activePack?:{id:string;version:string}|null;brand?:Partial<RealmBrand>;quotas?:Partial<RealmQuotas>}){const current=await this.realm(id);if(!current)throw Object.assign(Error("Realm not found"),{statusCode:404});const name=patch.name?.trim()||current.name,brand={...current.brand,...patch.brand,theme:{...current.brand.theme,...patch.brand?.theme},terminology:{...current.brand.terminology,...patch.brand?.terminology}},quotas={...current.quotas,...patch.quotas};for(const value of Object.values(quotas))if(!Number.isInteger(value)||value<0)throw Object.assign(Error("invalid Realm quota"),{statusCode:400});const config={brand,quotas,...(patch.activePack===null?{}:{activePack:patch.activePack??current.activePack})};await this.sql`update realms set name=${name},domain=${patch.domain===undefined?current.domain??null:patch.domain?.trim().toLowerCase()||null},guest_access=${patch.guestAccess??current.guestAccess},config=${this.sql.json(config as any)},updated_at=now() where id=${id}`;return this.realm(id)}
  async publish(input:{realmId:string;kind:"world"|"pack";resourceId:string;visibility:PublicationVisibility;policies:PublicationPolicy}){const id=randomUUID();await this.sql`insert into hosted_publications(id,realm_id,kind,resource_id,visibility,policies) values(${id},${input.realmId},${input.kind},${input.resourceId},${input.visibility},${this.sql.json(input.policies as any)}) on conflict(realm_id,kind,resource_id) do update set visibility=excluded.visibility,policies=excluded.policies,published_at=now() returning id`;return this.publication(input.realmId,input.kind,input.resourceId)}
  async publication(realmId:string,kind:"world"|"pack",resourceId:string){const row=(await this.sql`select * from hosted_publications where realm_id=${realmId} and kind=${kind} and resource_id=${resourceId}`)[0];return row?{id:row.id,realmId:row.realm_id,kind:row.kind,resourceId:row.resource_id,visibility:row.visibility,policies:row.policies,publishedAt:new Date(row.published_at).toISOString()} as HostedPublication:null}
  async catalog(realmId:string,admin=false){const rows=admin?await this.sql`select * from hosted_publications where realm_id=${realmId} order by published_at desc`:await this.sql`select * from hosted_publications where realm_id=${realmId} and visibility='public' order by published_at desc`;return rows.map(row=>({id:row.id,realmId:row.realm_id,kind:row.kind,resourceId:row.resource_id,visibility:row.visibility,policies:row.policies,publishedAt:new Date(row.published_at).toISOString()} as HostedPublication))}
  async putObject(realmId:string,role:string,mediaType:string,data:Uint8Array){if(!["logo","favicon","landing"].includes(role))throw Object.assign(Error("invalid brand asset role"),{statusCode:400});const checksum=hash(data);await this.sql.begin(async tx=>{await tx`insert into hosted_objects(checksum,media_type,data) values(${checksum},${mediaType},${Buffer.from(data)}) on conflict(checksum) do nothing`;await tx`insert into hosted_realm_assets(realm_id,role,checksum) values(${realmId},${role},${checksum}) on conflict(realm_id,role) do update set checksum=excluded.checksum`});return{role,checksum,mediaType,size:data.length,path:`/api/cdn/${checksum}`}}
  async object(checksum:string){const row=(await this.sql`select media_type,data from hosted_objects where checksum=${checksum}`)[0];return row?{mediaType:row.media_type as string,data:new Uint8Array(row.data as Buffer)}:null}
  async assets(realmId:string){const rows=await this.sql`select a.role,a.checksum,o.media_type,octet_length(o.data) size from hosted_realm_assets a join hosted_objects o on o.checksum=a.checksum where a.realm_id=${realmId}`;return Object.fromEntries(rows.map(row=>[row.role,{checksum:row.checksum,mediaType:row.media_type,size:Number(row.size),path:`/api/cdn/${row.checksum}`}]))}
  async usage(realmId:string){const [worlds,packs,sessions,assets]=await Promise.all([this.sql`select count(*) count from worlds where realm_id=${realmId}`,this.sql`select count(*) count from world_pack_projects where realm_id=${realmId}`,this.sql`select count(*) count from sessions where realm_id=${realmId} and state in ('preparing','lobby','live')`,this.sql`select coalesce(sum(octet_length(o.data)),0) total from hosted_realm_assets a join hosted_objects o on o.checksum=a.checksum where a.realm_id=${realmId}`]);return{worlds:Number(worlds[0]!.count),packs:Number(packs[0]!.count),activeSessions:Number(sessions[0]!.count),assetBytes:Number(assets[0]!.total)}}
  async assertQuota(realm:HostedRealm,key:keyof RealmQuotas,increment=1){const usage=await this.usage(realm.id);if(usage[key]+increment>realm.quotas[key])throw Object.assign(Error(`Realm ${key} quota exceeded`),{statusCode:429})}
  async record(realmId:string,event:string,amount=1){await this.sql`insert into hosted_telemetry(realm_id,event,amount) values(${realmId},${event},${amount})`}
  async telemetry(realmId:string){const rows=await this.sql`select event,sum(amount)::bigint total,max(created_at) latest from hosted_telemetry where realm_id=${realmId} group by event order by event`;return rows.map(row=>({event:row.event,total:Number(row.total),latest:new Date(row.latest).toISOString()}))}
  async backup(realmId:string){const realm=await this.realm(realmId);if(!realm)throw Object.assign(Error("Realm not found"),{statusCode:404});const [publications,assets,packs,worlds]=await Promise.all([this.sql`select kind,resource_id,visibility,policies,published_at from hosted_publications where realm_id=${realmId} order by kind,resource_id`,this.sql`select a.role,a.checksum,o.media_type,encode(o.data,'base64') data from hosted_realm_assets a join hosted_objects o on o.checksum=a.checksum where a.realm_id=${realmId} order by a.role`,this.sql`select data from world_pack_projects where realm_id=${realmId} order by id`,this.sql`select data from worlds where realm_id=${realmId} order by id`]),raw={format:"masterhost.realm-backup",version:"0.1",realm,publications,assets,packs:packs.map(row=>row.data),worlds:worlds.map(row=>row.data)},snapshot=JSON.parse(JSON.stringify(raw)),checksum=hash(canonical(snapshot)),id=randomUUID();await this.sql`insert into hosted_backups(id,realm_id,checksum,snapshot) values(${id},${realmId},${checksum},${this.sql.json(snapshot as any)})`;return{id,realmId,checksum,createdAt:new Date().toISOString(),counts:{publications:publications.length,assets:assets.length,packs:packs.length,worlds:worlds.length}}}
  async restore(realmId:string,backupId:string){return this.sql.begin(async tx=>{const row=(await tx`select checksum,snapshot from hosted_backups where id=${backupId} and realm_id=${realmId} for update`)[0];if(!row||hash(canonical(row.snapshot))!==row.checksum)throw Object.assign(Error("Realm backup missing or corrupt"),{statusCode:409});const snapshot=row.snapshot as any,realm=snapshot.realm as HostedRealm;await tx`update realms set name=${realm.name},domain=${realm.domain??null},guest_access=${realm.guestAccess},config=${tx.json({activePack:realm.activePack,brand:realm.brand,quotas:realm.quotas} as any)},updated_at=now() where id=${realmId}`;await tx`delete from hosted_publications where realm_id=${realmId}`;for(const item of snapshot.publications)await tx`insert into hosted_publications(id,realm_id,kind,resource_id,visibility,policies,published_at) values(${randomUUID()},${realmId},${item.kind},${item.resource_id},${item.visibility},${tx.json(item.policies)},${item.published_at})`;for(const item of snapshot.assets){await tx`insert into hosted_objects(checksum,media_type,data) values(${item.checksum},${item.media_type},${Buffer.from(item.data,"base64")}) on conflict(checksum) do nothing`;await tx`insert into hosted_realm_assets(realm_id,role,checksum) values(${realmId},${item.role},${item.checksum}) on conflict(realm_id,role) do update set checksum=excluded.checksum`};for(const project of snapshot.packs)await tx`insert into world_pack_projects(id,realm_id,pack_id,pack_version,status,revision,data) values(${project.id},${realmId},${project.document.manifest.id},${project.document.manifest.version},${project.status},${project.revision},${tx.json(project)}) on conflict(id) do update set data=excluded.data,revision=excluded.revision,status=excluded.status`;for(const world of snapshot.worlds)await tx`insert into worlds(id,realm_id,name,revision,data) values(${world.id},${realmId},${world.name},${world.revision},${tx.json(world)}) on conflict(id) do update set name=excluded.name,revision=excluded.revision,data=excluded.data,updated_at=now()`;return{restored:true,checksum:row.checksum,counts:{publications:snapshot.publications.length,assets:snapshot.assets.length,packs:snapshot.packs.length,worlds:snapshot.worlds.length}}})}
  async close(){await this.sql.end()}
}
