import postgres from"postgres";import type{WorldPackProject}from"@masterhost/worldpack-sdk";
export class PackProjectRepository{private sql;constructor(url:string){this.sql=postgres(url)}
 async migrate(){await this.sql`create table if not exists world_pack_projects(id uuid primary key,realm_id uuid not null,pack_id text not null,pack_version text not null,status text not null check(status in ('draft','published')),revision int not null,data jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`;await this.sql`drop index if exists world_pack_published_version`;await this.sql`create unique index if not exists world_pack_published_realm_version on world_pack_projects(realm_id,pack_id,pack_version) where status='published'`}
 async create(project:WorldPackProject){await this.sql`insert into world_pack_projects(id,realm_id,pack_id,pack_version,status,revision,data) values(${project.id},${project.realmId},${project.document.manifest.id},${project.document.manifest.version},${project.status},${project.revision},${this.sql.json(project as any)})`;return project}
 async get(id:string){const row=(await this.sql`select data from world_pack_projects where id=${id}`)[0];return(row?.data??null)as WorldPackProject|null}
 async findPublished(realmId:string,packId:string,packVersion:string):Promise<WorldPackProject|null>{const row=(await this.sql`select data from world_pack_projects where realm_id=${realmId} and pack_id=${packId} and pack_version=${packVersion} and status='published'`)[0];return(row?.data??null)as WorldPackProject|null}
 async list(realmId:string){const rows=await this.sql`select data from world_pack_projects where realm_id=${realmId} order by updated_at desc`;return rows.map(value=>value.data as WorldPackProject)}
 async save(project:WorldPackProject){if(project.status!=="draft")throw Object.assign(Error("published Pack versions are immutable"),{statusCode:409});const previous=await this.get(project.id);if(!previous)throw Object.assign(Error("Pack project not found"),{statusCode:404});if(previous.status!=="draft")throw Object.assign(Error("published Pack versions are immutable"),{statusCode:409});if(project.revision!==previous.revision+1)throw Object.assign(Error("Pack project revision changed; reload and retry"),{statusCode:409});const result=await this.sql`update world_pack_projects set pack_id=${project.document.manifest.id},pack_version=${project.document.manifest.version},revision=${project.revision},data=${this.sql.json(project as any)},updated_at=now() where id=${project.id} and revision=${previous.revision} and status='draft'`;if(result.count!==1)throw Object.assign(Error("Pack project revision changed; reload and retry"),{statusCode:409});return project}
 async publish(id:string){return this.sql.begin(async tx=>{const row=(await tx`select data from world_pack_projects where id=${id} for update`)[0];if(!row)throw Object.assign(Error("Pack project not found"),{statusCode:404});const project=structuredClone(row.data as WorldPackProject);if(project.status==="published")return project;const conflict=(await tx`select id from world_pack_projects where realm_id=${project.realmId} and pack_id=${project.document.manifest.id} and pack_version=${project.document.manifest.version} and status='published' and id<>${id}`)[0];if(conflict)throw Object.assign(Error("Pack ID and version are already published"),{statusCode:409});project.status="published";project.revision++;project.updatedAt=project.publishedAt=new Date().toISOString();await tx`update world_pack_projects set status='published',revision=${project.revision},data=${tx.json(project as any)},updated_at=now() where id=${id}`;return project})}
 async close(){await this.sql.end()}}
