import postgres from"postgres";import{randomUUID,randomInt,randomBytes,createHash,timingSafeEqual}from"node:crypto";import type{Campaign,GameSession,Realm,SessionParticipant,SessionState}from"@masterhost/domain";import{canTransition}from"@masterhost/domain";
const now=()=>new Date().toISOString();
const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
export class RuntimeRepository{
 private sql;constructor(url:string){this.sql=postgres(url)}
 async migrate(){
  await this.sql`create table if not exists realms(id uuid primary key,slug text unique not null,name text not null,guest_access boolean not null default true,created_at timestamptz not null default now())`;
  await this.sql`create table if not exists campaigns(id uuid primary key,realm_id uuid not null,world_id uuid not null,name text not null,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`;
  await this.sql`alter table campaigns add column if not exists gm_token_hash text`;
  await this.sql`create table if not exists sessions(id uuid primary key,realm_id uuid not null,campaign_id uuid not null,gm_id text null,state text not null,pin text null,pin_expires_at timestamptz null,created_at timestamptz not null default now(),started_at timestamptz null,finished_at timestamptz null)`;
  await this.sql`create unique index if not exists active_session_pin on sessions(realm_id,pin) where pin is not null and state in ('preparing','lobby','live')`;
  await this.sql`create table if not exists characters(id uuid primary key,realm_id uuid not null,world_pack_id text not null,world_pack_version text not null,owner_key text not null,display_name text not null,values jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`;
  await this.sql`create index if not exists characters_owner on characters(realm_id,owner_key)`;
  await this.sql`create table if not exists session_participants(id uuid primary key,session_id uuid not null,display_name text not null,profile_id text null,character_id uuid null,ready boolean not null default false,joined_at timestamptz not null default now(),left_at timestamptz null)`;
  await this.sql`alter table session_participants add column if not exists access_token_hash text`;
  await this.sql`create unique index if not exists session_participants_access_token on session_participants(access_token_hash) where access_token_hash is not null`;
 }
 async ensureRealm(id:string,slug="default",name="MasterHost"):Promise<Realm>{await this.sql`insert into realms(id,slug,name) values(${id},${slug},${name}) on conflict(id) do nothing`;const r=(await this.sql`select * from realms where id=${id}`)[0]!;return{id:r.id as string,slug:r.slug as string,name:r.name as string,guestAccess:Boolean(r.guest_access),createdAt:new Date(r.created_at as any).toISOString()}}
 async createCampaign(x:{realmId:string;worldId:string;name:string}):Promise<Campaign&{gmToken:string}>{const id=randomUUID(),gmToken=randomBytes(32).toString("base64url");await this.sql`insert into campaigns(id,realm_id,world_id,name,status,gm_token_hash) values(${id},${x.realmId},${x.worldId},${x.name},'active',${hashToken(gmToken)})`;return{id,realmId:x.realmId,worldId:x.worldId,name:x.name,status:"active",createdAt:now(),updatedAt:now(),gmToken}}
 async verifyCampaignGm(campaignId:string,token:string){if(!token)return false;const row=(await this.sql`select gm_token_hash from campaigns where id=${campaignId}`)[0],expected=row?.gm_token_hash;if(typeof expected!=="string")return false;const actual=Buffer.from(hashToken(token),"hex"),stored=Buffer.from(expected,"hex");return actual.length===stored.length&&timingSafeEqual(actual,stored)}
 async verifySessionGm(sessionId:string,token:string){const session=await this.session(sessionId);return session?this.verifyCampaignGm(session.campaignId,token):false}
 async campaign(id:string){const r=(await this.sql`select * from campaigns where id=${id}`)[0];if(!r)return null;return{id:r.id as string,realmId:r.realm_id as string,worldId:r.world_id as string,name:r.name as string,status:r.status as any,createdAt:new Date(r.created_at as any).toISOString(),updatedAt:new Date(r.updated_at as any).toISOString()}as Campaign}
 private async newPin(realmId:string){for(let i=0;i<30;i++){const pin=String(randomInt(0,100000)).padStart(5,"0"),r=await this.sql`select 1 from sessions where realm_id=${realmId} and pin=${pin} and state in ('preparing','lobby','live') limit 1`;if(!r.length)return pin}throw Error("unable to allocate session PIN")}
 async startLobby(x:{realmId:string;campaignId:string;gmId?:string;ttlMinutes?:number}):Promise<GameSession>{const id=randomUUID(),pin=await this.newPin(x.realmId),expires=new Date(Date.now()+(x.ttlMinutes??360)*60000).toISOString();await this.sql`insert into sessions(id,realm_id,campaign_id,gm_id,state,pin,pin_expires_at) values(${id},${x.realmId},${x.campaignId},${x.gmId??null},'lobby',${pin},${expires})`;return{id,realmId:x.realmId,campaignId:x.campaignId,gmId:x.gmId,state:"lobby",pin,pinExpiresAt:expires,createdAt:now()}}
 async resolvePin(realmId:string,pin:string){const r=(await this.sql`select * from sessions where realm_id=${realmId} and pin=${pin} and state in ('lobby','live') and (pin_expires_at is null or pin_expires_at>now()) limit 1`)[0];return r?this.mapSession(r):null}
 async session(id:string){const r=(await this.sql`select * from sessions where id=${id}`)[0];return r?this.mapSession(r):null}
 async transition(id:string,to:SessionState){const s=await this.session(id);if(!s)throw Error("session not found");if(!canTransition(s.state,to))throw Error(`invalid session transition ${s.state} -> ${to}`);if(to==="live"){const participants=await this.participants(id);if(!participants.length||participants.some(p=>!p.ready||!p.characterId))throw Error("all participants need a character and ready state")}const started=to==="live"?now():s.startedAt??null,finished=["finished","cancelled"].includes(to)?now():s.finishedAt??null,pin=["finished","cancelled"].includes(to)?null:s.pin??null;await this.sql`update sessions set state=${to},started_at=${started},finished_at=${finished},pin=${pin} where id=${id}`;return this.session(id)}
 async joinGuest(x:{sessionId:string;pin:string;displayName:string}){const s=await this.session(x.sessionId);if(!s||!["lobby","live"].includes(s.state)||s.pin!==x.pin||s.pinExpiresAt&&new Date(s.pinExpiresAt).getTime()<=Date.now())throw Error("session is not joinable");const id=randomUUID(),accessToken=randomBytes(32).toString("base64url");await this.sql`insert into session_participants(id,session_id,display_name,access_token_hash) values(${id},${x.sessionId},${x.displayName},${hashToken(accessToken)})`;return{id,sessionId:x.sessionId,displayName:x.displayName,ready:false,joinedAt:now(),accessToken}as SessionParticipant&{accessToken:string}}
 async verifyParticipant(id:string,token:string){if(!token)return false;const row=(await this.sql`select access_token_hash from session_participants where id=${id} and left_at is null`)[0];return typeof row?.access_token_hash==="string"&&row.access_token_hash===hashToken(token)}
 async sessionMember(sessionId:string,token:string){if(!token)return null;const row=(await this.sql`select id from session_participants where session_id=${sessionId} and access_token_hash=${hashToken(token)} and left_at is null`)[0];return row?this.participant(row.id as string):null}
 async participants(sessionId:string){const r=await this.sql`select * from session_participants where session_id=${sessionId} and left_at is null order by joined_at`;return r.map(x=>({id:x.id as string,sessionId:x.session_id as string,displayName:x.display_name as string,profileId:x.profile_id as any,characterId:x.character_id as any,ready:Boolean(x.ready),joinedAt:new Date(x.joined_at as any).toISOString()}as SessionParticipant))}

 async createCharacter(x:{realmId:string;packId:string;packVersion:string;ownerKey:string;displayName:string;values:Record<string,unknown>}){const id=randomUUID();await this.sql`insert into characters(id,realm_id,world_pack_id,world_pack_version,owner_key,display_name,values) values(${id},${x.realmId},${x.packId},${x.packVersion},${x.ownerKey},${x.displayName},${this.sql.json(x.values as any)})`;return{id,realmId:x.realmId,worldPackId:x.packId,worldPackVersion:x.packVersion,displayName:x.displayName,values:x.values,createdAt:now(),updatedAt:now()}}
 async characters(realmId:string,ownerKey:string,packId?:string,packVersion?:string){const r=packId&&packVersion?await this.sql`select * from characters where realm_id=${realmId} and owner_key=${ownerKey} and world_pack_id=${packId} and world_pack_version=${packVersion} order by updated_at desc`:await this.sql`select * from characters where realm_id=${realmId} and owner_key=${ownerKey} order by updated_at desc`;return r.map(x=>({id:x.id,realmId:x.realm_id,worldPackId:x.world_pack_id,worldPackVersion:x.world_pack_version,displayName:x.display_name,values:x.values,createdAt:new Date(x.created_at as any).toISOString(),updatedAt:new Date(x.updated_at as any).toISOString()}))}
 async character(id:string){const x=(await this.sql`select * from characters where id=${id}`)[0];return x?{id:x.id,realmId:x.realm_id,worldPackId:x.world_pack_id,worldPackVersion:x.world_pack_version,displayName:x.display_name,values:x.values,createdAt:new Date(x.created_at as any).toISOString(),updatedAt:new Date(x.updated_at as any).toISOString()}:null}
 async characterOwnedBy(id:string,ownerKey:string){if(!ownerKey)return false;const rows=await this.sql`select 1 from characters where id=${id} and owner_key=${ownerKey} limit 1`;return rows.length>0}


 async participant(id:string){const x=(await this.sql`select * from session_participants where id=${id}`)[0];return x?{id:x.id,sessionId:x.session_id,displayName:x.display_name,profileId:x.profile_id??undefined,characterId:x.character_id??undefined,ready:Boolean(x.ready),joinedAt:new Date(x.joined_at as any).toISOString()}:null}

 async setReady(id:string,ready:boolean){const participant=await this.participant(id);if(!participant)throw Error("participant not found");if(ready&&!participant.characterId)throw Error("character required before ready");await this.sql`update session_participants set ready=${ready} where id=${id}`;const r=(await this.sql`select * from session_participants where id=${id}`)[0];return r?{id:r.id,sessionId:r.session_id,displayName:r.display_name,profileId:r.profile_id??undefined,characterId:r.character_id??undefined,ready:Boolean(r.ready),joinedAt:new Date(r.joined_at).toISOString()}:null}
 async selectCharacter(id:string,characterId:string){await this.sql`update session_participants set character_id=${characterId} where id=${id}`;return true}
 async leave(id:string){const r=(await this.sql`update session_participants set left_at=now() where id=${id} returning session_id`)[0];return r?.session_id as string|undefined}
 private mapSession(r:any):GameSession{return{id:r.id,realmId:r.realm_id,campaignId:r.campaign_id,gmId:r.gm_id??undefined,state:r.state,pin:r.pin??undefined,pinExpiresAt:r.pin_expires_at?new Date(r.pin_expires_at).toISOString():undefined,createdAt:new Date(r.created_at).toISOString(),startedAt:r.started_at?new Date(r.started_at).toISOString():undefined,finishedAt:r.finished_at?new Date(r.finished_at).toISOString():undefined}}
 async close(){await this.sql.end()}
}
