import{readFile,readdir}from"node:fs/promises";import{join,relative,resolve}from"node:path";import YAML from"yaml";import{z}from"zod";import type{Character,CharacterCondition,CharacterCreationSchema,CharacterPortability}from"@masterhost/domain";
import { validateRuntimePack } from "./runtime-validation.js";
const Id=z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/);
export const ManifestSchema=z.object({id:z.string(),name:z.string(),version:z.string(),schemaVersion:z.literal("0.1"),defaultArtSet:z.string(),entryTemplate:Id});
const Question=z.object({id:Id,label:z.string(),type:z.literal("choice"),options:z.array(z.object({value:z.string(),label:z.string()})).min(1),default:z.string()});
export const ValueSpecSchema:z.ZodType<any>=z.lazy(()=>z.union([
 z.object({value:z.unknown()}),z.object({descriptor:z.string(),default:z.unknown().optional()}),z.object({generator:Id}),
 z.object({expression:z.string()}),z.object({param:z.string(),default:z.unknown().optional()}),z.object({parent:z.string(),default:z.unknown().optional()})
]));
const Condition:z.ZodType<any>=z.lazy(()=>z.union([
 z.object({eq:z.tuple([z.any(),z.any()])}),z.object({ne:z.tuple([z.any(),z.any()])}),
 z.object({in:z.tuple([z.any(),z.array(z.any())])}),z.object({gte:z.tuple([z.any(),z.any()])}),z.object({lte:z.tuple([z.any(),z.any()])}),
 z.object({all:z.array(Condition)}),z.object({any:z.array(Condition)}),z.object({not:Condition})
]));
const Component=z.object({template:Id,count:z.union([z.number().int().positive(),ValueSpecSchema]).optional(),when:Condition.optional(),parameters:z.record(z.string(),ValueSpecSchema).optional()});
const Parameter=z.object({required:z.boolean().optional(),default:z.unknown().optional()});
const Template=z.object({kind:z.string(),parameters:z.record(z.string(),Parameter).optional(),values:z.record(z.string(),ValueSpecSchema).optional(),traits:z.array(Id).optional(),tags:z.array(z.string()).optional(),components:z.record(z.string(),Component).optional()});
const Generator=z.discriminatedUnion("type",[z.object({type:z.literal("values"),values:z.array(z.unknown()).min(1)}),z.object({type:z.literal("weighted-table"),entries:z.array(z.object({value:z.unknown(),weight:z.number().positive()})).min(1)}),z.object({type:z.literal("integer-range"),min:z.number().int(),max:z.number().int()})]);
const Trait=z.object({id:Id,when:Condition.optional(),addTags:z.array(z.string()).optional(),set:z.record(z.string(),z.unknown()).optional(),multiply:z.record(z.string(),z.number()).optional()});
const Resource=z.object({label:z.string(),min:z.number().finite().optional(),max:z.number().finite().optional(),default:z.number().finite()}).strict().refine(x=>x.min===undefined||x.max===undefined||x.min<=x.max,{message:"resource min exceeds max"});
const InventoryEntry=z.object({itemId:Id,quantity:z.number().int().positive()}).strict();
const ActorTemplate=z.object({label:z.string().trim().min(1).max(80),resources:z.record(Id,z.number().finite()).optional(),attributes:z.record(Id,z.number().finite()).optional(),inventory:z.array(InventoryEntry).optional(),progression:z.record(Id,z.number().finite()).optional(),worldEntityKinds:z.array(Id).min(1).optional()}).strict();
const Effect=z.object({label:z.string(),duration:z.object({type:z.enum(["turns","rounds","session","permanent"]),value:z.number().int().positive().optional()}).strict().optional(),modifiers:z.record(Id,z.number().finite()).optional(),blockedActions:z.array(Id).min(1).optional()}).strict();
const Target=z.enum(["self","actor","none","single-actor","multiple-actors"]);
const StepCondition=z.object({previousOutcome:z.enum(["success","failure"])}).strict();
const ActionStep=z.union([
 z.object({check:z.object({id:Id,against:z.union([z.number().finite(),z.string()]).optional()}).strict(),when:StepCondition.optional()}).strict(),
 z.object({roll:z.object({id:Id,dice:z.string()}).strict(),when:StepCondition.optional()}).strict(),
 z.object({resource:z.object({target:z.enum(["actor","target"]),resource:Id,operation:z.enum(["add","subtract","set"]),value:z.union([z.number().finite(),z.string()])}).strict(),when:StepCondition.optional()}).strict(),
 z.object({effect:z.object({target:z.enum(["actor","target"]),id:Id}).strict(),when:StepCondition.optional()}).strict()
]);
const Action=z.union([
 z.object({label:z.string(),target:Target,steps:z.array(ActionStep).min(1)}).strict(),
 z.object({label:z.string(),target:Target,kind:z.enum(["check","resource","effect","custom"]),checkId:Id.optional(),resource:Id.optional(),operation:z.enum(["add","subtract","set"]).optional(),amount:z.number().finite().optional(),effectId:Id.optional()}).strict()
]);
const CharacterConditionSchema=z.object({field:Id,equals:z.unknown().optional(),in:z.array(z.unknown()).min(1).optional()}).strict().refine(value=>(value.equals===undefined)!==(value.in===undefined),{message:"character condition requires exactly one comparator"});
const CharacterField=z.object({id:Id,label:z.string(),type:z.enum(["text","choice","number","asset"]),required:z.boolean().optional(),options:z.array(z.object({value:z.string(),label:z.string()}).strict()).min(1).optional(),min:z.number().finite().optional(),max:z.number().finite().optional(),minLength:z.number().int().nonnegative().optional(),maxLength:z.number().int().positive().max(200).optional(),pattern:z.string().max(200).optional(),default:z.unknown().optional(),when:CharacterConditionSchema.optional()}).strict();
const StartingEntry=z.object({id:Id,quantity:z.number().int().positive().optional(),value:z.unknown().optional(),when:CharacterConditionSchema.optional()}).strict();
const CharacterCreation=z.object({schemaVersion:z.string().min(1).default("1"),steps:z.array(z.object({id:Id,title:z.string(),fields:z.array(CharacterField).min(1),when:CharacterConditionSchema.optional()}).strict()).min(1),calculated:z.array(z.object({id:Id,operation:z.enum(["sum","copy"]),fields:z.array(Id).min(1)}).strict()).optional(),starting:z.object({progression:z.record(z.string(),z.unknown()).optional(),resources:z.record(Id,z.number().finite()).optional(),inventory:z.array(StartingEntry).optional(),traits:z.array(StartingEntry).optional(),assets:z.array(StartingEntry).optional()}).strict().optional(),portability:z.object({rules:z.array(z.object({fromPackId:z.string().min(1),fromVersions:z.array(z.string()).min(1),fromSchemaVersions:z.array(z.string()).min(1).optional(),mode:z.enum(["accept","normalize","migrate"]),fieldMap:z.record(Id,Id).optional(),defaults:z.record(Id,z.unknown()).optional()}).strict()).default([])}).strict().optional()}).strict();
const Critical=z.object({rollTotalAtLeast:z.number().finite()}).strict(),CriticalFailure=z.object({rollTotalAtMost:z.number().finite()}).strict();
const Item=z.object({label:z.string().trim().min(1),stackLimit:z.number().int().positive().optional()}).strict();
const Progression=z.object({label:z.string().trim().min(1),min:z.number().finite().optional(),max:z.number().finite().optional(),default:z.number().finite()}).strict().refine(x=>x.min===undefined||x.max===undefined||x.min<=x.max,{message:"progression min exceeds max"});
export const PackSchema=z.object({questions:z.array(Question),generators:z.record(z.string(),Generator),templates:z.record(z.string(),Template),traits:z.record(z.string(),Trait).optional(),relations:z.array(z.any()).optional(),constraints:z.array(z.any()).optional(),dependencies:z.array(z.any()).optional(),characterCreation:CharacterCreation.optional(),checks:z.record(z.string(),z.object({label:z.string(),dice:z.string(),modifierField:Id.optional(),criticalSuccess:Critical.optional(),criticalFailure:CriticalFailure.optional()}).strict()).optional(),
resources:z.record(Id,Resource).optional(),effects:z.record(Id,Effect).optional(),actions:z.record(Id,Action).optional(),items:z.record(Id,Item).optional(),progression:z.record(Id,Progression).optional(),locations:z.object({worldEntityKinds:z.array(Id).min(1)}).strict().optional(),actorTemplates:z.record(Id,ActorTemplate).optional(),encounter:z.object({orderingPolicy:z.enum(["none","fixed","rolled","attribute","custom"]),attributeField:Id.optional()}).strict().optional()});
export type LoadedWorldPack={manifest:z.infer<typeof ManifestSchema>;content:z.infer<typeof PackSchema>;root:string;assets:string[]};
async function files(root:string,cur:string):Promise<string[]>{let out:string[]=[];for(const e of await readdir(cur,{withFileTypes:true}).catch(()=>[])){const p=join(cur,e.name);if(e.isDirectory())out.push(...await files(root,p));else out.push(relative(root,p))}return out}
export async function loadWorldPack(input:string):Promise<LoadedWorldPack>{const root=resolve(input),manifest=ManifestSchema.parse(YAML.parse(await readFile(join(root,"manifest.yaml"),"utf8"))),content=PackSchema.parse(YAML.parse(await readFile(join(root,"pack.yaml"),"utf8")));if(!content.templates[manifest.entryTemplate])throw Error(`Missing entry template ${manifest.entryTemplate}`);
 const inventory=(entries:{itemId:string;quantity:number}[],owner:string)=>{const seen=new Set<string>();for(const entry of entries){const definition=content.items?.[entry.itemId];if(!definition)throw Error(`${owner}: unknown item ${entry.itemId}`);if(seen.has(entry.itemId))throw Error(`${owner}: duplicate item ${entry.itemId}`);if(definition.stackLimit!==undefined&&entry.quantity>definition.stackLimit)throw Error(`${owner}: item ${entry.itemId} exceeds stack limit`);seen.add(entry.itemId)}};
 for(const[id,t]of Object.entries(content.templates)){for(const v of Object.values(t.values??{}))if((v as any).generator&&!content.generators[(v as any).generator])throw Error(`Template ${id}: missing generator ${(v as any).generator}`);for(const c of Object.values(t.components??{})){if(!content.templates[c.template])throw Error(`Template ${id}: missing template ${c.template}`);if((c.count as any)?.generator&&!content.generators[(c.count as any).generator])throw Error(`Template ${id}: missing count generator ${(c.count as any).generator}`)}for(const tr of t.traits??[])if(!content.traits?.[tr])throw Error(`Template ${id}: missing trait ${tr}`)}
 for(const[id,action]of Object.entries(content.actions??{})){
  if("steps" in action){for(const step of action.steps){if("check" in step&&!content.checks?.[step.check.id])throw Error(`Action ${id}: missing check ${step.check.id}`);if("resource" in step&&!content.resources?.[step.resource.resource])throw Error(`Action ${id}: missing resource ${step.resource.resource}`);if("effect" in step&&!content.effects?.[step.effect.id])throw Error(`Action ${id}: missing effect ${step.effect.id}`)}}
  else{if(action.checkId&&!content.checks?.[action.checkId])throw Error(`Action ${id}: missing check ${action.checkId}`);if(action.resource&&!content.resources?.[action.resource])throw Error(`Action ${id}: missing resource ${action.resource}`);if(action.effectId&&!content.effects?.[action.effectId])throw Error(`Action ${id}: missing effect ${action.effectId}`)}
 }
 for(const[id,template]of Object.entries(content.actorTemplates??{})){
  for(const[resourceId,value]of Object.entries(template.resources??{})){const resource=content.resources?.[resourceId];if(!resource)throw Error(`Actor template ${id}: unknown resource ${resourceId}`);if(resource.min!==undefined&&value<resource.min||resource.max!==undefined&&value>resource.max)throw Error(`Actor template ${id}: resource ${resourceId} outside bounds`)}
  const kinds=new Set(Object.values(content.templates).map(value=>value.kind));
  for(const kind of template.worldEntityKinds??[])if(!kinds.has(kind))throw Error(`Actor template ${id}: unknown World entity kind ${kind}`);
  inventory(template.inventory??[],`Actor template ${id}`);
  for(const[progressionId,value]of Object.entries(template.progression??{})){const definition=content.progression?.[progressionId];if(!definition)throw Error(`Actor template ${id}: unknown progression ${progressionId}`);if(definition.min!==undefined&&value<definition.min||definition.max!==undefined&&value>definition.max)throw Error(`Actor template ${id}: progression ${progressionId} outside bounds`)}
 }
 for(const kind of content.locations?.worldEntityKinds??[])if(!Object.values(content.templates).some(template=>template.kind===kind))throw Error(`Locations: unknown World entity kind ${kind}`);
 for(const[id,definition]of Object.entries(content.progression??{}))if(definition.min!==undefined&&definition.default<definition.min||definition.max!==undefined&&definition.default>definition.max)throw Error(`Progression ${id}: default outside bounds`);
 if(content.characterCreation){
  const schema=content.characterCreation,fields=schema.steps.flatMap(step=>step.fields),ids=new Set(fields.map(field=>field.id));
  if(ids.size!==fields.length)throw Error("Character fields must have unique IDs");
  const condition=(value:{field:string}|undefined,where:string)=>{if(value&&!ids.has(value.field))throw Error(`${where}: unknown character field ${value.field}`)};
  for(const step of schema.steps){condition(step.when,`Character step ${step.id}`);for(const field of step.fields){condition(field.when,`Character field ${field.id}`);if((field.type==="choice"||field.type==="asset")&&!field.options)throw Error(`Character field ${field.id}: options required`);if(field.pattern)try{new RegExp(field.pattern)}catch{throw Error(`Character field ${field.id}: invalid pattern`)}}}
  const calculatedIds=new Set<string>();for(const calculated of schema.calculated??[]){if(ids.has(calculated.id)||calculatedIds.has(calculated.id))throw Error(`Calculated character value duplicates field or calculation ${calculated.id}`);calculatedIds.add(calculated.id);for(const field of calculated.fields)if(!ids.has(field))throw Error(`Calculated character value ${calculated.id}: unknown field ${field}`)}
  for(const entry of [...schema.starting?.inventory??[],...schema.starting?.traits??[],...schema.starting?.assets??[]])condition(entry.when,`Character starting entry ${entry.id}`);
  inventory((schema.starting?.inventory??[]).map(entry=>({itemId:entry.id,quantity:entry.quantity??1})),"Character starting inventory");
  for(const[resourceId,value]of Object.entries(schema.starting?.resources??{})){const definition=content.resources?.[resourceId];if(!definition)throw Error(`Character starting resources: unknown resource ${resourceId}`);if(definition.min!==undefined&&value<definition.min||definition.max!==undefined&&value>definition.max)throw Error(`Character starting resource ${resourceId} outside bounds`)}
  for(const[progressionId,value]of Object.entries(schema.starting?.progression??{})){const definition=content.progression?.[progressionId];if(!definition)throw Error(`Character starting progression: unknown progression ${progressionId}`);if(typeof value!=="number"||definition.min!==undefined&&value<definition.min||definition.max!==undefined&&value>definition.max)throw Error(`Character starting progression ${progressionId} outside bounds`)}
  for(const rule of schema.portability?.rules??[]){if(rule.mode==="migrate"&&!rule.fieldMap)throw Error(`Character migration from ${rule.fromPackId} requires fieldMap`);for(const target of Object.keys(rule.fieldMap??{}))if(!ids.has(target))throw Error(`Character migration: unknown target field ${target}`);for(const target of Object.keys(rule.defaults??{}))if(!ids.has(target))throw Error(`Character migration: unknown default field ${target}`)}
 }
 for(const[effectId,effect]of Object.entries(content.effects??{}))for(const actionId of effect.blockedActions??[])if(!content.actions?.[actionId])throw Error(`Effect ${effectId}: unknown blocked action ${actionId}`);
 validateRuntimePack(content);
 return{manifest,content,root,assets:await files(root,join(root,"assets"))}}
export function validateWorldPack(p:LoadedWorldPack){return{valid:true as const,id:p.manifest.id,version:p.manifest.version,questions:p.content.questions.length,templates:Object.keys(p.content.templates).length,generators:Object.keys(p.content.generators).length,traits:Object.keys(p.content.traits??{}).length,assets:p.assets.length}}
export function characterConditionMatches(condition:CharacterCondition|undefined,values:Record<string,unknown>){if(!condition)return true;const value=values[condition.field];return condition.in?condition.in.some(candidate=>Object.is(candidate,value)):Object.is(condition.equals,value)}
export function validateCharacterValues(schema:CharacterCreationSchema,values:unknown):Record<string,unknown>{
 if(!values||typeof values!=="object"||Array.isArray(values))throw Error("character values must be an object");
 const fields=schema.steps.filter(step=>characterConditionMatches(step.when,values as Record<string,unknown>)).flatMap(step=>step.fields),allowed=new Set(fields.map(field=>field.id)),data={...(values as Record<string,unknown>)};
 for(const field of fields)if(characterConditionMatches(field.when,data)&&data[field.id]===undefined&&field.default!==undefined)data[field.id]=field.default;
 for(const key of Object.keys(data))if(!allowed.has(key)&&!schema.calculated?.some(value=>value.id===key))throw Error(`unknown character field ${key}`);
 for(const field of fields){if(!characterConditionMatches(field.when,data)){if(data[field.id]!==undefined)throw Error(`inactive character field ${field.id}`);delete data[field.id];continue}const value=data[field.id];if(value===undefined||value===null||value===""){if(field.required)throw Error(`required character field ${field.id}`);continue}
  if(field.type==="text"&&(typeof value!=="string"||value.length>200||field.minLength!==undefined&&value.length<field.minLength||field.maxLength!==undefined&&value.length>field.maxLength||field.pattern!==undefined&&!new RegExp(field.pattern).test(value)))throw Error(`invalid text field ${field.id}`);
  if(field.type==="number"&&(typeof value!=="number"||!Number.isFinite(value)||field.min!==undefined&&value<field.min||field.max!==undefined&&value>field.max))throw Error(`invalid number field ${field.id}`);
  if((field.type==="choice"||field.type==="asset")&&!field.options?.some(option=>option.value===value))throw Error(`invalid choice field ${field.id}`);
 }
 for(const calculated of schema.calculated??[]){const source=calculated.fields.map(field=>data[field]);if(calculated.operation==="copy")data[calculated.id]=source[0];else{if(source.some(value=>typeof value!=="number"||!Number.isFinite(value)))throw Error(`invalid calculated value ${calculated.id}`);data[calculated.id]=(source as number[]).reduce((sum,value)=>sum+value,0)}}
 return data;
}
export function buildCharacterState(schema:CharacterCreationSchema,values:unknown){const validated=validateCharacterValues(schema,values),active=<T extends{id:string;when?:CharacterCondition}>(entries:T[]|undefined)=>entries?.filter(entry=>characterConditionMatches(entry.when,validated))??[];return{values:validated,progression:{...(schema.starting?.progression??{})},resources:{...(schema.starting?.resources??{})},inventory:active(schema.starting?.inventory).map(({when,...entry})=>entry),traits:active(schema.starting?.traits).map(entry=>entry.id),assets:Object.fromEntries(active(schema.starting?.assets).map(entry=>[entry.id,entry.value??true]))}}
export function evaluateCharacterPortability(packId:string,packVersion:string,schema:CharacterCreationSchema,character:Pick<Character,"worldPackId"|"worldPackVersion"|"characterSchemaVersion"|"values">):CharacterPortability{
 if(character.worldPackId===packId&&character.worldPackVersion===packVersion&&character.characterSchemaVersion===(schema.schemaVersion??"1"))return{compatible:true,mode:"exact",reason:"exact Pack and character schema match",values:validateCharacterValues(schema,character.values)};
 const rule=schema.portability?.rules.find(value=>value.fromPackId===character.worldPackId&&value.fromVersions.includes(character.worldPackVersion)&&(!value.fromSchemaVersions||value.fromSchemaVersions.includes(character.characterSchemaVersion)));if(!rule)return{compatible:false,mode:"reject",reason:"no explicit Pack portability rule"};
 try{let candidate:Record<string,unknown>={...character.values};if(rule.mode==="normalize")candidate=Object.fromEntries(Object.entries(candidate).filter(([key])=>schema.steps.some(step=>step.fields.some(field=>field.id===key))));if(rule.mode==="migrate")candidate=Object.fromEntries(Object.entries(rule.fieldMap??{}).map(([target,source])=>[target,character.values[source]]));candidate={...(rule.defaults??{}),...candidate};return{compatible:true,mode:rule.mode,reason:`explicit ${rule.mode} rule`,values:validateCharacterValues(schema,candidate)}}catch(error){return{compatible:false,mode:"reject",reason:error instanceof Error?error.message:"character portability failed"}}
}
